Repository CliMA/Oceananigans.jl, pull requests merged in 2019-10, with the labels that each got.

#425 Examples: more, better, tested
  .gitlab-ci.yml
  .travis.yml
  Manifest.toml
  Project.toml
  examples/deepening_mixed_layer.jl
  examples/internal_wave.jl
  examples/ocean_wind_mixing_and_convection.jl
  examples/simple_diffusion.jl
  examples/simple_diffusion.md
  examples/two_dimensional_turbulence.jl
  examples/utils.jl
  src/coriolis.jl
  test/test_examples.jl
Labels: documentation

#450 Update rising thermal bubble example in README
  README.md
Labels: bug, documentation

#436 Add contributing section to README and contributor's guide
  CONTRIBUTING.md
  README.md
Labels: documentation

#467 Allow v1.3 GPU tests to fail on GitLab CI
  .gitlab-ci.yml
Labels: Testing, bug

#472 Use coverage job from earlier GitLab CI yaml
  .gitlab-ci.yml
Labels: Testing

#381 Stratified Couette flow verification
  test/runtests.jl
  test/test_verification.jl
  verification/stratified_couette_flow/run_stratified_couette_flow_simulations.jl
  verification/stratified_couette_flow/stratified_couette_flow.jl
  verification/stratified_couette_flow/stratified_couette_flow_analysis.jl
Labels: Testing, numerics, science

#435 Add table of contents to README
  README.md
Labels: documentation

#452 Arbitrary tracers
  benchmark/benchmark_static_ocean.jl
  benchmark/benchmark_tracers.jl
  benchmark/benchmark_utils.jl
  examples/internal_wave.jl
  examples/ocean_convection_with_plankton.jl
  examples/simple_diffusion.jl
  examples/two_dimensional_turbulence.jl
  src/Oceananigans.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/constant_anisotropic_diffusivity.jl
  src/TurbulenceClosures/constant_diffusivity_closures.jl
  src/TurbulenceClosures/constant_isotropic_diffusivity.jl
  src/TurbulenceClosures/rozema_anisotropic_minimum_dissipation.jl
  src/TurbulenceClosures/smagorinsky.jl
  src/TurbulenceClosures/turbulence_closure_diagnostics.jl
  src/TurbulenceClosures/turbulence_closure_utils.jl
  src/TurbulenceClosures/verstappen_anisotropic_minimum_dissipation.jl
  src/boundary_conditions.jl
  src/buoyancy.jl
  src/forcing.jl
  src/models.jl
  src/time_steppers.jl
  src/utils.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/runtests.jl
  test/test_buoyancy.jl
  test/test_dynamics.jl
  test/test_examples.jl
  test/test_output_writers.jl
  test/test_regression.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
  verification/stratified_couette_flow/stratified_couette_flow.jl
Labels: cleanup, feature, numerics, performance

#474 All the documentation!
  .gitignore
  .travis.yml
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/algorithm.md
  docs/src/assets/single_volume.png
  docs/src/examples.md
  docs/src/examples/rising_thermal_bubble.md
  docs/src/gallery.md
  docs/src/index.md
  docs/src/internal/fields.md
  docs/src/internal/grids.md
  docs/src/internal/operators.md
  docs/src/library.md
  docs/src/manual/boundary_conditions.md
  docs/src/manual/equations.md
  docs/src/manual/finite_volume.md
  docs/src/manual/fractional_step.md
  docs/src/manual/large_eddy_simulation.md
  docs/src/manual/model_setup.md
  docs/src/manual/overview.md
  docs/src/manual/poisson_solvers.md
  docs/src/manual/spatial_operators.md
  docs/src/manual/staggered_grid.md
  docs/src/manual/time_stepping.md
  docs/src/manual/turbulence_closures.md
  docs/src/verification/free_convection.md
  docs/src/verification/lid_driven_cavity.md
  docs/src/verification/stratified_couette_flow.md
  docs/src/verification/taylor_green_vortex.md
  examples/internal_wave.jl
  examples/simple_diffusion.jl
  examples/two_dimensional_turbulence.jl
  src/boundary_conditions.jl
  src/buoyancy.jl
  src/diagnostics.jl
  src/fields.jl
  src/forcing.jl
  src/grids.jl
  src/models.jl
  src/output_writers.jl
  test/test_examples.jl
Labels: documentation

#433 A fast netcdf output writer
  Manifest.toml
  Project.toml
  examples/netcdf_ouput_example.jl
  src/Oceananigans.jl
  src/output_writers.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/test_output_writers.jl
  test/test_regression.jl
Labels: feature

#462 FINALLY reverse the k index
  src/Oceananigans.jl
  src/Operators/ops_regular_cartesian_grid.jl
  src/TurbulenceClosures/closure_operators.jl
  src/boundary_conditions.jl
  src/diagnostics.jl
  src/grids.jl
  src/halo_regions.jl
  src/output_writers.jl
  src/time_steppers.jl
  src/utils.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/runtests.jl
  test/test_dynamics.jl
  test/test_grids.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
Labels: cleanup, numerics

#464 Allow users to specify the domain when creating a `RegularCartes…
  benchmark/benchmark_static_ocean.jl
  benchmark/benchmark_tracers.jl
  examples/internal_wave.jl
  examples/netcdf_ouput_example.jl
  examples/ocean_convection_with_plankton.jl
  examples/ocean_wind_mixing_and_convection.jl
  examples/simple_diffusion.jl
  examples/two_dimensional_turbulence.jl
  src/fields.jl
  src/grids.jl
  src/models.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/test_buoyancy.jl
  test/test_dynamics.jl
  test/test_fields.jl
  test/test_grids.jl
  test/test_halo_regions.jl
  test/test_models.jl
  test/test_operators.jl
  test/test_poisson_solvers.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
  verification/stratified_couette_flow/stratified_couette_flow.jl
Labels: cleanup, feature

#463 AbstractOperations for diagnostics (and beyond...)
  Manifest.toml
  Project.toml
  examples/internal_wave.jl
  examples/ocean_convection_with_plankton.jl
  examples/ocean_wind_mixing_and_convection.jl
  examples/simple_diffusion.jl
  examples/two_dimensional_turbulence.jl
  src/AbstractOperations/AbstractOperations.jl
  src/AbstractOperations/binary_operations.jl
  src/AbstractOperations/computations.jl
  src/AbstractOperations/derivatives.jl
  src/AbstractOperations/function_fields.jl
  src/AbstractOperations/grid_validation.jl
  src/AbstractOperations/interpolation_utils.jl
  src/AbstractOperations/multiary_operations.jl
  src/AbstractOperations/show_abstract_operations.jl
  src/AbstractOperations/unary_operations.jl
  src/Oceananigans.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/closure_operators.jl
  src/TurbulenceClosures/smagorinsky.jl
  src/TurbulenceClosures/verstappen_anisotropic_minimum_dissipation.jl
  src/diagnostics.jl
  src/fields.jl
  src/forcing.jl
  src/grids.jl
  src/output_writers.jl
  src/time_steppers.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/runtests.jl
  test/test_abstract_operations.jl
  test/test_boundary_conditions.jl
  test/test_diagnostics.jl
  test/test_dynamics.jl
  test/test_fields.jl
  test/test_halo_regions.jl
  test/test_models.jl
  test/test_output_writers.jl
  test/test_poisson_solvers.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
  verification/stratified_couette_flow/stratified_couette_flow.jl
Labels: abstractions, feature

#505 Time-stepper cleanup and modularization
  src/Oceananigans.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/adams_bashforth.jl
  src/TimeSteppers/kernels.jl
  src/models.jl
  src/output_writers.jl
  src/time_steppers.jl
  src/utils.jl
  test/runtests.jl
  test/test_time_stepping.jl
Labels: cleanup

#283 Finite volume operators through multiple dispatch
  src/Operators/README
  src/Operators/areas_and_volumes.jl
  src/Operators/derivative_operators.jl
  src/Operators/difference_operators.jl
  src/Operators/diffusion_operators.jl
  src/Operators/divergence_operators.jl
  src/Operators/interpolation_operators.jl
  src/Operators/laplacian_operators.jl
  src/Operators/momentum_advection_operators.jl
  src/Operators/tracer_advection_operators.jl
  src/Operators/viscous_dissipation_operators.jl
Labels: abstractions, cleanup, feature

#512 Submodules for grids, solvers, diagnostics, and output writers
  examples/ocean_wind_mixing_and_convection.jl
  src/AbstractOperations/AbstractOperations.jl
  src/Diagnostics/Diagnostics.jl
  src/Diagnostics/cfl.jl
  src/Diagnostics/diagnostics_kernels.jl
  src/Diagnostics/field_maximum.jl
  src/Diagnostics/horizontal_average.jl
  src/Diagnostics/nan_checker.jl
  src/Diagnostics/timeseries.jl
  src/Grids/Grids.jl
  src/Grids/grid_utils.jl
  src/Grids/regular_cartesian_grid.jl
  src/Oceananigans.jl
  src/Operators/ops_regular_cartesian_grid.jl
  src/OutputWriters/OutputWriters.jl
  src/OutputWriters/checkpointer.jl
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/OutputWriters/output_writer_utils.jl
  src/Solvers/Solvers.jl
  src/Solvers/poisson_solver_cpu.jl
  src/Solvers/poisson_solver_gpu.jl
  src/Solvers/solver_utils.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/adams_bashforth.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/diagnostics.jl
  src/fields.jl
  src/output_writers.jl
  src/poisson_solvers.jl
  test/runtests.jl
Labels: cleanup
