Repository CliMA/Oceananigans.jl, pull requests merged in 2019-06, with the labels that each got.

#264 No more scalar operations on CuArrays.
  src/Oceananigans.jl
  src/fields.jl
  src/models.jl
Labels: bug, performance

#253 Halo regions v2: filling halos and faster operations
  Manifest.toml
  examples/rising_thermal_bubble_2d.jl
  examples/rising_thermal_bubble_3d_gpu.jl
  src/Oceananigans.jl
  src/closures/closure_operators.jl
  src/closures/turbulence_closures.jl
  src/fields.jl
  src/operators/ops_regular_cartesian_grid.jl
  src/time_steppers.jl
  src/utils.jl
  test/runtests.jl
  test/test_dynamics.jl
  test/test_halo_regions.jl
  test/test_poisson_solvers.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
Labels: feature

#268 Fill halo regions on CuArrays instead of OffsetArrays
  src/fields.jl
Labels: GPU, bug, performance

#256 Polishing docs
  docs/src/algorithm.md
Labels: documentation

#288 Explicit default boundary conditions
  src/Oceananigans.jl
  src/boundary_conditions.jl
  src/time_steppers.jl
Labels: cleanup

#297 Adaptive time stepping through wizardry
  src/time_step_utils.jl
Labels: feature, numerics

#290 Reentrant channel model, for real this time (+ lots of cleanup)
  sandbox/baroclinic_eddies.jl
  src/Oceananigans.jl
  src/boundary_conditions.jl
  src/diagnostics.jl
  src/fields.jl
  src/fieldsets.jl
  src/halo_regions.jl
  src/models.jl
  src/operators/operators.jl
  src/operators/ops_regular_cartesian_grid.jl
  src/output_writers.jl
  src/poisson_solvers.jl
  src/time_steppers.jl
  test/runtests.jl
  test/test_boundary_conditions.jl
  test/test_dynamics.jl
  test/test_fields.jl
  test/test_forcings.jl
  test/test_grids.jl
  test/test_halo_regions.jl
  test/test_models.jl
  test/test_operators.jl
  test/test_output_writers.jl
  test/test_poisson_solvers.jl
  test/test_regression.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
Labels: feature, numerics

#301 Eddying channel script
  .gitignore
  sandbox/baroclinic_eddies.jl
  sandbox/eddying_channel.jl
  sandbox/plot_channel_frames.py
Labels: science

#302 Faster model with dynamic launch configuration by @maleadt
  Manifest.toml
  src/diagnostics.jl
  src/time_steppers.jl
  test/test_poisson_solvers.jl
Labels: GPU, performance

#303 Idealized seasonal cycle simulation v2
  sandbox/idealized_seasonal_cycle.jl
  src/Oceananigans.jl
  src/fields.jl
  src/time_step_utils.jl
Labels: science

#304 Hydrothermal plumes simulation v2
  sandbox/europa_hydrothermal_plumes.jl
  src/Oceananigans.jl
  src/planetary_constants.jl
Labels: science
