Repository CliMA/Oceananigans.jl, pull requests merged in 2019-08, with the labels that each got.

#325 Minor code simplifications
  src/Oceananigans.jl
  src/fields.jl
  src/fieldsets.jl
  src/forcing.jl
  src/models.jl
  src/operators/ops_regular_cartesian_grid.jl
  src/time_steppers.jl
  test/test_regression.jl
  test/test_time_stepping.jl
Labels: cleanup

#322 Fix calculation of Value boundary conditions
  src/boundary_conditions.jl
  src/diagnostics.jl
  src/output_writers.jl
  src/time_steppers.jl
  test/data_rayleigh_benard_regression.jld2
  test/test_regression.jl
Labels: bug

#336 Pearson vortex test
  test/test_dynamics.jl
Labels: Testing

#337 Kernel for setting initial conditions so set_ic! runs fast on GPUs
  examples/utils.jl
  sandbox/eddying_channel.jl
  src/fields.jl
  src/time_steppers.jl
  src/utils.jl
  test/test_models.jl
Labels: GPU, Testing, performance

#340 Remove JLD and HDF5 dependency
  Manifest.toml
  Project.toml
Labels: cleanup

#343 Robust setting of fields
  examples/deepening_mixed_layer.jl
  examples/utils.jl
  sandbox/eddying_channel.jl
  src/Oceananigans.jl
  src/fields.jl
  src/models.jl
  src/operators/ops_regular_cartesian_grid.jl
  src/time_steppers.jl
  src/utils.jl
  test/runtests.jl
  test/test_examples.jl
  test/test_fields.jl
  test/test_models.jl
Labels: GPU, feature, performance

#349 Clean trailing whitespace and convert tabs to spaces.
  docs/src/algorithm.md
  examples/deepening_mixed_layer.jl
  sandbox/do_cthulhu.jl
  sandbox/plot_channel_frames.py
  sandbox/plot_oceananigans_output_contourf3d.py
  sandbox/rayleigh_benard_passive_tracer.jl
  sandbox/simple_flux.jl
  src/boundary_conditions.jl
  src/fields.jl
  src/halo_regions.jl
  src/models.jl
  src/output_writers.jl
  src/poisson_solvers.jl
  src/time_steppers.jl
  src/utils.jl
  test/test_boundary_conditions.jl
  test/test_forcings.jl
  test/test_regression.jl
Labels: cleanup

#355 Dirchlet and Neumann aliases for Value and Gradient boundary conditions
  src/Oceananigans.jl
  src/boundary_conditions.jl
Labels: cleanup

#350 Verbose and maximum filesize options for JLD2 output writer
  src/Oceananigans.jl
  src/output_writers.jl
  src/utils.jl
  test/test_output_writers.jl
  test/test_regression.jl
Labels: feature

#368 Nuke broken tests
  test/deep_convection_regression_10.nc
  test/runtests.jl
  test/test_examples.jl
  test/test_regression.jl
Labels: Testing, cleanup

#367 Nuke sandbox
  sandbox/deep_convection.jl
  sandbox/do_cthulhu.jl
  sandbox/eddying_channel.jl
  sandbox/europa_hydrothermal_plumes.jl
  sandbox/free_convection_cosine_cooling.jl
  sandbox/idealized_seasonal_cycle.jl
  sandbox/plot_channel_frames.py
  sandbox/plot_oceananigans_output_contourf3d.py
  sandbox/plot_oceananigans_output_pcolormesh3d.py
  sandbox/rayleigh_benard_passive_tracer.jl
  sandbox/rayleigh_taylor_instability.jl
  sandbox/seasonal_cycle.jl
  sandbox/simple_flux.jl
  sandbox/stratified_couette_flow.jl
Labels: cleanup

#379 Fix diagnostics test problem size
  test/test_diagnostics.jl
Labels: Testing, cleanup

#378 Update CUDA packages to get rid of CUDA errors on CPU and use CUDAapi.has_cuda()
  Manifest.toml
  Project.toml
  examples/deepening_mixed_layer.jl
  src/Oceananigans.jl
  src/models.jl
Labels: cleanup

#383 New and more correct turbulence closures
  src/boundary_conditions.jl
  src/models.jl
  src/time_steppers.jl
  src/turbulence_closures/TurbulenceClosures.jl
  src/turbulence_closures/anisotropic_minimum_dissipation.jl
  src/turbulence_closures/closure_operators.jl
  src/turbulence_closures/constant_diffusivity_closures.jl
  src/turbulence_closures/constant_smagorinsky.jl
  src/turbulence_closures/rozema_anisotropic_minimum_dissipation.jl
  src/turbulence_closures/smagorinsky.jl
  src/turbulence_closures/velocity_gradients.jl
  src/turbulence_closures/velocity_tracer_gradients.jl
  src/turbulence_closures/verstappen_anisotropic_minimum_dissipation.jl
  test/test_turbulence_closures.jl
Labels: bug, feature, science

#382 Verbose flag for checkpointer
  src/output_writers.jl
Labels: feature

#380 Clean up benchmark scripts
  benchmark/benchmark_eddying_channel.jl
  benchmark/benchmark_free_convection.jl
  benchmark/benchmark_static_ocean.jl
  benchmark/benchmark_turbulence_closures.jl
  benchmark/benchmark_utils.jl
Labels: cleanup
