Repository CliMA/Oceananigans.jl, pull requests merged in 2019-09, with the labels that each got.

#386 Improve HorizontalAverage and time to write function
  src/diagnostics.jl
  src/halo_regions.jl
  src/output_writers.jl
  src/planetary_constants.jl
  src/time_steppers.jl
  src/utils.jl
Labels: cleanup

#388 Update CUDA packages (attempt 2)
  Manifest.toml
  Project.toml
  examples/deepening_mixed_layer.jl
  src/Oceananigans.jl
  src/models.jl
  test/test_forcings.jl
Labels: GPU

#389 [WIP] Use halo regions to enforce Value and Gradient boundary co…
  src/Oceananigans.jl
  src/boundary_conditions.jl
  src/diagnostics.jl
  src/halo_regions.jl
  src/models.jl
  src/output_writers.jl
  src/poisson_solvers.jl
  src/time_steppers.jl
  src/utils.jl
  test/test_halo_regions.jl
  test/test_operators.jl
  test/test_poisson_solvers.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
Labels: numerics

#395 Parameters field in Model for user convenience
  benchmark/benchmark_forcing_functions.jl
  src/boundary_conditions.jl
  src/models.jl
  src/time_steppers.jl
  test/test_forcings.jl
  test/test_regression.jl
Labels: feature

#396 Update README: installation instructions and development team
  README.md
Labels: documentation

#402 Use {Flux, Nothing} for default boundary condition type rather than {Flux, 0}
  src/boundary_conditions.jl
Labels: cleanup

#398 Add warning if GPU model grid Nx, Ny are not multiple of 16
  src/models.jl
  test/test_models.jl
Labels: bug, cleanup

#401 Simplification and generalization of Model constructors
  README.md
  examples/deepening_mixed_layer.jl
  examples/internal_wave.jl
  src/Oceananigans.jl
  src/diagnostics.jl
  src/grids.jl
  src/models.jl
  src/output_writers.jl
  src/time_steppers.jl
  test/test_boundary_conditions.jl
  test/test_diagnostics.jl
  test/test_dynamics.jl
  test/test_forcings.jl
  test/test_models.jl
  test/test_output_writers.jl
  test/test_regression.jl
  test/test_time_stepping.jl
Labels: cleanup, feature

#405 Refactor boundary conditions container
  src/Oceananigans.jl
  src/boundary_conditions.jl
  src/halo_regions.jl
  src/models.jl
  src/poisson_solvers.jl
  src/time_steppers.jl
  test/test_boundary_conditions.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
Labels: cleanup

#406 Pre-documentation cleanup
  benchmark/benchmark_utils.jl
  examples/internal_wave.jl
  src/Oceananigans.jl
  src/diagnostics.jl
  src/equation_of_state.jl
  src/fields.jl
  src/grids.jl
  src/halo_regions.jl
  src/models.jl
  src/output_writers.jl
  src/planetary_constants.jl
  src/poisson_solvers.jl
  src/time_steppers.jl
  src/turbulence_closures/TurbulenceClosures.jl
  src/turbulence_closures/closure_operators.jl
  src/turbulence_closures/rozema_anisotropic_minimum_dissipation.jl
  src/turbulence_closures/smagorinsky.jl
  src/turbulence_closures/velocity_tracer_gradients.jl
  src/turbulence_closures/verstappen_anisotropic_minimum_dissipation.jl
  src/utils.jl
  test/test_boundary_conditions.jl
  test/test_dynamics.jl
  test/test_fields.jl
  test/test_grids.jl
  test/test_regression.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
Labels: cleanup

#407 Timeseries diagnostic and CFL utilities
  src/Oceananigans.jl
  src/diagnostics.jl
  src/models.jl
  src/output_writers.jl
  src/turbulence_closures/TurbulenceClosures.jl
  src/turbulence_closures/rozema_anisotropic_minimum_dissipation.jl
  src/turbulence_closures/smagorinsky.jl
  src/turbulence_closures/turbulence_closure_diagnostics.jl
  src/turbulence_closures/turbulence_closure_utils.jl
  src/turbulence_closures/verstappen_anisotropic_minimum_dissipation.jl
  src/utils.jl
  test/runtests.jl
  test/test_diagnostics.jl
Labels: cleanup, feature

#411 Put Diagnostics and OutputWriters into OrderedDicts, plus code f…
  Manifest.toml
  Project.toml
  src/Oceananigans.jl
  src/diagnostics.jl
  src/models.jl
  src/output_writers.jl
  src/time_steppers.jl
  src/utils.jl
  test/test_diagnostics.jl
Labels: feature

#410 Docstrings everywhere!
  src/Oceananigans.jl
  src/boundary_conditions.jl
  src/clock.jl
  src/diagnostics.jl
  src/equation_of_state.jl
  src/fields.jl
  src/grids.jl
  src/output_writers.jl
  src/planetary_constants.jl
  src/time_steppers.jl
  src/turbulence_closures/TurbulenceClosures.jl
  src/turbulence_closures/constant_diffusivity_closures.jl
  src/turbulence_closures/smagorinsky.jl
  src/turbulence_closures/verstappen_anisotropic_minimum_dissipation.jl
  src/utils.jl
  test/test_turbulence_closures.jl
Labels: documentation

#412 New abstractions for buoyancy and rotation
  src/Oceananigans.jl
  src/Operators/Operators.jl
  src/Operators/ops_regular_cartesian_grid.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/closure_operators.jl
  src/TurbulenceClosures/constant_diffusivity_closures.jl
  src/TurbulenceClosures/rozema_anisotropic_minimum_dissipation.jl
  src/TurbulenceClosures/smagorinsky.jl
  src/TurbulenceClosures/turbulence_closure_diagnostics.jl
  src/TurbulenceClosures/turbulence_closure_utils.jl
  src/TurbulenceClosures/velocity_tracer_gradients.jl
  src/TurbulenceClosures/verstappen_anisotropic_minimum_dissipation.jl
  src/buoyancy.jl
  src/clock.jl
  src/coriolis.jl
  src/equation_of_state.jl
  src/models.jl
  src/output_writers.jl
  src/planetary_constants.jl
  src/time_steppers.jl
  test/runtests.jl
  test/test_boundary_conditions.jl
  test/test_coriolis_buoyancy.jl
  test/test_dynamics.jl
  test/test_output_writers.jl
  test/test_poisson_solvers.jl
  test/test_regression.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
Labels: cleanup, feature

#418 Search and replace testing for example scripts
  examples/deepening_mixed_layer.jl
  test/runtests.jl
  test/test_examples.jl
Labels: Testing

#424 Fix example test
  examples/deepening_mixed_layer.jl
  test/test_examples.jl
Labels: Testing, bug

#426 Get rid of docs replacement warnings on CPU
  src/fields.jl
Labels: bug
