Repository CliMA/Oceananigans.jl, pull requests merged in 2019-12, with the labels that each got.

#558 Delete leftover JLD2 files before deploying docs
  docs/make.jl
Labels: cleanup

#560 Update public API documentation
  docs/src/library.md
Labels: documentation

#554 Update `DiffusiveCFL` docstring
  src/Diagnostics/cfl.jl
Labels: documentation

#548 Document convinient unit definitions
  src/utils.jl
Labels: documentation

#549 Test time-stepping with all turbulent diffusivity closures
  src/Operators/Operators.jl
  test/test_time_stepping.jl
Labels: Testing

#534 Model setup documentation for JOSS
  docs/make.jl
  docs/src/manual/boundary_conditions.md
  docs/src/manual/model_setup.md
  src/OutputWriters/jld2_output_writer.jl
Labels: documentation

#551 Banners like ##### instead of ####
  benchmark/benchmark_forcing_functions.jl
  benchmark/benchmark_tracers.jl
  docs/make.jl
  docs/src/manual/physics.md
  examples/netcdf_ouput_example.jl
  src/Diagnostics/diagnostics_kernels.jl
  src/Operators/areas_and_volumes.jl
  src/Operators/derivative_operators.jl
  src/Operators/difference_operators.jl
  src/Operators/divergence_operators.jl
  src/Operators/interpolation_operators.jl
  src/Operators/laplacian_operators.jl
  src/Operators/momentum_advection_operators.jl
  src/Operators/tracer_advection_operators.jl
  src/OutputWriters/output_writer_utils.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/diffusion_operators.jl
  src/TurbulenceClosures/viscous_dissipation_operators.jl
  src/halo_regions.jl
  src/utils.jl
  verification/stratified_couette_flow/stratified_couette_flow_analysis.jl
Labels: cleanup

#556 Update `NetCDFOutputWriter` docstring and clobber default
  src/OutputWriters/netcdf_output_writer.jl
Labels: bug, documentation

#533 General-purpose batched tridiagonal solver
  Manifest.toml
  Project.toml
  src/Solvers/Solvers.jl
  src/Solvers/batched_tridiagonal_solver.jl
  src/utils.jl
  test/runtests.jl
  test/test_solvers.jl
Labels: feature, numerics

#561 Update stratified Couette flow verification experiment for JOSS
  .travis.yml
  docs/Manifest.toml
  docs/make.jl
  docs/src/verification/plots_stratified_couette_flow_stratified_couette_flow_LES_profiles.png
  docs/src/verification/plots_stratified_couette_flow_stratified_couette_flow_Re_Nu_scatter.png
  docs/src/verification/plots_stratified_couette_flow_stratified_couette_flow_Re_Nu_timeseries.png
  docs/src/verification/plots_stratified_couette_flow_stratified_couette_flow_velocity_temperature_profiles.png
  docs/src/verification/plots_stratified_couette_flow_stratified_couette_flow_velocity_temperature_slices.png
  docs/src/verification/stratified_couette_flow.md
  verification/stratified_couette_flow/stratified_couette_flow.jl
  verification/stratified_couette_flow/stratified_couette_flow_analysis.jl
Labels: documentation

#546 Support for applying channel boundary conditions
  src/AbstractOperations/computations.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/adams_bashforth.jl
  src/TimeSteppers/kernels.jl
  src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl
  src/TurbulenceClosures/turbulence_closure_implementations/verstappen_anisotropic_minimum_dissipation.jl
  src/boundary_conditions.jl
  src/fields.jl
  src/halo_regions.jl
  src/utils.jl
  test/test_time_stepping.jl
Labels: feature

#559 On CI servers select the GPU with the most memory
  test/runtests.jl
Labels: Testing

#478 Logging
  Manifest.toml
  Project.toml
  src/Oceananigans.jl
  src/logger.jl
Labels: feature

#557 Fix typos in `cell_diffusion_timescale` methods.
  src/TurbulenceClosures/turbulence_closure_diagnostics.jl
  src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl
  test/runtests.jl
  test/test_turbulence_closures.jl
Labels: bug

#550 Add default Ω_Earth and R_Earth for FPlane and BetaPlane
  src/coriolis.jl
  test/test_coriolis.jl
Labels: feature

#574 Fix and test `RoquetIdealizedNonlinearEquationOfState`
  src/Oceananigans.jl
  src/buoyancy.jl
  test/test_time_stepping.jl
Labels: Testing, bug

#575 Sometimes if you wait tests fix themselves
  test/test_solvers.jl
Labels: Testing, bug

#583 Remove `BoundaryConditions` alias
  src/boundary_conditions.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/test_boundary_conditions.jl
Labels: bug
