Repository CliMA/Oceananigans.jl, pull requests merged in 2019-07, with the labels that each got.

#309 [WIP] Integrate LES functionality
  src/Oceananigans.jl
  src/closures/anisotropic_minimum_dissipation.jl
  src/closures/closure_operators.jl
  src/closures/constant_diffusivity_closures.jl
  src/closures/constant_smagorinsky.jl
  src/closures/turbulence_closures.jl
  src/equation_of_state.jl
  src/time_steppers.jl
  test/test_turbulence_closures.jl
Labels: feature

#316 Dockerfile for Oceananigans
  Dockerfile
Labels: Testing, feature

#317 Fix calculation of Value boundary conditions
  src/boundary_conditions.jl
Labels: bug
