Repository CliMA/Oceananigans.jl, pull requests merged in 2020-09, with the labels that each got.

#711 Stop 'recomputing w' at the end of each time step
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/adams_bashforth.jl
  src/TimeSteppers/generic_time_stepping.jl
  src/TimeSteppers/time_stepping_kernels.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/runtests.jl
  test/test_pressure_solvers.jl
  test/test_regression.jl
  test/test_solvers.jl
  test/test_time_stepping.jl
Labels: numerics 🧮

#572 Lid-driven cavity verification experiment
  docs/make.jl
  docs/src/verification/lid_driven_cavity.md
  docs/src/verification/taylor_green_vortex.md
  verification/lid_driven_cavity/lid_driven_cavity.jl
  verification/lid_driven_cavity/plot_lid_driven_cavity.py
Labels: numerics 🧮, science 🌊, testing 🧪

#592 WENO advection schemes and advection verification experiments
  .travis.yml
  Manifest.toml
  Project.toml
  benchmark/benchmark_advection_schemes.jl
  benchmark/benchmark_time_steppers.jl
  src/Advection/Advection.jl
  src/Advection/centered_advective_fluxes.jl
  src/Advection/centered_fourth_order.jl
  src/Advection/centered_schemes.jl
  src/Advection/momentum_advection_operators.jl
  src/Advection/tracer_advection_operators.jl
  src/Advection/upwind_biased_advective_fluxes.jl
  src/Advection/upwind_biased_third_order.jl
  src/Advection/weno_fifth_order.jl
  src/Advection/weno_nth_order.jl
  src/Advection/weno_reconstruction.jl
  src/Oceananigans.jl
  test/runtests.jl
  test/test_time_stepping.jl
  test/test_weno_reconstruction.jl
  verification/convergence_tests/ConvergenceTests/OneDimensionalCosineAdvectionDiffusion.jl
  verification/convergence_tests/ConvergenceTests/OneDimensionalGaussianAdvectionDiffusion.jl
  verification/convergence_tests/ConvergenceTests/OneDimensionalUtils.jl
  verification/convergence_tests/Manifest.toml
  verification/convergence_tests/Project.toml
  verification/convergence_tests/one_dimensional_advection_schemes.jl
  verification/convergence_tests/one_dimensional_cosine_advection_diffusion.jl
  verification/convergence_tests/one_dimensional_gaussian_advection_diffusion.jl
  verification/periodic_advection/periodic_advection.jl
  verification/stommel_gyre/plot_stommel_gyre_advection.py
  verification/stommel_gyre/stommel_gyre.jl
  verification/stommel_gyre/stommel_gyre_advection.jl
  verification/thermal_bubble/plot_thermal_bubble_advection.py
  verification/thermal_bubble/thermal_bubble.jl
Labels: abstractions 🎨, numerics 🧮, testing 🧪
