Repository CliMA/Oceananigans.jl, pull requests merged in 2020-11, with the labels that each got.

#1126 "stable" url should be the canonical for Docs
  docs/make.jl
Labels: documentation 📜

#1125 Adds Kelvin-Helmholtz instability example
  docs/make.jl
  examples/kelvin_helmholtz_instability.jl
Labels: documentation 📜, science 🌊

#1144 Some further enhancements for the KH example
  examples/kelvin_helmholtz_instability.jl
Labels: documentation 📜, science 🌊

#1147 Brings back sanity in KH example
  examples/kelvin_helmholtz_instability.jl
Labels: documentation 📜, science 🌊

#1129 Langmuir Turbulence in the Ocean has a mixed layer
  examples/langmuir_turbulence.jl
Labels: documentation 📜, science 🌊

#1128 Update convecting plankton example to more closely resemble Taylor and Ferrari (2011)
  Manifest.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/convecting_plankton.jl
Labels: documentation 📜, science 🌊

#1168 Fix erroneous double hashes in two_dimensional_turbulence.jl example
  examples/two_dimensional_turbulence.jl
Labels: bug 🐞, documentation 📜

#1184 Explicit install of deps in Examples
  examples/convecting_plankton.jl
  examples/eady_turbulence.jl
  examples/internal_wave.jl
  examples/kelvin_helmholtz_instability.jl
  examples/langmuir_turbulence.jl
  examples/ocean_wind_mixing_and_convection.jl
  examples/one_dimensional_diffusion.jl
  examples/two_dimensional_turbulence.jl
Labels: documentation 📜, user interface/experience 💻

#1187 Slight terminology upgrade in eady example
  examples/eady_turbulence.jl
Labels: documentation 📜

#1199 Teach wizard about minimum time step
  src/Simulations/time_step_wizard.jl
  test/test_simulations.jl
Labels: simulation 🎮, user interface/experience 💻
