Repository CliMA/Oceananigans.jl, pull requests merged in 2021-11, with the labels that each got.

#2030 Fixes grid equality for GPUs
  Project.toml
  src/Grids/Grids.jl
  test/test_grids.jl
Labels: bug 🐞, GPU 👾

#2029 Updates simulation tips
  docs/src/simulation_tips.md
Labels: documentation 📜

#2031 Regression test for Hydrostatic free surface model
  Manifest.toml
  test/regression_tests/hydrostatic_free_turbulence_regression_test.jl
  test/test_regression.jl
  test/utils_for_runtests.jl
Labels: testing 🧪

#2036 Complete implementation of `HydrostaticFreeSurfaceModel` regression test
  test/data_dependencies.jl
  test/regression_tests/data/ocean_large_eddy_simulation_AnisotropicMinimumDissipation_iteration10000.jld2
  test/regression_tests/data/ocean_large_eddy_simulation_AnisotropicMinimumDissipation_iteration10010.jld2
  test/regression_tests/data/ocean_large_eddy_simulation_SmagorinskyLilly_iteration10000.jld2
  test/regression_tests/data/ocean_large_eddy_simulation_SmagorinskyLilly_iteration10010.jld2
  test/regression_tests/data/rayleigh_benard_iteration1000.jld2
  test/regression_tests/data/rayleigh_benard_iteration1100.jld2
  test/regression_tests/data/thermal_bubble_regression.nc
  test/regression_tests/hydrostatic_free_turbulence_regression_test.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/test_regression.jl
  test/utils_for_runtests.jl
Labels: cleanup 🧹

#2035 Halo optimization and solving the race condition on corner nodes
  benchmark/benchmark_two_dimensional_models.jl
  src/BoundaryConditions/fill_halo_regions.jl
  src/BoundaryConditions/fill_halo_regions_flux.jl
  src/BoundaryConditions/fill_halo_regions_nothing.jl
  src/BoundaryConditions/fill_halo_regions_open.jl
  src/BoundaryConditions/fill_halo_regions_periodic.jl
  src/BoundaryConditions/fill_halo_regions_value_gradient.jl
  src/Utils/kernel_launching.jl
  test/data_dependencies.jl
  test/test_regression.jl
Labels: bug 🐞, boundary conditions 🏓

#2057 Minor enhancement to ocean mixing example
  examples/ocean_wind_mixing_and_convection.jl
  src/BuoyancyModels/BuoyancyModels.jl
Labels: documentation 📜

#2056 Add `ConvectiveAdjustmentVerticalDiffusivity` in Docs
  docs/oceananigans.bib
  docs/src/appendix/library.md
  docs/src/model_setup/turbulent_diffusivity_closures_and_les_models.md
  docs/src/physics/turbulence_closures.md
  src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl
Labels: documentation 📜, turbulence closures 🎐

#2070 Remove GLMakie from `docs/Project.toml`
  docs/Manifest.toml
  docs/Project.toml
Labels: package 📦

#2066 Add `regrid!` in Docs
  docs/src/appendix/library.md
  src/Fields/Fields.jl
  src/Fields/regridding_fields.jl
  src/Oceananigans.jl
Labels: documentation 📜

#2069 Update `Oceananigans.CubedSpheres` to correctly import `error_if_nan_in_field`
  src/CubedSpheres/CubedSpheres.jl
Labels: bug 🐞

#2071 Fix `NaNChecker` for cubed sphere
  src/CubedSpheres/CubedSpheres.jl
  src/Simulations/nan_checker.jl
Labels: bug 🐞

#2076 Fix `SeawaterBuoyancy` docstring
  src/BuoyancyModels/seawater_buoyancy.jl
Labels: documentation 📜

#2075 Use Julia v1.6.4 in CI
  .buildkite/pipeline.yml
  .buildkite/validation-pipeline.yml
  Dockerfile
Labels: testing 🧪, package 📦

#2060 Stretched WENO and general improvement of WENO infrastructure
  Project.toml
  src/Advection/Advection.jl
  src/Advection/weno_fifth_order.jl
  src/Grids/grid_generation.jl
  src/Grids/grid_utils.jl
  src/Grids/rectilinear_grid.jl
  validation/advection/plot_rates_convergence_advection.jl
  validation/advection/validate_weno_scheme.jl
Labels: numerics 🧮

#2081 Better `show(io, ::AbstractGrid)`
  docs/src/model_setup/grids.md
  src/Grids/latitude_longitude_grid.jl
  src/Grids/rectilinear_grid.jl
Labels: grids 🗺️, user interface/experience 💻

#2082 Enhance docstrings + add models & modules in Docs/Appendix/Library
  docs/src/appendix/library.md
  src/Advection/centered_fourth_order.jl
  src/Advection/centered_second_order.jl
  src/Advection/upwind_biased_fifth_order.jl
  src/Advection/upwind_biased_first_order.jl
  src/Advection/upwind_biased_third_order.jl
  src/Advection/weno_fifth_order.jl
  src/BoundaryConditions/boundary_condition_classifications.jl
  src/BoundaryConditions/field_boundary_conditions.jl
  src/Fields/computed_field.jl
  src/Forcings/continuous_forcing.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_volume_flux.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_w_from_continuity.jl
  src/Models/HydrostaticFreeSurfaceModels/fft_based_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Models/ShallowWaterModels/ShallowWaterModels.jl
  src/Models/ShallowWaterModels/shallow_water_model.jl
  src/Oceananigans.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  src/OutputWriters/jld2_output_writer.jl
  src/Simulations/run.jl
  src/StokesDrift.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl
Labels: documentation 📜

#2079 small bug fix in Distributed Poisson Solver
  src/Distributed/distributed_fft_based_poisson_solver.jl
  test/test_distributed_poisson_solvers.jl
Labels: bug 🐞, distributed 🕸️

#2083 Fix WENO5 doctest
  src/Advection/weno_fifth_order.jl
Labels: bug 🐞, documentation 📜

#2085 More docstrings
  src/AbstractOperations/AbstractOperations.jl
  src/AbstractOperations/binary_operations.jl
  src/AbstractOperations/derivatives.jl
  src/AbstractOperations/multiary_operations.jl
  src/AbstractOperations/unary_operations.jl
  src/BuoyancyModels/buoyancy_field.jl
  src/Fields/function_field.jl
  src/Fields/reduced_field.jl
  src/TimeSteppers/clock.jl
  src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_biharmonic_diffusivity.jl
Labels: documentation 📜

#1989 Changes default buoyancy model and tracers for nonhydrostatic model
  docs/src/model_setup/boundary_conditions.md
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  docs/src/model_setup/forcing_functions.md
  docs/src/model_setup/lagrangian_particles.md
  docs/src/model_setup/output_writers.md
  docs/src/model_setup/setting_initial_conditions.md
  docs/src/model_setup/tracers.md
  examples/one_dimensional_diffusion.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/test_abstract_operations.jl
  test/test_boundary_conditions_integration.jl
  test/test_checkpointer.jl
  test/test_computed_field.jl
  test/test_dynamics.jl
  test/test_forcings.jl
  test/test_jld2_output_writer.jl
  test/test_netcdf_output_writer.jl
  test/test_nonhydrostatic_models.jl
  test/test_output_readers.jl
  test/test_output_writers.jl
  test/test_time_stepping.jl
  validation/stratified_couette_flow/stratified_couette_flow.jl
Labels: user interface/experience 💻

#2084 Stores `run_wall_time` in seconds and fixes bug
  Project.toml
  src/Simulations/run.jl
Labels: bug 🐞
