Repository CliMA/Oceananigans.jl, pull requests merged in 2021-07, with the labels that each got.

#1789 Improves phrasing in `RegularRectilinearGrid` docstring
  src/Grids/regular_rectilinear_grid.jl
Labels: documentation 📜

#1807 Create copies of AveragedTimeInterval for each output
  Project.toml
  src/OutputWriters/time_average_outputs.jl
  src/OutputWriters/windowed_time_average.jl
  test/test_netcdf_output_writer.jl
Labels: bug 🐞, testing 🧪

#1811 Updates `validation/periodic_advection.jl`
  validation/periodic_advection/periodic_advection.jl
Labels: bug 🐞

#1812 Fix various docstrings
  src/AbstractOperations/binary_operations.jl
  src/AbstractOperations/multiary_operations.jl
  src/BoundaryConditions/boundary_condition.jl
  src/BuoyancyModels/buoyancy_field.jl
  src/Coriolis/beta_plane.jl
  src/Coriolis/f_plane.jl
  src/Coriolis/hydrostatic_spherical_coriolis.jl
  src/Coriolis/non_traditional_beta_plane.jl
  src/Coriolis/non_traditional_f_plane.jl
  src/Fields/field.jl
  src/Grids/grid_utils.jl
  src/Operators/Operators.jl
  src/Operators/README
  src/Operators/README.md
  src/Operators/divergence_operators.jl
  src/Operators/laplacian_operators.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/isotropic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl
  src/TurbulenceClosures/turbulence_closure_implementations/tke_based_vertical_diffusivity.jl
Labels: documentation 📜

#1822 Update several packages
  Manifest.toml
  Project.toml
Labels: package 📦

#1810 Use constant near-surface grid spacing in ocean wind mixing and convection example + fixes some docstrings
  examples/ocean_wind_mixing_and_convection.jl
  src/Grids/regular_rectilinear_grid.jl
  src/Grids/vertically_stretched_rectilinear_grid.jl
Labels: documentation 📜

#1830 Update CUDAKernels and KernelAbstractions
  Manifest.toml
  Project.toml
Labels: GPU 👾, package 📦

#1797 Nukes Couette and Lid-driven flows, and reintroduces figures for convergence tests
  docs/make.jl
  docs/src/appendix/convergence_tests.md
  docs/src/validation/lid_driven_cavity.md
  docs/src/validation/stratified_couette_flow.md
Labels: documentation 📜

#1821 Adds grid as positional argument to WENO functions and extracts floating point type for arithmetic
  src/Advection/weno_fifth_order.jl
Labels: numerics 🧮

#1840 Cleanup of doctest files after building docs
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/contributing.md
Labels: documentation 📜, package 📦, user interface/experience 💻

#1838 Reorganized docs structure
  docs/make.jl
  docs/src/appendix/benchmarks.md
  docs/src/appendix/function_index.md
  docs/src/appendix/library.md
Labels: documentation 📜

#1839 Better momentum/tracer advection docstrings and function names
  src/Advection/Advection.jl
  src/Advection/momentum_advection_operators.jl
  src/Advection/tracer_advection_operators.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_advection.jl
  src/Models/IncompressibleModels/velocity_and_tracer_tendencies.jl
Labels: documentation 📜

#1836 Improves and fixes inconsistencies in boundary conditions docs
  docs/src/model_setup/boundary_conditions.md
Labels: documentation 📜

#1835 Allow non-zero diffusive and viscous fluxes with ImmersedBoundaryGrid
  src/Advection/centered_advective_fluxes.jl
  src/Advection/momentum_advection_operators.jl
  src/Advection/topologically_conditional_interpolation.jl
  src/Advection/upwind_biased_advective_fluxes.jl
  src/Grids/Grids.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/abstract_isotropic_diffusivity_closure.jl
  src/TurbulenceClosures/implicit_explicit_time_discretization.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/tke_based_vertical_diffusivity.jl
  test/test_dynamics.jl
  test/test_time_stepping.jl
Labels: testing 🧪

#1842 Homogenizes T, S notation in Docs/Buoyancy Models
  docs/src/physics/buoyancy_and_equations_of_state.md
Labels: documentation 📜

#1858 Fix LaTeX rendering bug in Kelvin Helmoltz instability example
  examples/kelvin_helmholtz_instability.jl
Labels: bug 🐞, documentation 📜

#1847 Adds a 2D horizontal convection example
  docs/make.jl
  docs/make_example.jl
  examples/horizontal_convection.jl
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/output_writer_utils.jl
Labels: documentation 📜

#1864 Updates `offset_indices` docstrings
  src/Grids/new_data.jl
Labels: documentation 📜

#1868 Some fixes in horizontal convection example
  examples/horizontal_convection.jl
Labels: documentation 📜

#1883 Reformulates TKEBasedVerticalDiffusivity
  src/BoundaryConditions/boundary_condition.jl
  src/BoundaryConditions/discrete_boundary_function.jl
  src/CubedSpheres/CubedSpheres.jl
  src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl
  src/TurbulenceClosures/turbulence_closure_implementations/tke_based_vertical_diffusivity.jl
Labels: parameterizations

#1888 Mask tracers for immersed boundaries
  src/ImmersedBoundaries/grid_fitted_immersed_boundary.jl
  src/Models/NonhydrostaticModels/update_nonhydrostatic_model_state.jl
  validation/immersed_boundaries/Manifest.toml
  validation/immersed_boundaries/Project.toml
  validation/immersed_boundaries/cylinder_flow_with_tracer.jl
  validation/immersed_boundaries/flow_around_cylinder.jl
Labels: immersed boundaries ⛰️

#1869 Refactors Poisson solver interfaces and new implicit free surface solver
  Project.toml
  examples/geostrophic_adjustment.jl
  src/Distributed/Distributed.jl
  src/Distributed/distributed_fft_based_poisson_solver.jl
  src/Distributed/distributed_kernel_launching.jl
  src/Distributed/distributed_solve_for_pressure.jl
  src/Distributed/multi_architectures.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/barotropic_pressure_correction.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_lateral_areas.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_volume_flux.jl
  src/Models/HydrostaticFreeSurfaceModels/explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/fft_based_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Models/NonhydrostaticModels/pressure_correction.jl
  src/Models/NonhydrostaticModels/solve_for_pressure.jl
  src/Operators/derivative_operators.jl
  src/Solvers/Solvers.jl
  src/Solvers/batched_tridiagonal_solver.jl
  src/Solvers/fft_based_poisson_solver.jl
  src/Solvers/fourier_tridiagonal_poisson_solver.jl
  src/Solvers/preconditioned_conjugate_gradient_solver.jl
  src/Solvers/solve_for_pressure.jl
  test/test_distributed_poisson_solvers.jl
  test/test_implicit_free_surface_solver.jl
  test/test_poisson_solvers.jl
  validation/implicit_free_surface/geostrophic_adjustment_test.jl
Labels: numerics 🧮

#1896 Updates Docs packages
  docs/Manifest.toml
  docs/make.jl
Labels: documentation 📜
