Repository CliMA/Oceananigans.jl, pull requests merged in 2021-09, with the labels that each got.

#1973 Bumps patch release after bug fixes via #1744
  Project.toml
Labels: package 📦

#1975 Adds clarification for `latitude` units in `Oceananigans.Coriolis`
  src/Coriolis/beta_plane.jl
  src/Coriolis/f_plane.jl
  src/Coriolis/non_traditional_beta_plane.jl
Labels: documentation 📜

#1976 Adds missing space in docs/Physics/Nonhydrostatic Model
  docs/src/physics/nonhydrostatic_model.md
Labels: documentation 📜

#1977 Fix typos + clarifying rephrase in `Oceananigans.Coriolis` docstrings
  src/Coriolis/beta_plane.jl
  src/Coriolis/constant_cartesian_coriolis.jl
  src/Coriolis/non_traditional_beta_plane.jl
Labels: documentation 📜

#1978 Create CITATION.cff file
  CITATION.cff
Labels: package 📦

#1979 Minor clearing up in Bickley jet example
  examples/shallow_water_Bickley_jet.jl
Labels: documentation 📜

#1982 Uses ValueBoundaryCondition in stratified couette flow validation test
  validation/stratified_couette_flow/stratified_couette_flow.jl
Labels: bug 🐞

#1983 Neutral boundary layers are not unstable
  Project.toml
  src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl
Labels: science 🌊

#1987 Adds vertical regridding feature
  Project.toml
  src/Fields/Fields.jl
  src/Fields/regridding_fields.jl
  src/Fields/set!.jl
  test/test_field.jl
Labels: feature 🌟

#1993 Adds docstring + example for `regrid!`
  src/Fields/regridding_fields.jl
Labels: documentation 📜

#1903 Quality of life improvements for `FieldDataset`
  Project.toml
  src/OutputReaders/field_dataset.jl
  src/OutputReaders/field_time_series.jl
  test/test_output_readers.jl
Labels: output 💾, user interface/experience 💻

#1988 Update dependencies
  .buildkite/pipeline.yml
  .buildkite/validation-pipeline.yml
  Dockerfile
  Manifest.toml
  docs/Manifest.toml
Labels: package 📦
