Repository CliMA/Oceananigans.jl, pull requests merged in 2021-04, with the labels that each got.

#1530 Switch Documenter.jl math engine to MathJax3 + Doc Fixes
  .gitignore
  docs/make.jl
  docs/oceananigans.bib
  docs/src/appendix/fractional_step.md
  docs/src/appendix/staggered_grid.md
  docs/src/model_setup/background_fields.md
  docs/src/model_setup/coriolis.md
  docs/src/model_setup/lagrangian_particles.md
  docs/src/numerical_implementation/boundary_conditions.md
  docs/src/numerical_implementation/finite_volume.md
  docs/src/numerical_implementation/large_eddy_simulation.md
  docs/src/numerical_implementation/poisson_solvers.md
  docs/src/numerical_implementation/pressure_decomposition.md
  docs/src/numerical_implementation/spatial_operators.md
  docs/src/numerical_implementation/time_stepping.md
  docs/src/numerical_implementation/turbulence_closures.md
  docs/src/physics/boundary_conditions.md
  docs/src/physics/buoyancy_and_equations_of_state.md
  docs/src/physics/coriolis_forces.md
  docs/src/physics/navier_stokes_and_tracer_conservation.md
  docs/src/physics/surface_gravity_waves.md
  docs/src/physics/turbulence_closures.md
  docs/src/validation/convergence_tests.md
  examples/convecting_plankton.jl
  examples/eady_turbulence.jl
  examples/shallow_water_Bickley_jet.jl
Labels: documentation 📜

#1543 Includes simulation tips section in the docs
  docs/make.jl
  docs/src/simulation_tips.md
Labels: documentation 📜

#1592 Fix typo in coriolis_forces.md
  docs/oceananigans.bib
  docs/src/physics/coriolis_forces.md
Labels: documentation 📜

#1531 Curvilinear anisotropic biharmonic diffusion
  src/Operators/Operators.jl
  src/Operators/derivative_operators.jl
  src/Operators/laplacian_operators.jl
  src/Operators/products_between_fields_and_grid_metrics.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/diffusion_operators.jl
  src/TurbulenceClosures/turbulence_closure_diagnostics.jl
  src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_diffusivity.jl
  src/TurbulenceClosures/viscous_dissipation_operators.jl
  test/runtests.jl
  test/test_poisson_solvers.jl
Labels: feature 🌟

#1595 Defines many identity's to avoid recursion when compiling AbstractOperations
  src/AbstractOperations/show_abstract_operations.jl
  src/Fields/reduced_field.jl
  src/Operators/interpolation_utils.jl
  test/test_abstract_operations_computed_field.jl
  test/test_implicit_free_surface_solver.jl
Labels: bug 🐞

#1598 Update docs/publications
  docs/src/publications.md
Labels: documentation 📜

#1596 Broadcasting for AbstractField, AbstractReducedField, and AbstractOperations
  .buildkite/pipeline.yml
  Project.toml
  examples/kelvin_helmholtz_instability.jl
  src/AbstractOperations/AbstractOperations.jl
  src/AbstractOperations/at.jl
  src/AbstractOperations/averages_of_operations.jl
  src/AbstractOperations/binary_operations.jl
  src/AbstractOperations/broadcasting_abstract_operations.jl
  src/AbstractOperations/derivatives.jl
  src/AbstractOperations/multiary_operations.jl
  src/AbstractOperations/unary_operations.jl
  src/BoundaryConditions/fill_halo_regions.jl
  src/BuoyancyModels/buoyancy_field.jl
  src/Distributed/distributed_fields.jl
  src/Distributed/halo_communication.jl
  src/Fields/Fields.jl
  src/Fields/abstract_field.jl
  src/Fields/averaged_field.jl
  src/Fields/broadcasting_abstract_fields.jl
  src/Fields/computed_field.jl
  src/Fields/field.jl
  src/Fields/function_field.jl
  src/Fields/kernel_computed_field.jl
  src/Fields/reduced_field.jl
  src/Fields/show_fields.jl
  src/Fields/zero_field.jl
  src/Solvers/preconditioned_conjugate_gradient_solver.jl
  src/Utils/tuple_utils.jl
  test/runtests.jl
  test/test_abstract_operations_computed_field.jl
  test/test_averaged_field.jl
  test/test_broadcasting.jl
  test/test_cubed_sphere_halo_exchange.jl
  test/test_distributed_poisson_solvers.jl
  test/test_field.jl
  test/test_halo_regions.jl
  test/test_implicit_free_surface_solver.jl
  test/test_kernel_computed_field.jl
  test/test_poisson_solvers.jl
Labels: feature 🌟

#1616 Fix for schematic not showing in Docs/Appandix/Staggered Grid
  docs/src/appendix/staggered_grid.md
  docs/src/numerical_implementation/finite_volume.md
Labels: documentation 📜

#1617 Adds missing `\cdot` in isotropic viscosity in Docs/Numerical Implementation/Spatial Operators
  docs/src/numerical_implementation/spatial_operators.md
Labels: documentation 📜
