Repository CliMA/Oceananigans.jl, pull requests merged in 2021-08, with the labels that each got.

#1928 Add a test to check surface bc continuous functions work with ImmersedBoundary
  src/BoundaryConditions/continuous_boundary_function.jl
  src/Forcings/continuous_forcing.jl
  test/runtests.jl
  test/test_hydrostatic_free_surface_immersed_boundaries_apply_surf_bc.jl
Labels: testing 🧪

#1932 Fix bug in hydrostatic vertical velocity with stretched grid
  Project.toml
  src/Models/HydrostaticFreeSurfaceModels/compute_w_from_continuity.jl
Labels: bug 🐞, numerics 🧮

#1935 Fix diffusive flux bug for immersed boundaries
  Project.toml
  src/TurbulenceClosures/diffusion_operators.jl
  validation/immersed_boundaries/immersed_tracer_1D.jl
Labels: bug 🐞, immersed boundaries ⛰️

#1940 Deploy docs
  Project.toml
Labels: documentation 📜
