Repository CliMA/Oceananigans.jl, pull requests merged in 2021-06, with the labels that each got.

#1738 ConvectiveAdjustmentVerticalDiffusivity
  src/Oceananigans.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/turbulence_closure_diagnostics.jl
  src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/tke_based_vertical_diffusivity.jl
  test/runtests.jl
  validation/vertical_mixing_closures/convective_adjustment_free_convection.jl
  validation/vertical_mixing_closures/tke_based_free_convection.jl
  validation/vertical_mixing_closures/tke_based_wind_mixing.jl
Labels: feature 🌟

#1751 Correct min_Δz for VerticallyStretchedGrids
  src/Grids/vertically_stretched_rectilinear_grid.jl
  test/test_simulations.jl
Labels: bug 🐞

#1760 Docs: Change pressure symbol φ -> p
  docs/src/appendix/fractional_step.md
  docs/src/numerical_implementation/poisson_solvers.md
  docs/src/numerical_implementation/pressure_decomposition.md
  docs/src/numerical_implementation/time_stepping.md
Labels: documentation 📜

#1746 Plots and fixes for benchmarks
  benchmark/Manifest.toml
  benchmark/Project.toml
  benchmark/benchmark_abstract_operations.jl
  benchmark/benchmark_advection_schemes.jl
  benchmark/benchmark_equations_of_state.jl
  benchmark/benchmark_fft_based_poisson_solvers.jl
  benchmark/benchmark_fourier_tridiagonal_poisson_solver.jl
  benchmark/benchmark_hydrostatic_model.jl
  benchmark/benchmark_incompressible_model.jl
  benchmark/benchmark_lagrangian_particle_tracking.jl
  benchmark/benchmark_multithreading.jl
  benchmark/benchmark_multithreading_single.jl
  benchmark/benchmark_regression.jl
  benchmark/benchmark_shallow_water_model.jl
  benchmark/benchmark_time_steppers.jl
  benchmark/benchmark_topologies.jl
  benchmark/benchmark_tracers.jl
  benchmark/benchmark_transforms.jl
  benchmark/benchmark_turbulence_closures.jl
  benchmark/benchmark_vertically_stretched_incompressible_model.jl
  benchmark/benchmarkable_incompressible_model.jl
  benchmark/src/Benchmarks.jl
  benchmark/strong_scaling_incompressible_model.jl
  benchmark/strong_scaling_incompressible_model_single.jl
  benchmark/strong_scaling_shallow_water_model.jl
  benchmark/strong_scaling_shallow_water_model_single.jl
  benchmark/weak_scaling_shallow_water_model.jl
  benchmark/weak_scaling_shallow_water_model_single.jl
Labels: performance 🏍️

#1774 Include Flat topologies when talking about the grids in the docs
  docs/src/model_setup/grids.md
Labels: documentation 📜

#1776 Docs: Physics + Numerics before Model description
  docs/make.jl
Labels: documentation 📜

#1772 Updates building docs instructions
  docs/src/contributing.md
Labels: documentation 📜

#1773 Move Publications section to index.md
  docs/make.jl
  docs/src/index.md
  docs/src/publications.md
Labels: documentation 📜

#1770 Exponentiate with Int32 not Int64
  Project.toml
  src/Advection/weno_fifth_order.jl
Labels: bug 🐞, numerics 🧮, 🚨 high priority 🚨
