Repository CliMA/Oceananigans.jl, pull requests merged in 2021-03, with the labels that each got.

#1425 Typo in Contributors guide
  CONTRIBUTING.md
  docs/src/contributing.md
Labels: documentation 📜

#590 MPI distributed parallelism
  .buildkite/pipeline.yml
  Manifest.toml
  Project.toml
  benchmark/Manifest.toml
  benchmark/Project.toml
  benchmark/strong_scaling_incompressible_model.jl
  benchmark/strong_scaling_incompressible_model_single.jl
  src/Architectures.jl
  src/Distributed/Distributed.jl
  src/Distributed/distributed_fft_based_poisson_solver.jl
  src/Distributed/distributed_fields.jl
  src/Distributed/distributed_incompressible_model.jl
  src/Distributed/distributed_solve_for_pressure.jl
  src/Distributed/distributed_utils.jl
  src/Distributed/halo_communication.jl
  src/Distributed/halo_communication_bcs.jl
  src/Distributed/multi_architectures.jl
  src/Fields/field.jl
  src/Fields/new_data.jl
  src/Models/IncompressibleModels/show_incompressible_model.jl
  src/Oceananigans.jl
  src/Simulations/simulation.jl
  test/runtests.jl
  test/test_distributed_models.jl
  test/test_distributed_poisson_solvers.jl
Labels: abstractions 🎨, feature 🌟

#1418 Implicit free-surface code for discussion and then merging....
  docs/src/numerical_implementation/poisson_solvers.md
  src/Fields/reduced_field.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/barotropic_pressure_correction.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface_solver_kernels.jl
  src/Solvers/preconditioned_conjugate_gradient_solver.jl
  test/runtests.jl
  test/test_implicit_free_surface_solver.jl
  test/test_preconditioned_conjugate_gradient_solver.jl
Labels: feature 🌟

#1305 Shallow Water Model Bickley Jet Example
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/make_example.jl
  examples/Bickley_jet_shallow_water.jl
  examples/eady_turbulence.jl
Labels: documentation 📜

#1463 Buildkite with Julia v1.5.4
  .buildkite/pipeline.yml
Labels: testing 🧪

#1464 Some clarifications + fix typos in Bickley example
  docs/Project.toml
  examples/Bickley_jet_shallow_water.jl
Labels: documentation 📜

#1476 Changing the name to shallow water Bickley jet
  docs/make.jl
  docs/make_example.jl
  examples/shallow_water_Bickley_jet.jl
Labels: documentation 📜, models 🧫

#1495 Make Bickley example work on GPU
  examples/shallow_water_Bickley_jet.jl
Labels: GPU 👾, documentation 📜

#870 Benchmark abstract operations
  benchmark/Manifest.toml
  benchmark/Project.toml
  benchmark/benchmark_abstract_operations.jl
Labels: help wanted 🦮
