Repository CliMA/Oceananigans.jl, pull requests merged in 2021-05, with the labels that each got.

#1626 Barotropic turbulence validation tests on RegularLatitudeLongitudeGrid
  src/AbstractOperations/derivatives.jl
  src/Fields/computed_field.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/Models/IncompressibleModels/IncompressibleModels.jl
  src/Models/ShallowWaterModels/ShallowWaterModels.jl
  src/Oceananigans.jl
  src/Operators/products_between_fields_and_grid_metrics.jl
  src/Simulations/Simulations.jl
  src/Simulations/time_step_wizard.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/quasi_adams_bashforth_2.jl
  src/TimeSteppers/runge_kutta_3.jl
  src/TimeSteppers/store_tendencies.jl
  src/TurbulenceClosures/diffusion_operators.jl
  src/TurbulenceClosures/viscous_dissipation_operators.jl
  validation/lat_lon_barotropic_turbulence/freely_decaying_barotropic_turbulence.jl
  validation/lat_lon_barotropic_turbulence/visualize.jl
Labels: feature 🌟, science 🌊

#1652 Adds Grids/vertically_stretched_rectilinear_grid.jl in Docs
  docs/make_example.jl
  docs/src/library.md
Labels: documentation 📜

#1654 Basic `ImmersedBoundaryGrid` + `GridFittedBoundary` implementation
  src/Advection/centered_advective_fluxes.jl
  src/Advection/centered_second_order.jl
  src/Advection/momentum_advection_operators.jl
  src/Advection/upwind_biased_advective_fluxes.jl
  src/Grids/Grids.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/grid_fitted_immersed_boundary.jl
  src/ImmersedBoundaries/immersed_grid_metrics.jl
  src/ImmersedBoundaries/mask_immersed_field.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/Models/IncompressibleModels/velocity_and_tracer_tendencies.jl
  src/Models/Models.jl
  src/Models/ShallowWaterModels/solution_and_tracer_tendencies.jl
  src/Oceananigans.jl
  src/TimeSteppers/runge_kutta_3.jl
  src/TurbulenceClosures/abstract_isotropic_diffusivity_closure.jl
  src/TurbulenceClosures/closure_tuples.jl
  src/TurbulenceClosures/diffusion_operators.jl
  src/TurbulenceClosures/implicit_explicit_time_discretization.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/horizontally_curvilinear_anisotropic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/nothing_closure.jl
  src/TurbulenceClosures/turbulence_closure_utils.jl
  src/TurbulenceClosures/viscous_dissipation_operators.jl
  test/runtests.jl
  test/test_hydrostatic_free_surface_immersed_boundaries.jl
  test/test_turbulence_closures.jl
  validation/immersed_boundaries/immersed_hydrostatic_diffusion.jl
  validation/immersed_boundaries/internal_tide.jl
Labels: feature 🌟, immersed boundaries ⛰️, numerics 🧮

#1514 Upgrade to Julia 1.6
  .buildkite/pipeline.yml
  .buildkite/validation-pipeline.yml
  .github/workflows/CompatHelper.yml
  Dockerfile
  Manifest.toml
  Project.toml
  README.md
  benchmark/Manifest.toml
  docs/Manifest.toml
  docs/src/installation_instructions.md
  docs/src/model_setup/background_fields.md
  docs/src/model_setup/boundary_conditions.md
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  docs/src/model_setup/checkpointing.md
  docs/src/model_setup/forcing_functions.md
  docs/src/model_setup/lagrangian_particles.md
  docs/src/model_setup/tracers.md
  src/Architectures.jl
  src/Diagnostics/cfl.jl
  src/Fields/field.jl
  src/Fields/set!.jl
  src/Forcings/forcing.jl
  src/Forcings/relaxation.jl
  src/Grids/Grids.jl
  src/Grids/grid_utils.jl
  src/Grids/vertically_stretched_rectilinear_grid.jl
  src/Models/IncompressibleModels/show_incompressible_model.jl
  src/Oceananigans.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/Solvers/fourier_tridiagonal_poisson_solver.jl
  src/TurbulenceClosures/turbulence_closure_utils.jl
  src/Utils/cell_advection_timescale.jl
  test/data_dependencies.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/test_cubed_sphere_circulation.jl
  test/test_cubed_sphere_halo_exchange.jl
  test/test_diagnostics.jl
  test/test_field.jl
  test/test_grids.jl
  test/test_jld2_output_writer.jl
  test/test_lagrangian_particle_tracking.jl
  test/test_netcdf_output_writer.jl
  test/test_output_readers.jl
  test/test_reduced_field.jl
  test/test_time_stepping.jl
  validation/convergence_tests/Manifest.toml
Labels: package 📦

#1675 Replaces a leftover Julia 1.5 -> 1.6
  docs/src/using_gpus.md
Labels: documentation 📜

#1665 Update spherical_splash.jl
  examples/spherical_splash.jl
Labels: bug 🐞

#1690 Update Physics Docs for the various Models
  docs/make.jl
  docs/src/appendix/fractional_step.md
  docs/src/appendix/staggered_grid.md
  docs/src/model_setup/background_fields.md
  docs/src/numerical_implementation/boundary_conditions.md
  docs/src/numerical_implementation/large_eddy_simulation.md
  docs/src/numerical_implementation/poisson_solvers.md
  docs/src/numerical_implementation/spatial_operators.md
  docs/src/numerical_implementation/time_stepping.md
  docs/src/numerical_implementation/turbulence_closures.md
  docs/src/physics/boundary_conditions.md
  docs/src/physics/boussinesq.md
  docs/src/physics/coriolis_forces.md
  docs/src/physics/hydrostatic_free_surface_model.md
  docs/src/physics/incompressible_model.md
  docs/src/physics/navier_stokes_and_tracer_conservation.md
  docs/src/physics/notation.md
  docs/src/physics/shallow_water_model.md
  docs/src/physics/surface_gravity_waves.md
  docs/src/physics/turbulence_closures.md
  docs/src/validation/convergence_tests.md
  examples/convecting_plankton.jl
  examples/eady_turbulence.jl
Labels: documentation 📜

#1715 Docs/Physics: Shallow Water Dynamics -> Shallow Water Model
  docs/make.jl
Labels: documentation 📜

#1677 Updates packages used for building the Docs
  docs/Manifest.toml
  docs/oceananigans.bib
Labels: documentation 📜

#1707 Update instructions for building docs
  docs/src/contributing.md
Labels: documentation 📜

#1721 Docs/Bibliography patch
  docs/oceananigans.bib
Labels: documentation 📜

#1729 Fixes typo in Docs/Physics/HydrostaticFreeSurfaceModel
  docs/src/physics/hydrostatic_free_surface_model.md
Labels: bug 🐞, documentation 📜
