Repository CliMA/Oceananigans.jl, pull requests merged in 2022-11, with the labels that each got.

#2804 Fix docstring/doctest for `required_halo_size`
  src/Grids/automatic_halo_sizing.jl
Labels: testing 🧪

#2786 CATKE and GM in a near-global 1 degree simulation + updates Ri-based vertical diffusivity
  Manifest.toml
  Project.toml
  src/AbstractOperations/AbstractOperations.jl
  src/AbstractOperations/unary_operations.jl
  src/Advection/momentum_advection_operators.jl
  src/Advection/tracer_advection_operators.jl
  src/Advection/vector_invariant_advection.jl
  src/Architectures.jl
  src/BoundaryConditions/boundary_condition.jl
  src/BoundaryConditions/fill_halo_regions.jl
  src/BuoyancyModels/buoyancy_field.jl
  src/Coriolis/beta_plane.jl
  src/Coriolis/constant_cartesian_coriolis.jl
  src/Coriolis/f_plane.jl
  src/Coriolis/hydrostatic_spherical_coriolis.jl
  src/Fields/set!.jl
  src/Fields/show_fields.jl
  src/Forcings/multiple_forcings.jl
  src/ImmersedBoundaries/conditional_derivatives.jl
  src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/rigid_lid.jl
  src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
  src/Models/HydrostaticFreeSurfaceModels/slice_ensemble_model_mode.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl
  src/Models/NonhydrostaticModels/update_nonhydrostatic_model_state.jl
  src/Models/ShallowWaterModels/update_shallow_water_state.jl
  src/MultiRegion/unified_heptadiagonal_iterative_solver.jl
  src/Oceananigans.jl
  src/OutputReaders/field_time_series.jl
  src/OutputWriters/OutputWriters.jl
  src/OutputWriters/windowed_time_average.jl
  src/Simulations/callback.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/abstract_scalar_biharmonic_diffusivity_closure.jl
  src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
  src/TurbulenceClosures/closure_kernel_operators.jl
  src/TurbulenceClosures/closure_tuples.jl
  src/TurbulenceClosures/implicit_explicit_time_discretization.jl
  src/TurbulenceClosures/isopycnal_rotation_tensor_components.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/mixing_length.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/surface_TKE_flux.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/turbulent_kinetic_energy_equation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/ri_based_vertical_diffusivity.jl
  src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl
  src/Utils/multi_region_transformation.jl
  src/Utils/schedules.jl
  test/test_dynamics.jl
  test/test_ensemble_hydrostatic_free_surface_models.jl
  test/test_hydrostatic_free_surface_immersed_boundaries.jl
  test/test_nonhydrostatic_models.jl
  test/test_vertical_vorticity_field.jl
  validation/vertical_mixing_closures/windy_catke_convection.jl
  validation/vertical_mixing_closures/windy_convection.jl
Labels: bug 🐞, science 🌊, turbulence closures 🎐

#2816 Fix wrong looping over indices of OffsetArray
  src/Grids/conformal_cubed_sphere_face_grid.jl
Labels: bug 🐞

#2808 Better docstrings for sparse utility functions in `Solvers`
  Manifest.toml
  src/Solvers/sparse_approximate_inverse.jl
  src/Solvers/sparse_preconditioners.jl
Labels: documentation 📜

#2819 Simplify the baroclinic adjustment example
  examples/baroclinic_adjustment.jl
Labels: documentation 📜

#2821 Fix race condition affecting `HydrostaticFreeSurfaceModel` with `isnothing(free_surface)`
  Project.toml
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/MultiRegion/multi_region_utils.jl
Labels: bug 🐞

#2824 Fixes bug in error for `validate_index`
  src/Grids/input_validation.jl
Labels: bug 🐞

#2826 Speed up matrix Poisson solver test + minor code cleanup
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  test/test_matrix_poisson_solver.jl
Labels: cleanup 🧹, testing 🧪

#2825 Use AMGX v0.1.3 + drop `@ifhasamgx`
  Manifest.toml
  Project.toml
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/matrix_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/mg_implicit_free_surface_solver.jl
  src/Oceananigans.jl
  src/Solvers/Solvers.jl
  src/Solvers/heptadiagonal_iterative_solver.jl
  src/Solvers/multigrid_solver.jl
  src/Solvers/sparse_preconditioners.jl
Labels: package 📦
