Repository CliMA/Oceananigans.jl, pull requests merged in 2022-01, with the labels that each got.

#2150 Bug fix in stretched grid!
  src/Grids/grid_generation.jl
  test/test_grids.jl
Labels: bug 🐞, grids 🗺️

#2128 Removes `architecture` from `ShallowWaterModel` docstring
  src/Models/ShallowWaterModels/shallow_water_model.jl
Labels: documentation 📜

#2137 Fix return statement in `test_matrix_poisson_solver.jl`
  test/test_matrix_poisson_solver.jl
Labels: cleanup 🧹

#2138 Use julia 1.6.5
  .buildkite/pipeline.yml
  .buildkite/validation-pipeline.yml
  Dockerfile
Labels: package 📦

#2132 Fix compat annotation in Docs
  docs/src/installation_instructions.md
Labels: documentation 📜

#2151 Split tests into smaller bits and pieces (take #2)
  .buildkite/pipeline.yml
  test/runtests.jl
  test/test_hydrostatic_regression.jl
  test/test_nonhydrostatic_regression.jl
Labels: GPU 👾, testing 🧪

#2147 Bugfix in `reset!(sim)` for AB2 timesteppers
  Project.toml
  src/Simulations/run.jl
  src/Simulations/simulation.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/quasi_adams_bashforth_2.jl
Labels: bug 🐞

#2141 Adds a correct simplified Inverse preconditioner
  benchmark/benchmark_hydrostatic_model.jl
  benchmark/benchmark_spai_preconditioner.jl
  src/Grids/latitude_longitude_grid.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_lateral_areas.jl
  src/Models/HydrostaticFreeSurfaceModels/matrix_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
  src/Solvers/Solvers.jl
  src/Solvers/heptadiagonal_iterative_solver.jl
  src/Solvers/preconditioned_conjugate_gradient_solver.jl
  src/Solvers/sparse_approximate_inverse.jl
  src/Solvers/sparse_preconditioners.jl
  test/data_dependencies.jl
  test/test_hydrostatic_free_surface_immersed_boundaries.jl
  test/test_hydrostatic_free_surface_immersed_boundaries_congrad_solve.jl
  test/test_hydrostatic_free_surface_immersed_boundaries_vertical_integrals.jl
  test/test_hydrostatic_free_surface_models.jl
  test/test_implicit_free_surface_solver.jl
  test/test_matrix_poisson_solver.jl
  validation/implicit_free_surface/geostrophic_adjustment_test.jl
  validation/near_global_lat_lon/annual_cycle_earth_bathymetry.jl
Labels: numerics 🧮

#2100 Implements a `ConsecutiveIterations` schedule
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/OutputWriters/windowed_time_average.jl
  src/Utils/schedules.jl
Labels: user interface/experience 💻

#2152 Small fix for single column model mode
  Project.toml
  src/Grids/conformal_cubed_sphere_face_grid.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/rectilinear_grid.jl
  src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
Labels: bug 🐞

#2160 Resolves conflict between `CUDA.device` and `Oceananigans.Architectures.device`
  src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
Labels: bug 🐞

#2157 More support for broadcasting to reduced fields
  src/Fields/broadcasting_abstract_fields.jl
  test/test_broadcasting.jl
Labels: performance 🏍️, testing 🧪

#2168 Update examples in `README`
  README.md
Labels: documentation 📜

#2163 Validate boundary conditions on Fields
  .buildkite/pipeline.yml
  src/BoundaryConditions/BoundaryConditions.jl
  src/BoundaryConditions/boundary_condition.jl
  src/BoundaryConditions/field_boundary_conditions.jl
  src/BoundaryConditions/fill_halo_regions_nothing.jl
  src/CubedSpheres/CubedSpheres.jl
  src/Fields/field.jl
  test/test_field.jl
Labels: user interface/experience 💻

#2173 Fixes bug inferring regular dimensions for Average
  Project.toml
  src/AbstractOperations/grid_metrics.jl
  src/AbstractOperations/metric_field_reductions.jl
  test/test_computed_field.jl
  test/test_field_reductions.jl
Labels: bug 🐞

#2175 Update packages
  Manifest.toml
  benchmark/Manifest.toml
  docs/Manifest.toml
Labels: package 📦

#2097 Fixes for implicit vertical diffusion with immersed boundaries
  Project.toml
  src/AbstractOperations/AbstractOperations.jl
  src/AbstractOperations/conditional_operations.jl
  src/AbstractOperations/grid_metrics.jl
  src/AbstractOperations/metric_field_reductions.jl
  src/AbstractOperations/show_abstract_operations.jl
  src/Advection/weno_fifth_order.jl
  src/Fields/abstract_field.jl
  src/Fields/field.jl
  src/Fields/field_reductions.jl
  src/Fields/interpolate.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/rectilinear_grid.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/conditional_fluxes.jl
  src/ImmersedBoundaries/grid_fitted_immersed_boundaries.jl
  src/ImmersedBoundaries/immersed_fields_reductions.jl
  src/ImmersedBoundaries/immersed_grid_metrics.jl
  src/ImmersedBoundaries/mask_immersed_field.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_lateral_areas.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_variables.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_volume_flux.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_advection.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/matrix_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Operators/Operators.jl
  src/Operators/derivative_operators.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  src/Solvers/batched_tridiagonal_solver.jl
  src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl
  src/TurbulenceClosures/velocity_tracer_gradients.jl
  src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl
  src/TurbulenceClosures/viscous_dissipation_operators.jl
  test/data_dependencies.jl
  test/regression_tests/hydrostatic_free_turbulence_regression_test.jl
  test/runtests.jl
  test/test_conditional_reductions.jl
  test/test_dynamics.jl
  test/test_field_reductions.jl
  test/test_hydrostatic_free_surface_immersed_boundaries.jl
  test/test_hydrostatic_free_surface_immersed_boundaries_vertical_integrals.jl
  test/utils_for_runtests.jl
  validation/immersed_boundaries/immersed_hydrostatic_diffusion.jl
  validation/immersed_boundaries/internal_tide.jl
  validation/near_global_lat_lon/annual_cycle_earth_bathymetry.jl
  validation/near_global_lat_lon/annual_cycle_earth_bathymetry_fine.jl
  validation/near_global_lat_lon/constant_forcing_earth_bathymetry.jl
  validation/near_global_lat_lon/cyclic_interpolate_utils.jl
Labels: bug 🐞, numerics 🧮

#2013 [WIP] Adds Split-Explicit to HydrostaticFreeSurfaceModel
  src/Coriolis/beta_plane.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/barotropic_pressure_correction.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  src/Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
  src/Models/Models.jl
  src/Oceananigans.jl
  test/runtests.jl
  test/test_split_explicit_free_surface_solver.jl
  test/test_split_explicit_vertical_integrals.jl
  validation/implicit_free_surface/geostrophic_adjustment_test.jl
  validation/mesoscale_turbulence/abernathey_channel.jl
Labels: feature 🌟, performance 🏍️, numerics 🧮, 🚨 high priority 🚨

#2181 Cleanup in the implicit free surface tests + add `matrix_implicit_free_surface_solver_tests`
  test/runtests.jl
  test/test_hydrostatic_free_surface_immersed_boundaries_implicit_solve.jl
  test/test_implicit_free_surface_solver.jl
Labels: testing 🧪

#2187 Split poisson solver tests
  .buildkite/pipeline.yml
  test/dependencies_for_poisson_solvers.jl
  test/runtests.jl
  test/test_poisson_solvers.jl
  test/test_poisson_solvers_vertically_stretched_grid.jl
Labels: GPU 👾, testing 🧪

#2195 Update docs/docstrings
  docs/src/model_setup/background_fields.md
  src/BoundaryConditions/discrete_boundary_function.jl
  src/Fields/field.jl
  src/Fields/field_reductions.jl
  src/Fields/regridding_fields.jl
  src/Forcings/discrete_forcing.jl
  src/Forcings/forcing.jl
  src/Forcings/relaxation.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Models/ShallowWaterModels/shallow_water_model.jl
Labels: documentation 📜

#2196 Fixes `FreeSurface` constructor for `SingleColumnGrid` and adds a test
  Project.toml
  src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
  test/test_hydrostatic_free_surface_models.jl
Labels: bug 🐞

#2199 Show free surface method/solver for `HydrostaticFreeSurfaceModel`s
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl
Labels: user interface/experience 💻

#2190 Defines more area and volume calculations in `Operations`
  Project.toml
  src/Operators/Operators.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  test/test_abstract_operations.jl
  test/test_field_reductions.jl
Labels: feature 🌟, numerics 🧮

#2206 More fixes in docstrings
  docs/src/model_setup/output_writers.md
  src/AbstractOperations/binary_operations.jl
  src/AbstractOperations/derivatives.jl
  src/BoundaryConditions/fill_halo_regions.jl
  src/BuoyancyModels/linear_equation_of_state.jl
  src/BuoyancyModels/seawater_buoyancy.jl
  src/Fields/background_fields.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/grid_fitted_immersed_boundaries.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/Simulations/time_step_wizard.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
  src/Utils/schedules.jl
Labels: documentation 📜
