Repository CliMA/Oceananigans.jl, pull requests merged in 2022-12, with the labels that each got.

#2849 Drop compat entry for KernelAbstractions 0.8
  Project.toml
Labels: package 📦

#2847 Fix bug loading `netcdf`
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  src/Oceananigans.jl
  src/OutputWriters/OutputWriters.jl
Labels: bug 🐞, package 📦, output 💾

#2852 New vector invariant scheme
  Project.toml
  src/Advection/topologically_conditional_interpolation.jl
  src/Advection/vector_invariant_advection.jl
  src/Advection/weno_interpolants.jl
  src/Advection/weno_reconstruction.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/conditional_fluxes.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/ShallowWaterModels/shallow_water_advection_operators.jl
  src/Models/ShallowWaterModels/shallow_water_model.jl
  test/regression_tests/shallow_water_bickley_jet_regression.jl
  validation/near_global_lat_lon/near_global_quarter_degree.jl
Labels: numerics 🧮

#2853 Upgrade Makie
  Manifest.toml
  docs/Manifest.toml
  docs/Project.toml
  examples/baroclinic_adjustment.jl
  examples/horizontal_convection.jl
  examples/internal_wave.jl
  examples/kelvin_helmholtz_instability.jl
  examples/ocean_wind_mixing_and_convection.jl
  examples/shallow_water_Bickley_jet.jl
  examples/tilted_bottom_boundary_layer.jl
  examples/two_dimensional_turbulence.jl
  validation/barotropic_gyre/visualize_barotropic_gyre.jl
  validation/cubed_sphere_surface_gravity_waves/animate_face.jl
  validation/cubed_sphere_surface_gravity_waves/animate_sphere.jl
  validation/mesoscale_turbulence/baroclinic_adjustment.jl
  validation/mesoscale_turbulence/eddying_channel.jl
  validation/mesoscale_turbulence/zonally_averaged_channel.jl
  validation/near_global_lat_lon/visualize_annual_cycle_solution.jl
  validation/solid_body_rotation/solid_body_rotation.jl
  validation/solid_body_rotation/solid_body_tracer_advection.jl
Labels: package 📦

#2859 Increased `interpolate` speed
  src/Fields/interpolate.jl
Labels: performance 🏍️, GPU 👾
