Repository CliMA/Oceananigans.jl, pull requests merged in 2022-08, with the labels that each got.

#2694 Fixes doc references in Numerical Implementation/Elliptic Solvers section + `checkdocs = :exports`
  docs/make.jl
  docs/src/appendix/fractional_step.md
  docs/src/appendix/library.md
  docs/src/numerical_implementation/elliptic_solvers.md
Labels: documentation 📜

#2703 Use Julia v1.6.7 for CI
  .buildkite/pipeline.yml
  .buildkite/validation-pipeline.yml
  Dockerfile
  Manifest.toml
  docs/src/index.md
Labels: testing 🧪, package 📦

#2699 Change `'\n'` -> `"\n"`
  src/AbstractOperations/conditional_operations.jl
  src/AbstractOperations/show_abstract_operations.jl
  src/BoundaryConditions/show_boundary_conditions.jl
  src/BuoyancyModels/seawater_buoyancy.jl
  src/Fields/background_fields.jl
  src/Fields/function_field.jl
  src/Fields/show_fields.jl
  src/Forcings/advective_forcing.jl
  src/Forcings/continuous_forcing.jl
  src/Forcings/discrete_forcing.jl
  src/Forcings/multiple_forcings.jl
  src/Forcings/relaxation.jl
  src/Grids/conformal_cubed_sphere_face_grid.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/rectilinear_grid.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/immersed_boundary_condition.jl
  src/LagrangianParticleTracking/LagrangianParticleTracking.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl
  src/Models/NonhydrostaticModels/show_nonhydrostatic_model.jl
  src/MultiRegion/multi_region_field.jl
  src/MultiRegion/unified_heptadiagonal_iterative_solver.jl
  src/OutputReaders/field_time_series.jl
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/Simulations/simulation.jl
  src/Solvers/heptadiagonal_iterative_solver.jl
  src/Solvers/multigrid_solver.jl
  src/Solvers/preconditioned_conjugate_gradient_solver.jl
  src/TurbulenceClosures/closure_tuples.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
  src/Utils/ordered_dict_show.jl
  test/utils_for_runtests.jl
  validation/near_global_lat_lon/one_degree_setups/idealized_near_global_one_degree.jl
Labels: 🚲 bikeshedding

#2697 Fix bug in `validate_fft_implicit_solver_grid `
  src/Models/HydrostaticFreeSurfaceModels/fft_based_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/mg_implicit_free_surface_solver.jl
  src/Solvers/multigrid_solver.jl
  validation/implicit_free_surface/implicit_surface_solvers_benchmark.jl
Labels: bug 🐞, immersed boundaries ⛰️

#2710 Fix location of Integrated areas derivatives in the PCG solver
  Project.toml
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
Labels: bug 🐞

#2712 Add test for implicit free surface with immersed boundary
  test/test_implicit_free_surface_solver.jl
Labels: testing 🧪

#2715 Slightly reorganizes dependencies in tests
  test/dependencies_for_runtests.jl
  test/regression_tests/shallow_water_bickley_jet_regression.jl
  test/test_cubed_spheres.jl
  test/test_grids.jl
  test/test_hydrostatic_regression.jl
  test/test_netcdf_output_writer.jl
  test/test_nonhydrostatic_regression.jl
  test/test_shallow_water_regression.jl
  test/test_simulations.jl
  test/test_time_stepping.jl
Labels: testing 🧪

#2695 Update dependencies
  .buildkite/pipeline.yml
  Manifest.toml
  docs/Manifest.toml
  test/runtests.jl
  test/test_output_readers.jl
  test/test_output_writers.jl
Labels: package 📦
