Repository CliMA/Oceananigans.jl, pull requests merged in 2022-02, with the labels that each got.

#2208 Add show method for CATKE closure
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/mixing_length.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/surface_TKE_flux.jl
Labels: turbulence closures 🎐, user interface/experience 💻

#2211 Only show free surface info when there is a free surface
  src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl
Labels: bug 🐞

#2212 Saves actual `solver_method` name in `ImplicitFreeSurface` (not just `:Default`)
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Solvers/preconditioned_conjugate_gradient_solver.jl
Labels: user interface/experience 💻

#2230 Updates models' docstrings
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Models/ShallowWaterModels/shallow_water_model.jl
  src/StokesDrift.jl
Labels: documentation 📜

#2231 Adds `longform` option to `prettytime`
  Project.toml
  src/Simulations/simulation.jl
  src/Utils/Utils.jl
  src/Utils/pretty_time.jl
  src/Utils/prettytime.jl
  test/test_utils.jl
Labels: user interface/experience 💻

#2225 Fixes CATKE-in-a-tuple implementation and adds tests
  Project.toml
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/slice_ensemble_model_mode.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/closure_tuples.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/surface_TKE_flux.jl
  test/test_ensemble_hydrostatic_free_surface_models.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
Labels: bug 🐞, user interface/experience 💻

#2243 Deploy docs with `forcepush = true`
  docs/make.jl
Labels: documentation 📜, package 📦

#2232 Subtle reformulation of `CATKEVerticalDiffusivity`
  Project.toml
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/mixing_length.jl
Labels: turbulence closures 🎐

#2257 Ensemble of Isopycnal Tracer Diffusion closures on the GPU
  Project.toml
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
Labels: GPU 👾, turbulence closures 🎐

#2262 Adds a sentence to the Anisotropic diffusivity section of the docs
  docs/src/model_setup/turbulent_diffusivity_closures_and_les_models.md
Labels: documentation 📜

#2260 Fix bug in `QuasiAdamsBashforth2TimeStepper`
  Project.toml
  docs/src/numerical_implementation/time_stepping.md
  src/CubedSpheres/cubed_sphere_faces.jl
  src/TimeSteppers/quasi_adams_bashforth_2.jl
  src/TimeSteppers/runge_kutta_3.jl
  test/test_time_stepping.jl
Labels: bug 🐞, numerics 🧮

#2280 Fix missing tracer equation reference in Docs
  docs/src/numerical_implementation/boundary_conditions.md
Labels: documentation 📜
