Repository CliMA/Oceananigans.jl, pull requests merged in 2022-10, with the labels that each got.

#2761 Cleanup unused type variables
  src/AbstractOperations/at.jl
  src/AbstractOperations/derivatives.jl
  src/OutputReaders/field_dataset.jl
Labels: cleanup 🧹

#2762 Fix some docstrings
  src/AbstractOperations/at.jl
  src/AbstractOperations/binary_operations.jl
  src/AbstractOperations/computed_field.jl
  src/AbstractOperations/conditional_operations.jl
  src/AbstractOperations/derivatives.jl
  src/AbstractOperations/grid_metrics.jl
  src/AbstractOperations/unary_operations.jl
  src/Advection/centered_reconstruction.jl
  src/Advection/momentum_advection_operators.jl
  src/Advection/tracer_advection_operators.jl
  src/Advection/upwind_biased_reconstruction.jl
  src/Fields/field.jl
  src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_variables.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/HydrostaticFreeSurfaceModels/vertical_vorticity_field.jl
Labels: documentation 📜

#2757 Fix flat advective fluxes
  src/Advection/centered_reconstruction.jl
  src/Advection/flat_advective_fluxes.jl
Labels: bug 🐞

#2779 Bump SeawaterPolynomials to v0.3.0
  Manifest.toml
  docs/src/model_setup/buoyancy_and_equation_of_state.md
Labels: package 📦

#2791 Update list of papers using Oceananigans
  docs/src/index.md
Labels: documentation 📜
