Repository CliMA/Oceananigans.jl, pull requests merged in 2022-09, with the labels that each got.

#2654 Preconditioning CG solver with Multigrid
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_variables.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface_utils.jl
  src/Models/HydrostaticFreeSurfaceModels/mg_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
  src/Solvers/multigrid_solver.jl
  test/test_implicit_free_surface_solver.jl
  validation/elliptic_solvers/doubly_bounded_poisson.jl
  validation/implicit_free_surface/implicit_surface_solvers_benchmark.jl
Labels: science 🌊, numerics 🧮

#2731 Fix bullet points in Docs/Model setup/Boundary conditions
  docs/src/model_setup/boundary_conditions.md
Labels: documentation 📜

#2736 Reduces allocations for Multigrid solver on CPU: Multilevel structure only created when required
  src/Models/HydrostaticFreeSurfaceModels/mg_implicit_free_surface_solver.jl
  src/Solvers/multigrid_solver.jl
Labels: performance 🏍️

#2734 Correct computation for buoyancy dissipation rate, `χ_diff` + demonstrate `Integral`
  docs/make.jl
  examples/horizontal_convection.jl
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
Labels: documentation 📜, output 💾

#2688 Add GPU functionality to Multigrid solver
  .gitignore
  Manifest.toml
  Project.toml
  benchmark/benchmark_implicit_surface_solvers.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/mg_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
  src/Oceananigans.jl
  src/Solvers/Solvers.jl
  src/Solvers/multigrid_solver.jl
  src/Solvers/preconditioned_conjugate_gradient_solver.jl
  test/test_hydrostatic_free_surface_immersed_boundaries_implicit_solve.jl
  test/test_implicit_free_surface_solver.jl
  test/test_multigrid_solver.jl
  validation/elliptic_solvers/doubly_bounded_poisson.jl
Labels: numerics 🧮, GPU 👾

#2729 Wet point Coriolis scheme and bugfix in GM tapering
  Project.toml
  src/Coriolis/Coriolis.jl
  src/Coriolis/hydrostatic_spherical_coriolis.jl
  src/Grids/inactive_node.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/conditional_derivatives.jl
  src/ImmersedBoundaries/conditional_fluxes.jl
  src/ImmersedBoundaries/grid_fitted_immersed_boundaries.jl
  src/ImmersedBoundaries/immersed_reductions.jl
  src/ImmersedBoundaries/mask_immersed_field.jl
  src/Operators/Operators.jl
  src/TurbulenceClosures/abstract_scalar_biharmonic_diffusivity_closure.jl
  src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
  validation/multi_region/multi_region_near_global_quarter_degree.jl
  validation/near_global_lat_lon/near_global_quarter_degree_one_level.jl
Labels: bug 🐞, numerics 🧮

#2745 Fix `CenterField` docstring
  src/Fields/field.jl
Labels: documentation 📜

#2746 Bug fix for general interpolation
  src/MultiRegion/multi_region_output_writers.jl
  src/Operators/Operators.jl
  src/Operators/interpolation_operators.jl
  src/Operators/interpolation_utils.jl
Labels: bug 🐞

#2749 Fix bug in `num_prod`
  src/Advection/reconstruction_coefficients.jl
Labels: bug 🐞

#2733 Add direct access to auxiliary fields for forcing functions
  docs/src/model_setup/forcing_functions.md
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Models/NonhydrostaticModels/calculate_nonhydrostatic_tendencies.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl
  src/Models/ShallowWaterModels/ShallowWaterModels.jl
  src/Utils/user_function_arguments.jl
  test/test_forcings.jl
Labels: user interface/experience 💻

#2740 BC and Immersed Reductions for Sliced Fields
  src/AbstractOperations/AbstractOperations.jl
  src/AbstractOperations/at.jl
  src/AbstractOperations/binary_operations.jl
  src/AbstractOperations/computed_field.jl
  src/AbstractOperations/conditional_operations.jl
  src/AbstractOperations/derivatives.jl
  src/AbstractOperations/grid_metrics.jl
  src/AbstractOperations/kernel_function_operation.jl
  src/AbstractOperations/multiary_operations.jl
  src/AbstractOperations/unary_operations.jl
  src/BoundaryConditions/fill_halo_regions.jl
  src/BoundaryConditions/fill_halo_regions_flux.jl
  src/BoundaryConditions/fill_halo_regions_open.jl
  src/BoundaryConditions/fill_halo_regions_periodic.jl
  src/CubedSpheres/CubedSpheres.jl
  src/CubedSpheres/conformal_cubed_sphere_grid.jl
  src/CubedSpheres/cubed_sphere_faces.jl
  src/Distributed/halo_communication.jl
  src/Fields/field.jl
  src/Fields/field_tuples.jl
  src/Fields/function_field.jl
  src/Fields/set!.jl
  src/Grids/input_validation.jl
  src/Grids/new_data.jl
  src/ImmersedBoundaries/conditional_derivatives.jl
  src/ImmersedBoundaries/immersed_reductions.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/barotropic_pressure_correction.jl
  src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/fft_based_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface_utils.jl
  src/Models/HydrostaticFreeSurfaceModels/matrix_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/mg_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
  src/Models/HydrostaticFreeSurfaceModels/store_hydrostatic_free_surface_tendencies.jl
  src/MultiRegion/multi_region_boundary_conditions.jl
  src/MultiRegion/multi_region_field.jl
  src/MultiRegion/unified_implicit_free_surface_solver.jl
  src/Operators/Operators.jl
  src/Operators/divergence_operators.jl
  src/OutputWriters/output_construction.jl
  src/Solvers/fft_based_poisson_solver.jl
  src/Solvers/fourier_tridiagonal_poisson_solver.jl
  src/Solvers/preconditioned_conjugate_gradient_solver.jl
  test/test_abstract_operations.jl
  test/test_checkpointer.jl
  test/test_field_reductions.jl
  test/test_implicit_free_surface_solver.jl
  test/test_multi_region_advection_diffusion.jl
  test/test_multi_region_implicit_solver.jl
  test/test_operators.jl
  test/test_split_explicit_free_surface_solver.jl
  validation/solid_body_rotation/rossby_haurwitz.jl
Labels: abstractions 🎨, user interface/experience 💻
