Repository CliMA/Oceananigans.jl, pull requests merged in 2022-07, with the labels that each got.

#2640 Use predefined `compute_∇²!` instead of defining new `calc_∇²!` in `test_matrix_poisson_solver.jl`
  test/test_matrix_poisson_solver.jl
  test/test_multi_region_poisson_solver.jl
Labels: cleanup 🧹

#2649 Change `CUDA.query` (deprecated) -> `CUDA.isdone`
  src/Architectures.jl
Labels: GPU 👾

#2645 Viscous term for Shallow Water model
  src/Models/ShallowWaterModels/ShallowWaterModels.jl
  src/Models/ShallowWaterModels/calculate_shallow_water_tendencies.jl
  src/Models/ShallowWaterModels/shallow_water_advection_operators.jl
  src/Models/ShallowWaterModels/shallow_water_diffusion_operators.jl
  src/Models/ShallowWaterModels/shallow_water_model.jl
  src/Models/ShallowWaterModels/solution_and_tracer_tendencies.jl
  src/Models/ShallowWaterModels/update_shallow_water_state.jl
  src/TurbulenceClosures/turbulence_closure_utils.jl
  test/regression_tests/shallow_water_bickley_jet_regression.jl
  test/test_shallow_water_models.jl
Labels: science 🌊

#2632 Add example for `FieldBoundaryConditions` on an `ImmersedBoundaryGrid`
  docs/src/model_setup/boundary_conditions.md
  src/BoundaryConditions/field_boundary_conditions.jl
Labels: documentation 📜, immersed boundaries ⛰️

#2651 Bugfix for `DiscreteDiffusionFunction` + passes prognostic + auxiliary fields to forcing functions
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/TurbulenceClosures/turbulence_closure_utils.jl
  test/test_turbulence_closures.jl
Labels: bug 🐞

#2664 Fixes to Gent McWilliams parametrization
  Project.toml
  src/TurbulenceClosures/isopycnal_rotation_tensor_components.jl
  src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
Labels: bug 🐞, turbulence closures 🎐
