Repository CliMA/Oceananigans.jl, pull requests merged in 2022-03, with the labels that each got.

#2289 Better local variable name: `area` -> `grid_metric`
  src/Operators/products_between_fields_and_grid_metrics.jl
Labels: cleanup 🧹

#2283 Small adjustment to Turbulence Closures section of docs
  docs/src/physics/turbulence_closures.md
Labels: documentation 📜

#2294 Use verbose names in `LinearEquationOfState`
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  examples/ocean_wind_mixing_and_convection.jl
  src/BuoyancyModels/linear_equation_of_state.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/test_abstract_operations.jl
  test/test_buoyancy.jl
  test/test_computed_field.jl
  test/test_dynamics.jl
  validation/mesoscale_turbulence/eddying_channel_nonhydrostatic.jl
  validation/near_global_lat_lon/annual_cycle_earth_bathymetry.jl
  validation/near_global_lat_lon/annual_cycle_earth_bathymetry_fine.jl
  validation/near_global_lat_lon/constant_forcing_earth_bathymetry.jl
  validation/stratified_couette_flow/stratified_couette_flow.jl
Labels: user interface/experience 💻

#2287 Update turbulence closures Docs section
  docs/src/physics/turbulence_closures.md
  src/TurbulenceClosures/implicit_explicit_time_discretization.jl
Labels: documentation 📜

#2288 Fix inconsistent variable definition in `ScalarDiffusivity` constructor
  Project.toml
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
  src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl
  test/test_dynamics.jl
Labels: turbulence closures 🎐

#2310 Update Docs authors
  docs/make.jl
Labels: documentation 📜

#2322 Enhances docstrings for timesteppers
  docs/oceananigans.bib
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/clock.jl
  src/TimeSteppers/quasi_adams_bashforth_2.jl
  src/TimeSteppers/runge_kutta_3.jl
Labels: documentation 📜

#2298 Quarter degree near global simulation
  validation/near_global_lat_lon/annual_cycle_earth_bathymetry_fine.jl
  validation/near_global_lat_lon/near-global-quarter-degree.jl
Labels: science 🌊

#2328 Adds methods to make CATKE work better with other closures
  Project.toml
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl
Labels: bug 🐞, turbulence closures 🎐

#2324 Split timestep tests
  .buildkite/pipeline.yml
  test/runtests.jl
Labels: testing 🧪

#2331 Better `show()` method + fix docstring for convective adjustment
  docs/src/model_setup/turbulent_diffusivity_closures_and_les_models.md
  src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl
Labels: documentation 📜, user interface/experience 💻

#2312 A more detailed session for installation instructions
  docs/src/installation_instructions.md
Labels: documentation 📜

#2334 Better docstrings for scalar diffusivity closures
  Project.toml
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
Labels: documentation 📜

#2346 Serialize grids with CPU architecture
  Project.toml
  src/OutputWriters/output_writer_utils.jl
Labels: output 💾

#2357 Update README to use latest syntax
  README.md
Labels: documentation 📜

#2362 Bugfix in `fill_halo` for julia < 1.7
  Project.toml
  src/BoundaryConditions/fill_halo_regions.jl
  src/Operators/products_between_fields_and_grid_metrics.jl
Labels: bug 🐞, numerics 🧮

#2365 Add `show` for `Reductions`
  src/AbstractOperations/AbstractOperations.jl
  src/AbstractOperations/computed_field.jl
  src/AbstractOperations/metric_field_reductions.jl
  src/Fields/field_reductions.jl
Labels: user interface/experience 💻

#2370 Denote which coordinate is lat and which is lon in `show(io, ::LatitudeLongitudeGrid)`
  src/Grids/grid_utils.jl
  src/Grids/latitude_longitude_grid.jl
Labels: grids 🗺️, user interface/experience 💻

#2374 Update dissipation and surface TKE flux parameters for CATKE
  Project.toml
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/surface_TKE_flux.jl
Labels: science 🌊

#2376 Fix docstring alignment
  src/OutputReaders/field_dataset.jl
Labels: documentation 📜

#2380 Return `field` from `compute!(field::ReducedComputedField)`
  src/Fields/field.jl
  src/Fields/field_reductions.jl
Labels: user interface/experience 💻

#2381 Number all equations in Docs/Timestepping section
  docs/src/numerical_implementation/time_stepping.md
Labels: documentation 📜

#1570 [WIP] Adds Rossby Haurwitz and Spherical Bickley jet examples
  examples/RafsPlot.jl
  examples/rossby_haurwitz.jl
  examples/spherical_bickley.jl
Labels: documentation 📜

#2338 Update architecture in distributed benchmark scripts
  benchmark/distributed_nonhydrostatic_model_mpi.jl
  benchmark/distributed_shallow_water_model_mpi.jl
Labels: distributed 🕸️

#2393 Adds a paper that uses Oceananigans in Docs
  docs/src/index.md
Labels: documentation 📜

#2392 Fixes and tests `Field(u::Field; indices)` and `Field(u::AbstractOperation; indices)`
  Project.toml
  src/AbstractOperations/computed_field.jl
  src/Fields/field.jl
  test/test_computed_field.jl
  test/test_field.jl
Labels: bug 🐞

#2379 Implements RiBasedVerticalDiffusivity
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/abstract_scalar_biharmonic_diffusivity_closure.jl
  src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
  src/TurbulenceClosures/closure_kernel_operators.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/mixing_length.jl
  src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/ri_based_vertical_diffusivity.jl
  validation/vertical_mixing_closures/Manifest.toml
  validation/vertical_mixing_closures/Project.toml
  validation/vertical_mixing_closures/convective_adjustment_windy_convection.jl
  validation/vertical_mixing_closures/heterogeneous_cooling.jl
  validation/vertical_mixing_closures/tke_based_free_convection.jl
  validation/vertical_mixing_closures/tke_based_wind_mixing.jl
  validation/vertical_mixing_closures/windy_convection.jl
Labels: science 🌊
