Repository CliMA/Oceananigans.jl, pull requests merged in 2022-04, with the labels that each got.

#2425 Proper reductions for FieldTimeSeries
  Project.toml
  src/OutputReaders/field_time_series.jl
  src/Simulations/run.jl
  src/Simulations/simulation.jl
Labels: bug 🐞

#2378 Change default halo size to 3 in non-`Flat` directions
  Project.toml
  docs/src/model_setup/background_fields.md
  docs/src/model_setup/boundary_conditions.md
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  docs/src/model_setup/grids.md
  docs/src/model_setup/lagrangian_particles.md
  docs/src/model_setup/tracers.md
  src/AbstractOperations/binary_operations.jl
  src/AbstractOperations/conditional_operations.jl
  src/AbstractOperations/grid_metrics.jl
  src/AbstractOperations/multiary_operations.jl
  src/AbstractOperations/unary_operations.jl
  src/Fields/field.jl
  src/Fields/regridding_fields.jl
  src/Grids/grid_utils.jl
  src/Grids/input_validation.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/rectilinear_grid.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/test_field.jl
  test/test_grids.jl
  test/test_halo_regions.jl
  test/test_hydrostatic_free_surface_models.jl
  test/test_jld2_output_writer.jl
  test/test_nonhydrostatic_models.jl
  test/test_split_explicit_free_surface_solver.jl
Labels: grids 🗺️

#2333 Excise some examples and improve others
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/oceananigans.bib
  examples/baroclinic_adjustment.jl
  examples/one_dimensional_diffusion.jl
  examples/tilted_bottom_boundary_layer.jl
  validation/mesoscale_turbulence/eady_turbulence.jl
Labels: documentation 📜

#2446 Use Julia v1.6.6 LTS
  .buildkite/pipeline.yml
  .buildkite/validation-pipeline.yml
  Dockerfile
Labels: package 📦

#2348 More distributed validation scripts
  src/Distributed/Distributed.jl
  src/Distributed/distributed_fields.jl
  src/Distributed/distributed_grids.jl
  src/Distributed/partition_assemble.jl
  validation/distributed_simulations/mpi_nonhydrostatic_two_dimensional_turbulence.jl
  validation/distributed_simulations/mpi_output_writing.jl
  validation/distributed_simulations/mpi_set.jl
  validation/distributed_simulations/mpi_shallow_water_turbulence.jl
Labels: distributed 🕸️

#2451 Fix typos in Docs/Numerics/Poisson solvers
  docs/src/numerical_implementation/poisson_solvers.md
Labels: documentation 📜

#2449 Move CATKE diffusivities to vertical cell interfaces
  Project.toml
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/mixing_length.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/turbulent_kinetic_energy_equation.jl
  validation/vertical_mixing_closures/windy_convection.jl
Labels: turbulence closures 🎐

#2458 Few beautifications in docstrings
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/Solvers/fft_based_poisson_solver.jl
  src/Solvers/preconditioned_conjugate_gradient_solver.jl
Labels: documentation 📜

#2459 Few minor beauty fixes
  src/Architectures.jl
  src/BoundaryConditions/BoundaryConditions.jl
  src/BuoyancyModels/BuoyancyModels.jl
  src/Coriolis/Coriolis.jl
  src/Diagnostics/Diagnostics.jl
  src/Fields/regridding_fields.jl
  src/Forcings/Forcings.jl
  src/Grids/Grids.jl
  src/Grids/rectilinear_grid.jl
  src/Logger.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/Models.jl
  src/Models/NonhydrostaticModels/correct_nonhydrostatic_immersed_tendencies.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Models/NonhydrostaticModels/solve_for_pressure.jl
  src/Operators/Operators.jl
  src/OutputWriters/OutputWriters.jl
  src/OutputWriters/windowed_time_average.jl
  src/Solvers/Solvers.jl
  src/Solvers/fourier_tridiagonal_poisson_solver.jl
  src/Solvers/heptadiagonal_iterative_solver.jl
  src/Solvers/index_permutations.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/runge_kutta_3.jl
  src/Units.jl
  src/Utils/Utils.jl
Labels: documentation 📜

#2460 Better diffusivity closure `show()`
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
Labels: turbulence closures 🎐, user interface/experience 💻

#2437 Support boundary conditions on immersed boundaries
  Project.toml
  docs/src/model_setup/boundary_conditions.md
  src/BoundaryConditions/boundary_condition.jl
  src/BoundaryConditions/continuous_boundary_function.jl
  src/BoundaryConditions/discrete_boundary_function.jl
  src/BoundaryConditions/field_boundary_conditions.jl
  src/BoundaryConditions/show_boundary_conditions.jl
  src/CubedSpheres/CubedSpheres.jl
  src/Fields/field.jl
  src/Grids/Grids.jl
  src/Grids/grid_solid_nodes.jl
  src/Grids/inactive_node.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/rectilinear_grid.jl
  src/Grids/zeros.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/conditional_derivatives.jl
  src/ImmersedBoundaries/conditional_fluxes.jl
  src/ImmersedBoundaries/grid_fitted_immersed_boundaries.jl
  src/ImmersedBoundaries/immersed_boundary_condition.jl
  src/ImmersedBoundaries/immersed_grid_metrics.jl
  src/ImmersedBoundaries/immersed_reductions.jl
  src/ImmersedBoundaries/mask_immersed_field.jl
  src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Models/NonhydrostaticModels/calculate_nonhydrostatic_tendencies.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl
  src/Oceananigans.jl
  src/Operators/derivative_operators.jl
  src/Operators/divergence_operators.jl
  src/Operators/interpolation_operators.jl
  src/OutputWriters/checkpointer.jl
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/OutputWriters/output_writer_utils.jl
  src/TurbulenceClosures/abstract_scalar_biharmonic_diffusivity_closure.jl
  src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
  src/TurbulenceClosures/closure_kernel_operators.jl
  src/TurbulenceClosures/diffusion_operators.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/surface_TKE_flux.jl
  test/test_boundary_conditions_integration.jl
  test/test_dynamics.jl
  validation/immersed_boundaries/flow_over_hills.jl
  validation/immersed_boundaries/immersed_couette_flow.jl
  validation/immersed_boundaries/immersed_tracer_1D.jl
Labels: immersed boundaries ⛰️

#2476 Fix typo in `HydrostaticFreeSurfaceModel` docs
  docs/src/physics/hydrostatic_free_surface_model.md
Labels: documentation 📜

#2474 Update docs to point to discussions, wiki, etc
  README.md
  docs/make.jl
  docs/src/index.md
  docs/src/installation_instructions.md
  docs/src/model_setup/grids.md
  docs/src/quick_start.md
  docs/src/using_gpus.md
  examples/two_dimensional_turbulence.jl
  src/Grids/latitude_longitude_grid.jl
Labels: documentation 📜

#2481 Implement the actually-Cox (aka the anti-anti-Cox) stencil for GM
  src/TurbulenceClosures/isopycnal_rotation_tensor_components.jl
  src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
  validation/mesoscale_turbulence/coarse_lat_lon_baroclinic_adjustment.jl
Labels: numerics 🧮, turbulence closures 🎐

#2486 Pin MPICH_jll at 4.0.1
  Project.toml
Labels: package 📦

#2496 Drop MPICH_jll direct dependency
  Project.toml
  docs/src/index.md
Labels: package 📦

#2487 VerticallyImplicitTimeDiscretization for symmetric isoneutral diffusion
  Project.toml
  src/Grids/zeros.jl
  src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
  src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
  src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl
Labels: numerics 🧮, turbulence closures 🎐

#2504 Update `JLD2OutputWriter` calls
  validation/barotropic_gyre/barotropic_gyre.jl
  validation/bickley_jet/bickley_jet.jl
  validation/bickley_jet/immersed_bickley_jet.jl
  validation/bickley_jet/spherical_bickley_jet.jl
  validation/biogeochemistry/sediment_entrainment.jl
  validation/convergence_tests/src/DoublyPeriodicTaylorGreen.jl
  validation/convergence_tests/src/ForcedFlowFixedSlip.jl
  validation/convergence_tests/src/ForcedFlowFreeSlip.jl
  validation/convergence_tests/src/TwoDimensionalDiffusion.jl
  validation/cubed_sphere_eddying_aquaplanet/cubed_sphere_eddying_aquaplanet.jl
  validation/cubed_sphere_rossby_haurwitz/cubed_sphere_rossby_haurwitz.jl
  validation/cubed_sphere_surface_gravity_waves/cubed_sphere_surface_gravity_waves.jl
  validation/cubed_sphere_surface_gravity_waves/surface_gravity_waves_on_face.jl
  validation/cubed_sphere_tracer_advection/cubed_sphere_tracer_advection.jl
  validation/curvilinear_diffusion/longitudinal_tracer_diffusion.jl
  validation/curvilinear_diffusion/meridional_diffusion.jl
  validation/curvilinear_diffusion/spot_tracer_diffusion.jl
  validation/distributed_simulations/mpi_nonhydrostatic_two_dimensional_turbulence.jl
  validation/distributed_simulations/mpi_output_writing.jl
  validation/immersed_boundaries/bumpy_baroclinic_adjustment.jl
  validation/immersed_boundaries/immersed_bickley_jet.jl
  validation/immersed_boundaries/immersed_cubed_sphere_rossby_haurwitz.jl
  validation/immersed_boundaries/internal_tide.jl
  validation/immersed_boundaries/shallow_water_flow_past_cape.jl
  validation/immersed_boundaries/shallow_water_flow_past_cylinder.jl
  validation/implicit_free_surface/geostrophic_adjustment_test.jl
  validation/mesoscale_turbulence/abernathey_channel.jl
  validation/mesoscale_turbulence/baroclinic_adjustment.jl
  validation/mesoscale_turbulence/eddying_channel.jl
  validation/mesoscale_turbulence/zonally_averaged_abernathey_channel.jl
  validation/mesoscale_turbulence/zonally_averaged_channel.jl
  validation/near_global_lat_lon/annual_cycle_earth_bathymetry.jl
  validation/near_global_lat_lon/constant_forcing_earth_bathymetry.jl
  validation/near_global_lat_lon/freely_decaying_barotropic_turbulence.jl
  validation/near_global_lat_lon/near-global-quarter-degree.jl
  validation/solid_body_rotation/solid_body_rotation.jl
  validation/solid_body_rotation/solid_body_tracer_advection.jl
  validation/vertical_mixing_closures/heterogeneous_cooling.jl
Labels: output 💾

#2505 Fix url for section about papers citing Oceananigans
  README.md
Labels: documentation 📜
