Repository CliMA/Oceananigans.jl, pull requests merged in 2022-05, with the labels that each got.

#2510 Remove vertical advection from vector invariant WENO
  src/Advection/vector_invariant_advection.jl
Labels: numerics 🧮

#2524 OutputWriters for MultiRegion
  src/MultiRegion/multi_region_output_writers.jl
Labels: feature 🌟

#2521 Add tests for computations on slices
  test/test_computed_field.jl
Labels: testing 🧪

#2518 Drop direct dependency to GPUArrays and BenchmarkTools
  Manifest.toml
  Project.toml
Labels: package 📦

#2447 Update dependency packages
  Manifest.toml
  Project.toml
  docs/Manifest.toml
Labels: package 📦

#2513 Permute PencilFFT temporary array dimensions
  src/Distributed/distributed_fft_based_poisson_solver.jl
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Models/NonhydrostaticModels/solve_for_pressure.jl
  test/test_distributed_models.jl
  test/test_distributed_poisson_solvers.jl
Labels: distributed 🕸️

#2531 Cosmetic improvement to checkpointer docs
  src/OutputWriters/checkpointer.jl
Labels: documentation 📜

#2551 Fixes bug in IBM with Value or Gradient boundary conditions
  Project.toml
  src/ImmersedBoundaries/immersed_boundary_condition.jl
Labels: bug 🐞, immersed boundaries ⛰️

#2552 Update PencilArrays
  Manifest.toml
Labels: package 📦

#2553 Convert `two_dimensional_turbulence.jl` and `internal_wave.jl` literated examples in docs to use CairoMakie
  docs/Manifest.toml
  examples/baroclinic_adjustment.jl
  examples/geostrophic_adjustment.jl
  examples/internal_wave.jl
  examples/two_dimensional_turbulence.jl
Labels: documentation 📜

#2556 Convert more examples to plot with Makie
  examples/langmuir_turbulence.jl
  examples/one_dimensional_diffusion.jl
  examples/shallow_water_Bickley_jet.jl
  examples/tilted_bottom_boundary_layer.jl
Labels: documentation 📜

#2569 Fix inconsistent behaviour in `test_matrix_poisson_solver.jl`
  test/test_matrix_poisson_solver.jl
Labels: testing 🧪

#2562 Eliminate Plots as dependency in Docs; use Makie
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/make_example.jl
  docs/src/model_setup/grids.md
  examples/convecting_plankton.jl
  examples/horizontal_convection.jl
  examples/kelvin_helmholtz_instability.jl
  examples/langmuir_turbulence.jl
  examples/ocean_wind_mixing_and_convection.jl
  examples/shallow_water_Bickley_jet.jl
  examples/tilted_bottom_boundary_layer.jl
Labels: documentation 📜

#2572 Fix matrix solver test take 2
  test/test_matrix_poisson_solver.jl
Labels: testing 🧪

#2573 small bugfix in `Integral` construction
  src/AbstractOperations/metric_field_reductions.jl
Labels: bug 🐞

#2574 Update dependencies
  Manifest.toml
  docs/Manifest.toml
Labels: package 📦
