Repository CliMA/Oceananigans.jl, pull requests merged in 2022-06, with the labels that each got.

#2596 Check for CUDA-enabled device on `grid` construction rather than in model constructors
  src/Grids/Grids.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/rectilinear_grid.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
Labels: cleanup 🧹, GPU 👾

#2522 Vector Invariant Formulation of the `ShallowWaterModel`
  .buildkite/pipeline.yml
  docs/src/physics/shallow_water_model.md
  examples/shallow_water_Bickley_jet.jl
  src/Grids/grid_generation.jl
  src/Grids/latitude_longitude_grid.jl
  src/Models/HydrostaticFreeSurfaceModels/vertical_vorticity_field.jl
  src/Models/Models.jl
  src/Models/ShallowWaterModels/ShallowWaterModels.jl
  src/Models/ShallowWaterModels/calculate_shallow_water_tendencies.jl
  src/Models/ShallowWaterModels/rk3_substep_shallow_water_model.jl
  src/Models/ShallowWaterModels/shallow_water_advection_operators.jl
  src/Models/ShallowWaterModels/shallow_water_cell_advection_timescale.jl
  src/Models/ShallowWaterModels/shallow_water_model.jl
  src/Models/ShallowWaterModels/solution_and_tracer_tendencies.jl
  src/Models/ShallowWaterModels/store_shallow_water_tendencies.jl
  src/Models/ShallowWaterModels/update_shallow_water_state.jl
  src/Oceananigans.jl
  src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
  test/data_dependencies.jl
  test/regression_tests/shallow_water_bickley_jet_regression.jl
  test/runtests.jl
  test/test_distributed_models.jl
  test/test_shallow_water_models.jl
  test/test_shallow_water_regression.jl
  validation/near_global_lat_lon/near_global_quarter_degree_one_level.jl
  validation/near_global_lat_lon/visualize.jl
  validation/shallow_water_model/make_animation.jl
  validation/shallow_water_model/near_global_shallow_water_quarter_degree.jl
  validation/shallow_water_model/vortex_merger.jl
Labels: numerics 🧮

#2599 Updates for Docs/Physics section
  docs/make.jl
  docs/src/physics/boundary_conditions.md
  docs/src/physics/boussinesq.md
  docs/src/physics/buoyancy_and_equations_of_state.md
  docs/src/physics/coriolis_forces.md
  docs/src/physics/hydrostatic_free_surface_model.md
  docs/src/physics/nonhydrostatic_model.md
  docs/src/physics/notation.md
  docs/src/physics/surface_gravity_waves.md
  docs/src/physics/turbulence_closures.md
Labels: documentation 📜

#2601 Drop SafeTestset from package dependency
  Manifest.toml
  Project.toml
Labels: package 📦

#2607 Fix `ShallowWaterModel` closure for tracers in the vector invariant form
  src/Models/ShallowWaterModels/solution_and_tracer_tendencies.jl
Labels: bug 🐞

#2614 Adds back a fig in Docs/Model/Grids + example with `Flat` topology
  docs/src/model_setup/grids.md
Labels: documentation 📜

#2582 `compute_at!` for ConditionalOperation
  Project.toml
  src/AbstractOperations/conditional_operations.jl
  test/test_computed_field.jl
Labels: bug 🐞

#2619 Update package's dependencies
  Manifest.toml
  docs/Manifest.toml
Labels: package 📦

#2617 Add docstring for `SpecifiedTimes`
  src/Utils/schedules.jl
Labels: documentation 📜

#2624 Add empty PR template
  .github/pull_request_template.md
Labels: package 📦

#2621 Update `ImplicitFreeSurface` & `HeptadiagonalIterativeSolver` docstrings
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Solvers/fft_based_poisson_solver.jl
  src/Solvers/heptadiagonal_iterative_solver.jl
Labels: documentation 📜

#2627 Docs library cleanup
  docs/src/appendix/library.md
  src/Advection/tracer_advection_operators.jl
  src/Models/ShallowWaterModels/shallow_water_advection_operators.jl
  src/Operators/divergence_operators.jl
  src/Operators/laplacian_operators.jl
Labels: documentation 📜

#2633 Fix typo in Docs/Buoyancy models
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  test/test_computed_field.jl
  validation/mesoscale_turbulence/baroclinic_adjustment.jl
  validation/mesoscale_turbulence/eddying_channel.jl
  validation/near_global_lat_lon/freely_decaying_barotropic_turbulence.jl
Labels: documentation 📜
