Repository CliMA/Oceananigans.jl, pull requests merged in 2023-09, with the labels that each got.

#3248 Update `TimeStepWizard`
  src/Simulations/time_step_wizard.jl
Labels: documentation 📜, user interface/experience 💻

#3235 (0.87.3) BugFix for computing `Field(::KernelFunctionOperation)`
  Project.toml
  src/Utils/multi_region_transformation.jl
  test/test_computed_field.jl
Labels: bug 🐞

#3258 Update dependencies and use Julia 1.9.3 for CI
  .buildkite/pipeline.yml
  Dockerfile
  Manifest.toml
  docs/Manifest.toml
Labels: package 📦

#3257 Rename `return_metrics` -> `coordinates`
  src/Advection/Advection.jl
  src/Advection/reconstruction_coefficients.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/rectilinear_grid.jl
  src/ImmersedBoundaries/immersed_grid_metrics.jl
Labels: cleanup 🧹

#3266 Cubed sphere tracer advection script
  src/AbstractOperations/broadcasting_abstract_operations.jl
  src/Fields/broadcasting_abstract_fields.jl
  src/Fields/constant_field.jl
  src/Fields/field_boundary_buffers.jl
  src/Fields/field_tuples.jl
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/Models/NonhydrostaticModels/set_nonhydrostatic_model.jl
  src/MultiRegion/cubed_sphere_partitions.jl
  src/MultiRegion/multi_region_cubed_sphere_grid.jl
  src/MultiRegion/multi_region_field.jl
  src/MultiRegion/multi_region_grid.jl
  src/MultiRegion/multi_region_models.jl
  src/Oceananigans.jl
  test/test_hydrostatic_free_surface_models.jl
  test/test_multi_region_cubed_sphere.jl
  validation/multi_region/cubed_sphere_tracer_advection.jl
  validation/multi_region/multi_region_cubed_sphere.jl
Labels: cubed sphere 🧊🌎

#3271 Remove some type instabilities
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
  src/Models/Models.jl
  src/Models/ShallowWaterModels/shallow_water_model.jl
Labels: numerics 🧮

#3255 Fix docstring for `RectilinearGrid` grid metrics
  src/Grids/rectilinear_grid.jl
Labels: documentation 📜, grids 🗺️

#3239 Fill metrics for halo regions for `OrthogonalSphericalShellGrid`
  src/Grids/grid_generation.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Grids/rectilinear_grid.jl
  test/test_grids.jl
  validation/orthogonal_spherical_shell_grid/splash.jl
Labels: grids 🗺️

#3278 Reorder compat entries in alphabetical order
  Project.toml
Labels: package 📦

#3293 Propagate eltype through FFT-based implicit free surface solver
  src/Models/HydrostaticFreeSurfaceModels/fft_based_implicit_free_surface_solver.jl
Labels: good first issue 🐤

#3296 Fixes bug in free surface build for `HydrostaticFreeSurfaceModel`s on a `ConformalCubedSphereGrid`
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
  src/MultiRegion/multi_region_cubed_sphere_grid.jl
  test/test_multi_region_cubed_sphere.jl
Labels: bug 🐞, cubed sphere 🧊🌎

#3294 Fixes docstring for free surface in `HydrostaticFreeSurfaceModel`
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
Labels: documentation 📜

#3273 Type stabilize offset_data
  src/Grids/new_data.jl
Labels: numerics 🧮
