Repository CliMA/Oceananigans.jl, pull requests merged in 2023-02, with the labels that each got.

#2894 Better show for impenetrable boundary condition
  src/BoundaryConditions/show_boundary_conditions.jl
Labels: boundary conditions 🏓, user interface/experience 💻

#2871 CubedSphere grid construction + tests
  src/CubedSpheres/conformal_cubed_sphere_grid.jl
  src/Grids/grid_utils.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  test/test_grids.jl
Labels: testing 🧪, grids 🗺️, cubed sphere 🧊🌎

#2897 Fix in lat-lon grid `Δy` metric
  src/Grids/latitude_longitude_grid.jl
Labels: grids 🗺️

#2903 Some docstring fixes/enhancements + Code cleanup
  benchmark/benchmark_abstract_operations.jl
  benchmark/benchmark_advection_schemes.jl
  benchmark/benchmark_equations_of_state.jl
  benchmark/benchmark_fourier_tridiagonal_poisson_solver.jl
  benchmark/benchmark_lagrangian_particle_tracking.jl
  benchmark/benchmark_multithreading_single.jl
  benchmark/benchmark_shallow_water_model.jl
  benchmark/benchmark_time_steppers.jl
  benchmark/benchmark_topologies.jl
  benchmark/benchmark_tracers.jl
  benchmark/benchmark_turbulence_closures.jl
  benchmark/benchmark_vertically_stretched_nonhydrostatic_model.jl
  benchmark/distributed_nonhydrostatic_model_threaded.jl
  benchmark/distributed_shallow_water_model_threaded.jl
  docs/src/model_setup/boundary_conditions.md
  src/AbstractOperations/grid_metrics.jl
  src/Advection/vector_invariant_advection.jl
  src/Advection/weno_reconstruction.jl
  src/Distributed/distributed_fft_based_poisson_solver.jl
  src/Models/ShallowWaterModels/shallow_water_advection_operators.jl
  src/Operators/divergence_operators.jl
  src/Operators/vorticity_operators.jl
  src/OutputReaders/field_dataset.jl
  src/OutputWriters/checkpointer.jl
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
Labels: documentation 📜

#2890 Change default output array type for `JLD2OutputWriter` to `Array{Float64}`
  Project.toml
  docs/src/model_setup/output_writers.md
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/OutputWriters/windowed_time_average.jl
  test/test_netcdf_output_writer.jl
Labels: output 💾

#2899 Upgrade KernelAbstractions to 0.8
  Manifest.toml
  Project.toml
  src/AbstractOperations/AbstractOperations.jl
  src/AbstractOperations/binary_operations.jl
  src/AbstractOperations/constant_field_abstract_operations.jl
  src/Architectures.jl
  src/BoundaryConditions/fill_halo_regions.jl
  src/Fields/field.jl
  src/Fields/regridding_fields.jl
  src/Fields/set!.jl
  src/ImmersedBoundaries/immersed_boundary_condition.jl
  src/Utils/tuple_utils.jl
  test/test_abstract_operations.jl
  test/test_computed_field.jl
Labels: GPU 👾, package 📦

#2865 Fixes writing of 3d-reduced `Field`s to NetCDF
  Project.toml
  src/OutputWriters/netcdf_output_writer.jl
  test/test_computed_field.jl
  test/test_netcdf_output_writer.jl
Labels: output 💾

#2920 Update `TimeStepWizard` docs
  src/Simulations/time_step_wizard.jl
Labels: documentation 📜

#2919 Update deps
  Manifest.toml
  docs/Manifest.toml
Labels: package 📦

#2937 Brings back ShallowWater regression test
  .buildkite/pipeline.yml
  test/data_dependencies.jl
  test/regression_tests/shallow_water_bickley_jet_regression.jl
Labels: GPU 👾, testing 🧪

#2877 Bugfix for non traditional beta plane
  .buildkite/pipeline.yml
  src/Coriolis/non_traditional_beta_plane.jl
Labels: bug 🐞

#2934 Small changes to tilted bottom boundary layer example
  examples/tilted_bottom_boundary_layer.jl
Labels: documentation 📜

#2933 Don't conflate the status of a sliced field with its parent field
  src/AbstractOperations/computed_field.jl
  src/Fields/field.jl
  src/Fields/field_reductions.jl
  src/OutputWriters/netcdf_output_writer.jl
Labels: bug 🐞, output 💾

#2941 Docstring for `ShallowWaterScalarDiffusivity`
  src/Models/ShallowWaterModels/shallow_water_diffusion_operators.jl
  test/test_shallow_water_models.jl
Labels: documentation 📜

#2944 `\textit{...}` -> `*...*` for correct rendering in `boundary_conditions.md`
  docs/src/physics/boundary_conditions.md
Labels: documentation 📜

#2946 Informative error message for non-regularly spaced grids in `NonhydrostaticModel`
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
Labels: user interface/experience 💻
