Repository CliMA/Oceananigans.jl, pull requests merged in 2023-03, with the labels that each got.

#2952 Convert docstring example to doctest
  src/BuoyancyModels/buoyancy.jl
Labels: testing 🧪, documentation 📜

#2955 Added another parameter for gravitational acceleration
  src/Models/ShallowWaterModels/shallow_water_model.jl
Labels: bug 🐞

#2951 Return zero for `closure == nothing`
  src/Oceananigans.jl
  src/TurbulenceClosures/turbulence_closure_implementations/nothing_closure.jl
  test/test_turbulence_closures.jl
Labels: user interface/experience 💻

#2958 Some updates in Docs/Simulations tips
  docs/src/simulation_tips.md
Labels: documentation 📜

#2957 Fix bug in hydrostatic spherical Coriolis
  Project.toml
  src/Coriolis/hydrostatic_spherical_coriolis.jl
Labels: bug 🐞

#2932 Clean up ImmersedBoundaries module
  src/ImmersedBoundaries/grid_fitted_immersed_boundaries.jl
Labels: cleanup 🧹

#2802 Adds an interface for inserting biogeochemistry models into Oceananigans models
  Project.toml
  src/Biogeochemistry.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Models/NonhydrostaticModels/calculate_nonhydrostatic_tendencies.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl
  src/Models/NonhydrostaticModels/update_nonhydrostatic_model_state.jl
  src/Oceananigans.jl
  src/Operators/interpolation_utils.jl
  test/runtests.jl
  test/test_biogeochemistry.jl
  validation/biogeochemistry/simple_plankton_continuous_form_biogeochemistry.jl
Labels: feature 🌟, science 🌊

#2842 Creates functions for grid spacings
  Project.toml
  docs/src/model_setup/output_writers.md
  examples/baroclinic_adjustment.jl
  examples/kelvin_helmholtz_instability.jl
  examples/ocean_wind_mixing_and_convection.jl
  examples/one_dimensional_diffusion.jl
  examples/tilted_bottom_boundary_layer.jl
  src/Biogeochemistry.jl
  src/BoundaryConditions/continuous_boundary_function.jl
  src/BuoyancyModels/nonlinear_equation_of_state.jl
  src/Coriolis/beta_plane.jl
  src/Coriolis/non_traditional_beta_plane.jl
  src/CubedSpheres/CubedSpheres.jl
  src/CubedSpheres/conformal_cubed_sphere_grid.jl
  src/CubedSpheres/cubed_sphere_faces.jl
  src/Fields/abstract_field.jl
  src/Fields/function_field.jl
  src/Fields/interpolate.jl
  src/Fields/regridding_fields.jl
  src/Forcings/continuous_forcing.jl
  src/Grids/Grids.jl
  src/Grids/grid_utils.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Grids/rectilinear_grid.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/grid_fitted_immersed_boundaries.jl
  src/ImmersedBoundaries/immersed_grid_metrics.jl
  src/ImmersedBoundaries/partial_cell_immersed_boundaries.jl
  src/Models/NonhydrostaticModels/correct_nonhydrostatic_immersed_tendencies.jl
  src/Oceananigans.jl
  src/Operators/Operators.jl
  src/Operators/derivative_operators.jl
  src/Operators/interpolation_utils.jl
  src/Operators/laplacian_operators.jl
  src/Operators/products_between_fields_and_grid_metrics.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/StokesDrift.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
  test/dependencies_for_poisson_solvers.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/test_biogeochemistry.jl
  test/test_computed_field.jl
  test/test_dynamics.jl
  test/test_field.jl
  test/test_grids.jl
  test/test_hydrostatic_free_surface_models.jl
  test/test_netcdf_output_writer.jl
  test/test_nonhydrostatic_models.jl
  test/test_shallow_water_models.jl
Labels: user interface/experience 💻

#2971 Fix docs rendering in Model setup/Forcing
  docs/src/model_setup/forcing_functions.md
Labels: documentation 📜

#2881 Horizontal regridding and stabilizing CATKE features
  src/Advection/upwind_biased_reconstruction.jl
  src/BuoyancyModels/nonlinear_equation_of_state.jl
  src/BuoyancyModels/seawater_buoyancy.jl
  src/Fields/regridding_fields.jl
  src/Grids/grid_utils.jl
  src/Grids/latitude_longitude_grid.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/grid_fitted_immersed_boundaries.jl
  src/ImmersedBoundaries/mask_immersed_field.jl
  src/ImmersedBoundaries/partial_cell_immersed_boundaries.jl
  src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/Models/NonhydrostaticModels/pressure_correction.jl
  src/Models/NonhydrostaticModels/set_nonhydrostatic_model.jl
  src/Models/NonhydrostaticModels/update_nonhydrostatic_model_state.jl
  src/Models/ShallowWaterModels/update_shallow_water_state.jl
  src/Solvers/batched_tridiagonal_solver.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/closure_tuples.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/mixing_length.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/turbulent_kinetic_energy_equation.jl
  src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl
  test/runtests.jl
  test/test_field.jl
  test/test_immersed_advection.jl
  test/test_regrid.jl
  validation/regridding/latitude_longitude_regridding.jl
  validation/regridding/rectilinear_regridding.jl
  validation/vertical_mixing_closures/column_windy_convection.jl
  validation/vertical_mixing_closures/convective_adjustment_free_convection.jl
  validation/vertical_mixing_closures/heterogeneous_cooling.jl
  validation/vertical_mixing_closures/heterogeneous_windy_convection.jl
  validation/vertical_mixing_closures/many_convective_adjustment_windy_convection.jl
  validation/vertical_mixing_closures/many_tke_based_free_convection.jl
  validation/vertical_mixing_closures/profile_catke.jl
  validation/vertical_mixing_closures/profile_catke_ensemble.jl
  validation/vertical_mixing_closures/windy_catke_convection.jl
Labels: feature 🌟, experimental feature 🧪

#2984 More informative message when user provides smaller halo size than ImmersedBoundraryGrid requires
  src/Fields/regridding_fields.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
Labels: user interface/experience 💻

#2994 Update contributing.md to use `main` not `master`
  docs/src/contributing.md
Labels: documentation 📜

#2993 Update `resting_stratified_bumpy_ocean.jl`
  validation/immersed_boundaries/resting_stratified_bumpy_ocean.jl
Labels: validation scripts 💅🏼

#3012 Delete validation/near_global_lat_lon directory
  validation/near_global_lat_lon/analyze_bathymetry_forcing.jl
  validation/near_global_lat_lon/annual_cycle_earth_bathymetry.jl
  validation/near_global_lat_lon/annual_cycle_forcing.jl
  validation/near_global_lat_lon/constant_forcing_earth_bathymetry.jl
  validation/near_global_lat_lon/cyclic_interpolate_utils.jl
  validation/near_global_lat_lon/freely_decaying_barotropic_turbulence.jl
  validation/near_global_lat_lon/near_global_quarter_degree.jl
  validation/near_global_lat_lon/near_global_quarter_degree_one_level.jl
  validation/near_global_lat_lon/one_degree_setups/bathymetry-360x150-latitude-75.0.jld2
  validation/near_global_lat_lon/one_degree_setups/idealized_near_global_one_degree.jl
  validation/near_global_lat_lon/one_degree_setups/one_degree_artifacts.jl
  validation/near_global_lat_lon/one_degree_setups/one_degree_interface_heights.jl
  validation/near_global_lat_lon/one_degree_setups/plot_bathymetry.jl
  validation/near_global_lat_lon/one_degree_setups/plot_boundary_conditions.jl
  validation/near_global_lat_lon/one_degree_setups/plot_initial_condition.jl
  validation/near_global_lat_lon/one_degree_setups/variable_biharmonic_diffusion_coefficient.jl
  validation/near_global_lat_lon/visualize.jl
  validation/near_global_lat_lon/visualize_annual_cycle_solution.jl
Labels: cleanup 🧹, validation scripts 💅🏼

#3026 Fixes CPU slowdown with KernelAbstractions >= v0.8
  src/BoundaryConditions/apply_flux_bcs.jl
  src/BoundaryConditions/fill_halo_regions.jl
  src/BoundaryConditions/fill_halo_regions_open.jl
  src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl
  src/Models/NonhydrostaticModels/calculate_nonhydrostatic_tendencies.jl
  src/Models/ShallowWaterModels/shallow_water_diffusion_operators.jl
  src/Operators/derivative_operators.jl
  src/Solvers/batched_tridiagonal_solver.jl
  src/TimeSteppers/quasi_adams_bashforth_2.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
  src/TurbulenceClosures/turbulence_closure_utils.jl
Labels: performance 🏍️

#3011 Fix bug in `precondition!` for `DiagonallyDominantPreconditioner`
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
Labels: bug 🐞, numerics 🧮

#3028 Brings back SWE regression
  .buildkite/pipeline.yml
Labels: testing 🧪, package 📦

#2885 Clean up methods for computing matrix that corresponds to `linear_operation!` used by MultigridSolver
  src/Models/HydrostaticFreeSurfaceModels/mg_implicit_free_surface_solver.jl
  src/Solvers/Solvers.jl
  src/Solvers/matrix_solver_utils.jl
  src/Solvers/multigrid_solver.jl
Labels: cleanup 🧹
