Repository CliMA/Oceananigans.jl, pull requests merged in 2023-12, with the labels that each got.

#3393 Add link to arXiv for scalings in README
  README.md
Labels: performance 🏍️, GPU 👾, documentation 📜

#3402 Fix CUDA compat entry
  Project.toml
Labels: GPU 👾, package 📦

#3413 (0.90.3) Fix bug in adapting `ScalarDiffusivity` and `ScalarBiharmonicDiffusivity`
  Project.toml
  src/TurbulenceClosures/discrete_diffusion_function.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
Labels: bug 🐞

#3398 Improve docstring example for seawater density
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  src/BuoyancyModels/seawater_buoyancy.jl
  src/Models/seawater_density.jl
Labels: documentation 📜
