Repository CliMA/Oceananigans.jl, pull requests merged in 2023-08, with the labels that each got.

#3225 (0.87.1) Make `set!` a little more ambitious
  Project.toml
  src/Fields/set!.jl
  test/test_field.jl
Labels: bug 🐞, boundary conditions 🏓

#3231 Update dependencies
  Manifest.toml
  docs/Manifest.toml
  src/AbstractOperations/conditional_operations.jl
Labels: package 📦

#3240 Better validation for `LatitudeLongitudeGrid` + add test for `sum(Azᶜᶜᵃ) ≈ 4πr²`
  src/Grids/latitude_longitude_grid.jl
  test/test_grids.jl
Labels: testing 🧪, grids 🗺️

#3243 Fix latex rendering in Ocean wind and mixing example
  examples/ocean_wind_mixing_and_convection.jl
Labels: documentation 📜

#3245 Provide a better explanation of the `max_change` and `min_change` of `TimeStepWizard`
  examples/horizontal_convection.jl
  src/Simulations/time_step_wizard.jl
Labels: documentation 📜, user interface/experience 💻
