Repository CliMA/Oceananigans.jl, pull requests merged in 2023-05, with the labels that each got.

#3101 Updates dependencies
  Manifest.toml
  docs/Manifest.toml
Labels: package 📦

#3102 Simplify implementation of SmagorinskyLilly + some other closure doc fixes
  src/TurbulenceClosures/implicit_explicit_time_discretization.jl
  src/TurbulenceClosures/turbulence_closure_implementations/ri_based_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/smagorinsky_lilly.jl
  src/TurbulenceClosures/turbulence_closure_utils.jl
Labels: cleanup 🧹, turbulence closures 🎐

#3096 Adds `parameters` keyword to `UniformStokesDrift`
  examples/langmuir_turbulence.jl
  src/StokesDrift.jl
  test/test_stokes_drift.jl
Labels: user interface/experience 💻

#3103 Mention native coords in `ScalarDiffusivity`/`ScalarBiharmonicDiffusivity` docs
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
Labels: documentation 📜, turbulence closures 🎐

#3106 Minor updates in `Docs/simulation_tips`
  docs/src/simulation_tips.md
Labels: documentation 📜

#3108 Small wording updates + missing `` added for correct rendering in horizontal convection example
  examples/horizontal_convection.jl
Labels: documentation 📜

#3109 Ensure that all `.jld2`/`.nc` files are deleted before docs deployment
  docs/make.jl
Labels: documentation 📜, package 📦

#3113 Find output files recursively after a doc build
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
Labels: cleanup 🧹, documentation 📜

#3118 Fix units for vorticity in tilted BL example
  examples/tilted_bottom_boundary_layer.jl
Labels: documentation 📜

#3117 Extend `BatchedTridiagonalSolver` to all directions
  src/Grids/Grids.jl
  src/Grids/grid_utils.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/Solvers/batched_tridiagonal_solver.jl
  src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl
  test/test_batched_tridiagonal_solver.jl
  test/test_time_stepping.jl
Labels: numerics 🧮
