Repository CliMA/Oceananigans.jl, pull requests merged in 2023-10, with the labels that each got.

#3212 Remove type instability in WENO β calculation for Float32
  src/Advection/weno_interpolants.jl
Labels: performance 🏍️, numerics 🧮, GPU 👾

#3305 Add `Lz` property for `OrthogonalSphericalShellGrid`
  src/Grids/orthogonal_spherical_shell_grid.jl
Labels: grids 🗺️

#3303 Add `indices` info in `show(io, ::Field)` for fields with non-default indices
  docs/src/model_setup/boundary_conditions.md
  src/Fields/field.jl
  src/Fields/show_fields.jl
Labels: user interface/experience 💻

#3304 Add more clarification in a comment
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
Labels: documentation 📜

#3274 (0.89.1) Make maximum numeric diffusivity more generic for named tuples of diffusivity
  Project.toml
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/turbulence_closure_diagnostics.jl
Labels: simulation 🎮

#3321 Fix typo in `Face` -> `Center` interpolation explanation in `Operators/README.md`
  src/Operators/README.md
Labels: documentation 📜

#3319 Add validation for array-based coordinates
  src/Grids/input_validation.jl
Labels: grids 🗺️, user interface/experience 💻

#3326 Add distributed test pipeline
  .buildkite/distributed/JuliaProject.toml
  .buildkite/distributed/pipeline.yml
  .buildkite/pipeline.yml
  Manifest.toml
  Project.toml
  test/dependencies_for_runtests.jl
Labels: testing 🧪, distributed 🕸️

#3324 Add tests for Face-Face halo filling
  Project.toml
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/MultiRegion/cubed_sphere_connectivity.jl
  src/MultiRegion/cubed_sphere_partitions.jl
  src/MultiRegion/multi_region_boundary_conditions.jl
  src/MultiRegion/multi_region_cubed_sphere_grid.jl
  test/test_multi_region_cubed_sphere.jl
  validation/multi_region/cubed_sphere_tracer_advection.jl
Labels: boundary conditions 🏓, cubed sphere 🧊🌎

#3323 Fix various bugs in auto adding bgc tracers and setting up field dependant forcing
  Project.toml
  src/Biogeochemistry.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Operators/interpolation_utils.jl
Labels: bug 🐞, boundary conditions 🏓, biogeochemistry 🦠

#3331 Throw error if nodes given by function/array generators are not sorted
  src/DistributedComputations/distributed_grids.jl
  src/Grids/grid_generation.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/rectilinear_grid.jl
Labels: cleanup 🧹, grids 🗺️

#3328 Regression tests for the Distributed module
  .buildkite/distributed/pipeline.yml
  src/Architectures.jl
  src/DistributedComputations/distributed_architectures.jl
  src/DistributedComputations/distributed_fields.jl
  src/DistributedComputations/distributed_grids.jl
  src/DistributedComputations/halo_communication.jl
  src/DistributedComputations/halo_communication_bcs.jl
  src/DistributedComputations/partition_assemble.jl
  src/Fields/field_boundary_buffers.jl
  src/ImmersedBoundaries/distributed_immersed_boundaries.jl
  src/Models/HydrostaticFreeSurfaceModels/distributed_split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
  src/OutputWriters/output_writer_utils.jl
  src/Simulations/simulation.jl
  src/Simulations/time_step_wizard.jl
  test/regression_tests/hydrostatic_free_turbulence_regression_test.jl
  test/runtests.jl
  test/test_distributed_hydrostatic_model.jl
  test/test_distributed_models.jl
  test/test_distributed_poisson_solvers.jl
  test/test_hydrostatic_regression.jl
  test/utils_for_runtests.jl
Labels: testing 🧪, distributed 🕸️

#3334 Fix docstring for `SeawaterBuoyancy`
  src/BuoyancyModels/seawater_buoyancy.jl
Labels: documentation 📜

#3310 Update dependencies + use Documenter v1
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/src/model_setup/grids.md
  docs/src/quick_start.md
  examples/baroclinic_adjustment.jl
  examples/convecting_plankton.jl
  examples/horizontal_convection.jl
  examples/internal_wave.jl
  examples/kelvin_helmholtz_instability.jl
  examples/langmuir_turbulence.jl
  examples/ocean_wind_mixing_and_convection.jl
  examples/one_dimensional_diffusion.jl
  examples/shallow_water_Bickley_jet.jl
  examples/tilted_bottom_boundary_layer.jl
  examples/two_dimensional_turbulence.jl
  src/AbstractOperations/conditional_operations.jl
  validation/mesoscale_turbulence/abernathey_channel.jl
  validation/mesoscale_turbulence/eady_turbulence.jl
  validation/mesoscale_turbulence/zonally_averaged_abernathey_channel.jl
  validation/mesoscale_turbulence/zonally_averaged_channel.jl
Labels: package 📦

#3329 Add `SeawaterDensity` to `Oceananigans.Models`
  src/Models/Models.jl
  src/Models/seawater_density.jl
  test/runtests.jl
  test/test_sewater_density.jl
Labels: feature 🌟

#3327 Add Enzyme extension
  Project.toml
  ext/OceananigansEnzymeCoreExt.jl
  test/runtests.jl
  test/test_enzyme.jl
Labels: extensions 🧬

#3347 Move Enzyme extension tests to dedicated test group
  .buildkite/pipeline.yml
  test/runtests.jl
Labels: testing 🧪, extensions 🧬

#3350 Update Docs/Model/Output Writers to replace `FieldSlicer` -> `indices`
  docs/src/model_setup/output_writers.md
Labels: documentation 📜

#3338 Add Y-partition and XY-partition tests
  .buildkite/distributed/pipeline.yml
  src/BoundaryConditions/fill_halo_regions.jl
  src/BoundaryConditions/fill_halo_regions_flux.jl
  src/BoundaryConditions/fill_halo_regions_periodic.jl
  src/BoundaryConditions/show_boundary_conditions.jl
  src/DistributedComputations/distributed_grids.jl
  src/DistributedComputations/halo_communication.jl
  src/DistributedComputations/halo_communication_bcs.jl
  src/Fields/field_boundary_buffers.jl
  src/Grids/latitude_longitude_grid.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_boundary_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
  src/Models/interleave_communication_and_computation.jl
  src/MultiRegion/multi_region_boundary_conditions.jl
  test/data_dependencies.jl
  test/regression_tests/hydrostatic_free_turbulence_regression_test.jl
  test/test_distributed_hydrostatic_model.jl
  test/test_hydrostatic_regression.jl
  test/test_multi_region_implicit_solver.jl
  test/utils_for_runtests.jl
Labels: testing 🧪, distributed 🕸️

#3341 (0.90.0) Define `WENOVectorInvariant` + some cleanup
  Project.toml
  src/Advection/Advection.jl
  src/Advection/vector_invariant_advection.jl
  src/Advection/vector_invariant_cross_upwinding.jl
  src/Advection/vector_invariant_self_upwinding.jl
  src/Advection/vector_invariant_velocity_upwinding.jl
  src/Coriolis/Coriolis.jl
  src/Coriolis/hydrostatic_spherical_coriolis.jl
  src/MultiRegion/multi_region_models.jl
  src/Oceananigans.jl
  test/test_coriolis.jl
  test/test_hydrostatic_free_surface_immersed_boundaries.jl
  test/test_hydrostatic_free_surface_models.jl
  validation/barotropic_gyre/barotropic_gyre.jl
  validation/solid_body_rotation/rossby_haurwitz.jl
  validation/solid_body_rotation/solid_body_tracer_advection.jl
Labels: user interface/experience 💻

#3355 (0.90.0) Omit entries in Flat direction from `node`
  README.md
  docs/src/quick_start.md
  examples/convecting_plankton.jl
  examples/horizontal_convection.jl
  examples/internal_wave.jl
  examples/kelvin_helmholtz_instability.jl
  examples/one_dimensional_diffusion.jl
  examples/shallow_water_Bickley_jet.jl
  examples/tilted_bottom_boundary_layer.jl
  src/BoundaryConditions/continuous_boundary_function.jl
  src/Fields/function_field.jl
  src/Fields/interpolate.jl
  src/Fields/regridding_fields.jl
  src/Fields/set!.jl
  src/Forcings/continuous_forcing.jl
  src/Grids/Grids.jl
  src/Grids/grid_utils.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/nodes_and_spacings.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Grids/rectilinear_grid.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/Models/HydrostaticFreeSurfaceModels/fft_based_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/slice_ensemble_model_mode.jl
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Operators/Operators.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/Solvers/fourier_tridiagonal_poisson_solver.jl
  src/Solvers/plan_transforms.jl
  test/test_dynamics.jl
  test/test_ensemble_hydrostatic_free_surface_models.jl
  test/test_hydrostatic_regression.jl
  test/test_immersed_advection.jl
  test/test_internal_wave_dynamics.jl
  test/test_matrix_poisson_solver.jl
  test/test_nonhydrostatic_regression.jl
  test/test_shallow_water_models.jl
  test/test_time_stepping.jl
Labels: user interface/experience 💻
