Repository CliMA/Oceananigans.jl, pull requests merged in 2023-11, with the labels that each got.

#3371 Add compat entries for Stdlibs
  Manifest.toml
  Project.toml
Labels: package 📦

#3372 Add compat entry for Random
  Manifest.toml
  Project.toml
Labels: package 📦

#3339 Non uniform partitioning for `Distributed` architectures
  .buildkite/distributed/pipeline.yml
  src/DistributedComputations/DistributedComputations.jl
  src/DistributedComputations/distributed_architectures.jl
  src/DistributedComputations/distributed_grids.jl
  test/data_dependencies.jl
  test/utils_for_runtests.jl
Labels: distributed 🕸️

#3373 Update regression test data
  test/data_dependencies.jl
Labels: testing 🧪

#3378 (0.90.1) Bump to 0.90.1 to fix docs issue
  Project.toml
Labels: documentation 📜

#3380 Add OceanBioME.jl paper
  docs/src/index.md
Labels: documentation 📜

#3376 Default NaN-Checker for Particle Tracking models
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/Models/Models.jl
Labels: cleanup 🧹

#3391 Changes property "longname" to "long_name" for NetCDFOutputWriter
  src/OutputWriters/netcdf_output_writer.jl
  test/test_netcdf_output_writer.jl
Labels: output 💾

#3385 Tiny conversion of code to English
  src/OutputWriters/netcdf_output_writer.jl
Labels: cleanup 🧹

#3392 Correction of three-dimensional Stokes drift implementation
  examples/Spatially_varying_stokes_drift.jl
  src/StokesDrifts.jl
Labels: science 🌊
