Repository CliMA/Oceananigans.jl, pull requests merged in 2023-07, with the labels that each got.

#3164 Αdd CATKE paper in list of papers that used Oceananigans in the Docs
  docs/src/index.md
Labels: documentation 📜

#3168 More docs built optimization
  docs/make.jl
Labels: testing 🧪, documentation 📜

#3167 Restore netCDF output writer tests
  test/runtests.jl
Labels: testing 🧪, output 💾

#3170 Some simplifications in Docs/Simulations For GPUs
  docs/src/simulation_tips.md
Labels: GPU 👾, documentation 📜

#3100 Use julia v1.9
  .buildkite/pipeline.yml
  .buildkite/validation-pipeline.yml
  .github/workflows/CompatHelper.yml
  Dockerfile
  Manifest.toml
  docs/Manifest.toml
  docs/Project.toml
  docs/src/index.md
  src/MultiRegion/multi_region_grid.jl
  src/MultiRegion/x_partitions.jl
  src/Solvers/matrix_solver_utils.jl
  src/Utils/schedules.jl
Labels: package 📦

#3172 Minor cleanup
  src/OutputWriters/checkpointer.jl
  src/Simulations/run.jl
Labels: 🚲 bikeshedding

#3165 Dispatch `fractional_x/y/z_index` methods over various grid types
  src/Fields/interpolate.jl
  src/Grids/Grids.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Grids/rectilinear_grid.jl
Labels: cleanup 🧹

#3173 Add `update_biogeochemical_state!` to `update_state!` for hydrostatic free surface single column mode
  src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
Labels: bug 🐞, biogeochemistry 🦠

#3174 (0.84.1) Fixes string generator for `summary(::SpecifiedTimes)`
  Project.toml
  src/Utils/schedules.jl
Labels: bug 🐞

#3175 Upgrade to Julia v1.9.2
  .buildkite/pipeline.yml
  Dockerfile
  Manifest.toml
  docs/Manifest.toml
Labels: package 📦

#3179 Add tests for biogeochemistry on lat/lon grids
  src/Grids/orthogonal_spherical_shell_grid.jl
  test/test_biogeochemistry.jl
Labels: testing 🧪, biogeochemistry 🦠

#3180 Make shallow water Bickley jet less expensive
  examples/shallow_water_Bickley_jet.jl
Labels: documentation 📜

#3190 (0.86.0) Removes all support for <1.9 Julia versions
  Project.toml
  README.md
  docs/src/index.md
  src/Fields/field.jl
  src/Oceananigans.jl
Labels: bug 🐞, package 📦

#3186 Use latest Documenter + DocumenterCitations
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/oceananigans.bib
  docs/src/appendix/fractional_step.md
  docs/src/appendix/staggered_grid.md
  docs/src/assets/citations.css
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  docs/src/numerical_implementation/elliptic_solvers.md
  docs/src/numerical_implementation/large_eddy_simulation.md
  docs/src/numerical_implementation/spatial_operators.md
  docs/src/numerical_implementation/time_stepping.md
  docs/src/numerical_implementation/turbulence_closures.md
  docs/src/physics/buoyancy_and_equations_of_state.md
  docs/src/physics/coriolis_forces.md
  docs/src/physics/turbulence_closures.md
  paper/paper.bib
  src/Solvers/discrete_transforms.jl
  src/Solvers/index_permutations.jl
  src/TimeSteppers/runge_kutta_3.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
Labels: documentation 📜, package 📦
