Repository CliMA/Oceananigans.jl, pull requests merged in 2023-06, with the labels that each got.

#3124 Initialize `SplitExplicitFreeSurface` with a CFL condition
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl
  test/test_split_explicit_free_surface_solver.jl
  test/test_split_explicit_vertical_integrals.jl
Labels: user interface/experience 💻

#3131 Fix few bugs + improve docstring of `SplitExplicitFreeSurface`
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl
Labels: bug 🐞, documentation 📜

#3027 Fixes inconsistent advection from "different" velocities
  Project.toml
  docs/src/appendix/library.md
  src/Biogeochemistry.jl
  src/Grids/grid_utils.jl
  src/LagrangianParticleTracking/update_particle_properties.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/Models/LagrangianParticleTracking/LagrangianParticleTracking.jl
  src/Models/LagrangianParticleTracking/lagrangian_particle_advection.jl
  src/Models/LagrangianParticleTracking/update_lagrangian_particle_properties.jl
  src/Models/Models.jl
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl
  src/Models/ShallowWaterModels/ShallowWaterModels.jl
  src/Oceananigans.jl
  src/OutputWriters/fetch_output.jl
  src/OutputWriters/output_writer_utils.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/quasi_adams_bashforth_2.jl
  src/TimeSteppers/runge_kutta_3.jl
  src/Utils/Utils.jl
  src/Utils/sum_of_arrays.jl
  test/test_biogeochemistry.jl
  test/test_dynamics.jl
  test/test_field.jl
  test/test_lagrangian_particle_tracking.jl
  validation/lagrangian_particles/particles_in_convection.jl
Labels: numerics 🧮

#3127 Three dimensional difference operators
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/conditional_derivatives.jl
  src/ImmersedBoundaries/conditional_differences.jl
  src/Operators/Operators.jl
  src/Operators/derivative_operators.jl
  src/Operators/difference_operators.jl
  src/Operators/divergence_operators.jl
  src/Operators/vorticity_operators.jl
  test/test_operators.jl
Labels: cleanup 🧹, numerics 🧮, immersed boundaries ⛰️

#3133 Diffusivity docs
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/TurbulenceClosures/discrete_diffusion_function.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
Labels: documentation 📜

#2912 Fix error interpolating field on irregularly spaced grid
  Project.toml
  src/Fields/interpolate.jl
  src/Grids/Grids.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Grids/rectilinear_grid.jl
  test/test_field.jl
Labels: bug 🐞

#3135 Use multiple processes to execute `examples` in make.jl
  .buildkite/pipeline.yml
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/make_example.jl
  docs/src/contributing.md
  examples/baroclinic_adjustment.jl
  examples/convecting_plankton.jl
  examples/internal_wave.jl
  examples/kelvin_helmholtz_instability.jl
  examples/langmuir_turbulence.jl
  examples/ocean_wind_mixing_and_convection.jl
  examples/one_dimensional_diffusion.jl
  examples/tilted_bottom_boundary_layer.jl
  examples/two_dimensional_turbulence.jl
Labels: testing 🧪

#3150 Fix typos in Docs
  docs/src/physics/hydrostatic_free_surface_model.md
  docs/src/physics/nonhydrostatic_model.md
Labels: documentation 📜

#3151 More doc built optimizations -- run computationally expensive examples first
  docs/make.jl
Labels: testing 🧪, documentation 📜

#3155 Update dependencies
  Manifest.toml
  docs/Manifest.toml
Labels: package 📦

#3149 Create dependabot.yml
  .github/dependabot.yml
Labels: package 📦

#3091 (0.84.0) Improvement of vector invariant advection + various new implementations
  Project.toml
  src/Advection/Advection.jl
  src/Advection/centered_reconstruction.jl
  src/Advection/flat_advective_fluxes.jl
  src/Advection/multi_dimensional_reconstruction.jl
  src/Advection/reconstruction_coefficients.jl
  src/Advection/topologically_conditional_interpolation.jl
  src/Advection/upwind_biased_advective_fluxes.jl
  src/Advection/upwind_biased_reconstruction.jl
  src/Advection/vector_invariant_advection.jl
  src/Advection/vector_invariant_cross_upwinding.jl
  src/Advection/vector_invariant_self_upwinding.jl
  src/Advection/vector_invariant_upwinding.jl
  src/Advection/vector_invariant_velocity_upwinding.jl
  src/Advection/weno_interpolants.jl
  src/Advection/weno_reconstruction.jl
  src/Coriolis/hydrostatic_spherical_coriolis.jl
  src/Coriolis/no_rotation.jl
  src/ImmersedBoundaries/conditional_differences.jl
  src/ImmersedBoundaries/conditional_fluxes.jl
  src/Models/HydrostaticFreeSurfaceModels/calculate_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl
  src/MultiRegion/multi_region_models.jl
  src/Operators/derivative_operators.jl
  src/Operators/divergence_operators.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  test/test_immersed_advection.jl
  validation/advection/gaussian_bump_advection.jl
  validation/convergence_tests/src/TwoDimensionalBurgersAdvection.jl
  validation/convergence_tests/src/TwoDimensionalVortexAdvection.jl
Labels: numerics 🧮

#3153 (0.84.0) Fix `NetCDFOutputWriter` compression kwarg
  src/OutputWriters/netcdf_output_writer.jl
Labels: bug 🐞, output 💾

#3121 Bump compat entries for PencilFFTs and PencilArrays
  Manifest.toml
  Project.toml
Labels: package 📦, distributed 🕸️

#3161 Fix issue with GL/CairoMakie not being able to compile on Apple's M1/2 chips
  Manifest.toml
Labels: package 📦
