Repository CliMA/Oceananigans.jl, pull requests merged in 2023-04, with the labels that each got.

#3050 Remove swe regression + add warning in `ShallowWaterModel`
  .buildkite/pipeline.yml
  Project.toml
  src/Models/ShallowWaterModels/shallow_water_model.jl
  test/data_dependencies.jl
  test/regression_tests/shallow_water_bickley_jet_regression.jl
  test/runtests.jl
  test/test_shallow_water_regression.jl
Labels: models 🧫

#2979 `node(s)` return native coordinates for grids + `x/y/znode(s)` -> distances & `λ/φnode(s)` -> degrees
  Project.toml
  docs/src/model_setup/background_fields.md
  src/Advection/cell_advection_timescale.jl
  src/Coriolis/hydrostatic_spherical_coriolis.jl
  src/Grids/Grids.jl
  src/Grids/grid_utils.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Grids/rectilinear_grid.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/conditional_derivatives.jl
  src/ImmersedBoundaries/conditional_fluxes.jl
  src/ImmersedBoundaries/immersed_grid_metrics.jl
  src/MultiRegion/multi_region_field.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/TurbulenceClosures/turbulence_closure_diagnostics.jl
  test/test_field_reductions.jl
  test/test_grids.jl
  test/test_hydrostatic_free_surface_immersed_boundaries.jl
  test/test_multi_region_advection_diffusion.jl
  validation/advection/validate_one_dimensional_advection.jl
Labels: user interface/experience 💻

#3046 Avoid redefining `R_Earth` in the `Coriolis` module
  src/BuoyancyModels/BuoyancyModels.jl
  src/Coriolis/Coriolis.jl
  src/Grids/Grids.jl
  src/Grids/latitude_longitude_grid.jl
Labels: cleanup 🧹

#3044 Add `.sqlite` and `.nsys-rep` to `.gitignore`
  .gitignore
Labels: package 📦

#3033 Update LICENSE
  LICENSE
Labels: package 📦

#3037 Remove Tullio dependency; take #2
  Manifest.toml
  Project.toml
  src/AbstractOperations/AbstractOperations.jl
  src/Advection/cell_advection_timescale.jl
  src/CubedSpheres/CubedSpheres.jl
  src/Diagnostics/cfl.jl
  test/test_diagnostics.jl
Labels: cleanup 🧹

#3035 Updates `Docs/Buoyancy models and equation of state` + update SeawaterPolynomials to v0.3.2
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  docs/src/model_setup/clock.md
  src/AbstractOperations/conditional_operations.jl
Labels: documentation 📜

#3052 Remove AlgebraicMultigrid + AMGX deps
  Manifest.toml
  Project.toml
  benchmark/benchmark_implicit_surface_solvers.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/matrix_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/mg_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
  src/Solvers/Solvers.jl
  src/Solvers/heptadiagonal_iterative_solver.jl
  src/Solvers/multigrid_solver.jl
  src/Solvers/preconditioned_conjugate_gradient_solver.jl
  src/Solvers/sparse_preconditioners.jl
  test/runtests.jl
  test/test_hydrostatic_free_surface_immersed_boundaries_implicit_solve.jl
  test/test_implicit_free_surface_solver.jl
  test/test_multigrid_solver.jl
  validation/elliptic_solvers/doubly_bounded_poisson.jl
  validation/elliptic_solvers/triply_bounded_poisson.jl
Labels: GPU 👾

#2966 Update dependencies
  Manifest.toml
  docs/Manifest.toml
  src/AbstractOperations/conditional_operations.jl
Labels: package 📦

#3063 Better `ShallowWaterScalarDiffusivity` docs
  src/Models/ShallowWaterModels/shallow_water_diffusion_operators.jl
Labels: documentation 📜

#3057 Add diffusive and viscous flux methods for tuples
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
  src/TurbulenceClosures/closure_kernel_operators.jl
  src/TurbulenceClosures/closure_tuples.jl
  test/test_turbulence_closures.jl
Labels: turbulence closures 🎐

#3074 Use grids' native coordinates in continuous BCs
  src/BoundaryConditions/continuous_boundary_function.jl
Labels: grids 🗺️, boundary conditions 🏓

#3071 Fix `default_dimension_attributes` in NetCDFwriter to work with IBG
  src/OutputWriters/netcdf_output_writer.jl
Labels: output 💾, immersed boundaries ⛰️

#3077 Reduce memory fetch for ContinuousBoundaryFunction BCs
  src/BoundaryConditions/continuous_boundary_function.jl
Labels: performance 🏍️, boundary conditions 🏓

#3079 Fix bug in buoyancy implementation
  Project.toml
  src/BuoyancyModels/BuoyancyModels.jl
  src/BuoyancyModels/buoyancy_field.jl
  src/BuoyancyModels/buoyancy_tracer.jl
  src/BuoyancyModels/g_dot_b.jl
  src/BuoyancyModels/linear_equation_of_state.jl
  src/BuoyancyModels/no_buoyancy.jl
  src/BuoyancyModels/seawater_buoyancy.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl
  src/Models/NonhydrostaticModels/update_hydrostatic_pressure.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
Labels: bug 🐞, numerics 🧮

#3084 Better julia compat version message in Docs
  docs/src/index.md
Labels: documentation 📜

#3086 Double gyre
  docs/make.jl
  examples/double_gyre.jl
Labels: science 🌊, documentation 📜
