Repository CliMA/Oceananigans.jl, pull requests merged in 2024-10, with the labels that each got.

#3801 New Base.axes for AbstractField
  src/AbstractOperations/AbstractOperations.jl
  src/Fields/abstract_field.jl
  src/Fields/field.jl
Labels: performance 🏍️, abstractions 🎨

#3802 Enforce gauge condition in preconditioners for ConjugateGradientPoissonSolver
  src/BoundaryConditions/field_boundary_conditions.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
  src/Models/Models.jl
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Models/NonhydrostaticModels/solve_for_pressure.jl
  src/MultiRegion/multi_region_models.jl
  src/Solvers/Solvers.jl
  src/Solvers/conjugate_gradient_poisson_solver.jl
  src/Solvers/conjugate_gradient_solver.jl
  src/Solvers/fft_based_poisson_solver.jl
  src/Solvers/fourier_tridiagonal_poisson_solver.jl
  test/test_preconditioned_conjugate_gradient_solver.jl
Labels: numerics 🧮

#3805 Bring back support for closure tuples with CATKE
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/time_step_catke_equation.jl
  test/test_turbulence_closures.jl
  validation/vertical_mixing_closures/tupled_vertical_diffusion.jl
Labels: turbulence closures 🎐

#3823 Support AbstractOperations with MakieExtension
  ext/OceananigansMakieExt.jl
Labels: extensions 🧬

#3817 Implement interface for `set!` and use it to `set!` distributed fields better
  src/Architectures.jl
  src/DistributedComputations/DistributedComputations.jl
  src/DistributedComputations/distributed_fields.jl
  src/DistributedComputations/distributed_grids.jl
  src/DistributedComputations/partition_assemble.jl
  src/Fields/abstract_field.jl
  src/Fields/set!.jl
  src/ImmersedBoundaries/distributed_immersed_boundaries.jl
  src/MultiRegion/multi_region_grid.jl
  src/MultiRegion/x_partitions.jl
  src/MultiRegion/y_partitions.jl
  src/Oceananigans.jl
  test/regression_tests/hydrostatic_free_turbulence_regression_test.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/test_distributed_hydrostatic_model.jl
Labels: distributed 🕸️, user interface/experience 💻

#3666 Bug in NetCDF output for curvilinear immersed grids
  src/Grids/latitude_longitude_grid.jl
  src/Grids/rectilinear_grid.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/OutputWriters/netcdf_output_writer.jl
  test/test_netcdf_output_writer.jl
Labels: bug 🐞

#3832 Add ConformalMapping Type to OrthogonalSphericalShellGrid for Specialized Dispatch
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Operators/vorticity_operators.jl
Labels: cubed sphere 🧊🌎

#3824 Temporary support for OrthogonalSphericalShellGrid for MakieExt
  ext/OceananigansMakieExt.jl
Labels: extensions 🧬

#3861 Add papers using Oceananigans
  docs/src/index.md
Labels: documentation 📜

#3864 Add more advection scheme tests; fix order adapting with tracer-specific schemes; fix WENOVectorInvariant
  Project.toml
  src/Advection/flux_form_advection.jl
  src/Advection/vector_invariant_advection.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  test/test_hydrostatic_free_surface_models.jl
Labels: bug 🐞

#3325 Correct vorticity computation at the corners of cubed sphere panels
  src/Operators/vorticity_operators.jl
Labels: bug 🐞, cubed sphere 🧊🌎

#3868 More specific `ConformalCubedSpherePanel` type
  src/Grids/orthogonal_spherical_shell_grid.jl
Labels: cubed sphere 🧊🌎

#3869 Clean up redundant errors in `FieldTimeSeries`
  src/OutputReaders/field_time_series.jl
Labels: cleanup 🧹

#3860 (0.93.0) Use `with_halos=true` default for `JLD2OutputWriter`
  Project.toml
  docs/Project.toml
  docs/src/model_setup/lagrangian_particles.md
  docs/src/model_setup/output_writers.md
  examples/horizontal_convection.jl
  examples/internal_tide.jl
  examples/langmuir_turbulence.jl
  examples/two_dimensional_turbulence.jl
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/OutputWriters/windowed_time_average.jl
  test/test_jld2_output_writer.jl
Labels: output 💾

#3871 Fix bug calling domain for LatitudeLongitudeGrid
  Project.toml
  src/Grids/latitude_longitude_grid.jl
  test/test_grids.jl
Labels: bug 🐞

#3876 (0.93.2) Update Adapt.jl compat and fix `Float32` CATKE on GPU
  Project.toml
  src/Grids/grid_generation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_mixing_length.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/time_step_catke_equation.jl
  test/test_hydrostatic_free_surface_models.jl
Labels: bug 🐞, GPU 👾, turbulence closures 🎐
