Repository CliMA/Oceananigans.jl, pull requests merged in 2024-04, with the labels that each got.

#3528 Friendlier KH example for GPU
  examples/kelvin_helmholtz_instability.jl
Labels: GPU 👾, user interface/experience 💻

#3524 Add interpolation for fields on `ImmersedBoundaryGrid`s
  src/ImmersedBoundaries/ImmersedBoundaries.jl
Labels: immersed boundaries ⛰️

#3532 Add info about models that support BackgroundFields
  Manifest.toml
  docs/src/model_setup/background_fields.md
Labels: documentation 📜

#3535 Automatically try to reshape arrays when encountering DimensionMismatch
  src/Fields/set!.jl
Labels: user interface/experience 💻

#3488 Fill halos of conformal cubed sphere grid coordinates and metrics in a single pass
  src/AbstractOperations/conditional_operations.jl
  src/DistributedComputations/distributed_on_architecture.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/MultiRegion/MultiRegion.jl
  src/MultiRegion/cubed_sphere_boundary_conditions.jl
  src/MultiRegion/multi_region_cubed_sphere_grid.jl
  test/data_dependencies.jl
  test/dependencies_for_runtests.jl
  test/runtests.jl
  test/test_multi_region_cubed_sphere.jl
  validation/multi_region/multi_region_cubed_sphere.jl
  validation/multi_region/multi_region_cubed_sphere_grid.jl
Labels: grids 🗺️, cubed sphere 🧊🌎

#3540 Use adaptive timestep in two-dimensional turbulence example
  examples/two_dimensional_turbulence.jl
Labels: documentation 📜

#3541 Update climacommon to 2024_04_05
  .buildkite/distributed/pipeline.yml
Labels: testing 🧪

#3539 Fix examples in `ConformalCubedSphereGrid` docs and convert to doctests
  docs/make.jl
  src/MultiRegion/multi_region_cubed_sphere_grid.jl
Labels: documentation 📜, cubed sphere 🧊🌎

#3542 Show methods display information about the advection scheme(s)
  .buildkite/pipeline.yml
  docs/src/model_setup/boundary_conditions.md
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  docs/src/model_setup/lagrangian_particles.md
  docs/src/model_setup/tracers.md
  src/BuoyancyModels/buoyancy.jl
  src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl
  src/Models/NonhydrostaticModels/show_nonhydrostatic_model.jl
  src/Models/ShallowWaterModels/show_shallow_water_model.jl
  src/Models/seawater_density.jl
Labels: documentation 📜, user interface/experience 💻

#3514 (0.90.12) Bugfix for `SpitExplicitFreeSurface` on `MultiRegionGrid`s and make `SpitExplicitFreeSurface` the default + don't allow more halos than interior points
  Project.toml
  docs/src/model_setup/background_fields.md
  docs/src/model_setup/boundary_conditions.md
  docs/src/model_setup/output_writers.md
  src/AbstractOperations/binary_operations.jl
  src/AbstractOperations/conditional_operations.jl
  src/AbstractOperations/grid_metrics.jl
  src/AbstractOperations/kernel_function_operation.jl
  src/AbstractOperations/multiary_operations.jl
  src/AbstractOperations/unary_operations.jl
  src/BuoyancyModels/buoyancy.jl
  src/Fields/field.jl
  src/Grids/automatic_halo_sizing.jl
  src/Grids/input_validation.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Grids/rectilinear_grid.jl
  src/Models/HydrostaticFreeSurfaceModels/distributed_split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
  src/Models/HydrostaticFreeSurfaceModels/slice_ensemble_model_mode.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
  src/MultiRegion/cubed_sphere_connectivity.jl
  src/MultiRegion/multi_region_cubed_sphere_grid.jl
  src/MultiRegion/multi_region_grid.jl
  src/MultiRegion/multi_region_split_explicit_free_surface.jl
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/windowed_time_average.jl
  test/test_boundary_conditions_integration.jl
  test/test_dynamics.jl
  test/test_field.jl
  test/test_forcings.jl
  test/test_grids.jl
  test/test_hydrostatic_free_surface_immersed_boundaries.jl
  test/test_hydrostatic_free_surface_models.jl
  test/test_implicit_free_surface_solver.jl
  test/test_multi_region_advection_diffusion.jl
  test/test_nonhydrostatic_models.jl
  test/test_shallow_water_models.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
Labels: bug 🐞, distributed 🕸️

#3546 Add Whitley & Wenegrat 2024
  docs/src/index.md
Labels: documentation 📜

#3553 Update deps
  Manifest.toml
  test/data_dependencies.jl
  test/runtests.jl
  test/test_seawater_density.jl
  validation/immersed_boundaries/immersed_cubed_sphere_rossby_haurwitz.jl
  validation/multi_region/multi_region_cubed_sphere_grid.jl
  validation/multi_region/multi_region_near_global_quarter_degree.jl
  validation/shallow_water_model/make_animation.jl
  validation/shallow_water_model/near_global_shallow_water_quarter_degree.jl
Labels: package 📦

#3554 Fix typo in doc @ref in one_dimensional_diffusion.jl
  examples/one_dimensional_diffusion.jl
Labels: documentation 📜

#3550 Fix bug when using Lagrangian particles on Flat topologies
  src/Fields/interpolate.jl
  src/Models/LagrangianParticleTracking/LagrangianParticleTracking.jl
  src/Models/LagrangianParticleTracking/lagrangian_particle_advection.jl
  test/test_lagrangian_particle_tracking.jl
Labels: bug 🐞

#3548 Alignment and minor changes
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
Labels: documentation 📜, turbulence closures 🎐

#3549 Fix `interpolator` for left side of periodic domain
  Project.toml
  src/Fields/interpolate.jl
Labels: bug 🐞
