Repository CliMA/Oceananigans.jl, pull requests merged in 2024-05, with the labels that each got.

#3575 Allow creating a `ConformalCubedSphereGrid` on GPU
  src/Grids/orthogonal_spherical_shell_grid.jl
Labels: GPU 👾, cubed sphere 🧊🌎

#3578 Make the 3D stokes drift validation case even better
  validation/stokes_drift/surface_wave_quasi_geostrophic_flow.jl
Labels: validation scripts 💅🏼

#3591 Fix typo in callbacks example
  docs/src/model_setup/callbacks.md
Labels: documentation 📜

#3581 Enforce total buoyancy flux BC in tilted geometry example
  examples/tilted_bottom_boundary_layer.jl
Labels: documentation 📜

#3576 Passes `grid` argument to `NetCDFOutputWriter`
  docs/src/model_setup/output_writers.md
  src/Fields/interpolate.jl
  src/OutputWriters/netcdf_output_writer.jl
  test/test_output_writers.jl
Labels: output 💾

#3590 Implement `Scan`, generalizing `Reduction` to accumulating scans like `cumsum!`
  src/AbstractOperations/AbstractOperations.jl
  src/AbstractOperations/metric_field_reductions.jl
  src/Fields/Fields.jl
  src/Fields/field.jl
  src/Fields/field_reductions.jl
  src/Fields/scans.jl
  src/Oceananigans.jl
  test/runtests.jl
  test/test_field_scans.jl
Labels: abstractions 🎨

#3573 Bugfix for `parent_index_range`
  src/Fields/field.jl
  src/Grids/grid_utils.jl
  test/test_field.jl
Labels: bug 🐞

#3604 Remove `GKSwstype: "100"` from buildkite environment variables
  .buildkite/pipeline.yml
Labels: testing 🧪, package 📦
