Repository CliMA/Oceananigans.jl, pull requests merged in 2024-11, with the labels that each got.

#3907 Update examples to use new fluxes notation
  examples/langmuir_turbulence.jl
  examples/ocean_wind_mixing_and_convection.jl
  validation/vertical_mixing_closures/gpu_tkevd_ensemble.jl
  validation/vertical_mixing_closures/heterogeneous_windy_convection.jl
Labels: documentation 📜

#3866 Fix docs for `VectorInvariant` and `WENOVectorInvariant`
  .buildkite/pipeline.yml
  Dockerfile
  src/Advection/vector_invariant_advection.jl
Labels: documentation 📜

#3893 Use on_architecture more liberally with boundary conditions
  Project.toml
  src/BoundaryConditions/field_boundary_conditions.jl
  src/OutputReaders/field_time_series.jl
  src/OutputWriters/output_writer_utils.jl
  test/test_output_readers.jl
Labels: GPU 👾

#3880 Bugfix in distributed GPU tests and Distributed `set!`
  .buildkite/distributed/pipeline.yml
  .buildkite/pipeline.yml
  Project.toml
  src/Fields/set!.jl
  test/runtests.jl
  test/test_distributed_poisson_solvers.jl
  test/test_distributed_transpose.jl
  test/utils_for_runtests.jl
Labels: bug 🐞

#3906 Fix equation rendering in `boundary_conditions.md`
  docs/src/numerical_implementation/boundary_conditions.md
Labels: documentation 📜

#3841 `static_column_depth` interface and numerical bottom height in `AbstractGridFittedBottom`
  ext/OceananigansMakieExt.jl
  src/Grids/Grids.jl
  src/Grids/grid_utils.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/abstract_grid_fitted_boundary.jl
  src/ImmersedBoundaries/grid_fitted_bottom.jl
  src/ImmersedBoundaries/partial_cell_bottom.jl
  src/Models/HydrostaticFreeSurfaceModels/distributed_split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
  src/MultiRegion/multi_region_field.jl
  src/MultiRegion/multi_region_grid.jl
  src/MultiRegion/multi_region_split_explicit_free_surface.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_equation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_mixing_length.jl
  validation/vertical_mixing_closures/heterogeneous_windy_convection.jl
Labels: user interface/experience 💻

#3887 Correct error message in `validate_lat_lon_grid_args`
  src/Grids/latitude_longitude_grid.jl
Labels: user interface/experience 💻

#3872 (0.94.0) Refactor exported names
  Project.toml
  docs/src/model_setup/callbacks.md
  docs/src/operations.md
  examples/convecting_plankton.jl
  examples/internal_tide.jl
  examples/internal_wave.jl
  examples/kelvin_helmholtz_instability.jl
  examples/ocean_wind_mixing_and_convection.jl
  examples/tilted_bottom_boundary_layer.jl
  examples/two_dimensional_turbulence.jl
  src/AbstractOperations/AbstractOperations.jl
  src/AbstractOperations/at.jl
  src/Advection/vector_invariant_advection.jl
  src/Fields/Fields.jl
  src/Fields/abstract_field.jl
  src/MultiRegion/cubed_sphere_grid.jl
  src/MultiRegion/multi_region_grid.jl
  src/Oceananigans.jl
  src/Simulations/Simulations.jl
  src/Utils/kernel_launching.jl
  test/dependencies_for_runtests.jl
Labels: cleanup 🧹, user interface/experience 💻

#3908 Dont adapt Flat direction advection scheme plus better summary for FluxFormAdvection
  docs/src/model_setup/boundary_conditions.md
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  docs/src/model_setup/lagrangian_particles.md
  docs/src/model_setup/tracers.md
  src/Advection/adapt_advection_order.jl
  src/Advection/centered_reconstruction.jl
  src/Advection/flux_form_advection.jl
  src/Advection/upwind_biased_reconstruction.jl
  src/Advection/vector_invariant_advection.jl
  src/Advection/weno_reconstruction.jl
  src/BuoyancyModels/buoyancy.jl
  src/Models/seawater_density.jl
Labels: user interface/experience 💻

#3894 (0.94.1) Refactor `SplitExplicitFreeSurface`
  Project.toml
  docs/src/appendix/library.md
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/SplitExplicitFreeSurfaces.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/barotropic_split_explicit_corrector.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/compute_slow_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/distributed_split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/initialize_split_explicit_substepping.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/split_explicit_timesteppers.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/step_split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/barotropic_pressure_correction.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/distributed_split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_field_tuples.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/HydrostaticFreeSurfaceModels/nothing_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/MultiRegion/multi_region_models.jl
  src/MultiRegion/multi_region_split_explicit_free_surface.jl
  test/test_checkpointer.jl
  test/test_hydrostatic_regression.jl
  test/test_split_explicit_free_surface_solver.jl
  test/test_split_explicit_vertical_integrals.jl
Labels: cleanup 🧹

#3143 (0.94.0) Overhaul spacings functions to return `KernelFunctionOperation`s
  docs/src/fields.md
  docs/src/grids.md
  examples/ocean_wind_mixing_and_convection.jl
  examples/tilted_bottom_boundary_layer.jl
  ext/OceananigansMakieExt.jl
  src/AbstractOperations/grid_metrics.jl
  src/Fields/interpolate.jl
  src/Grids/Grids.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/nodes_and_spacings.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Grids/rectilinear_grid.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/immersed_boundary_grid.jl
  src/ImmersedBoundaries/immersed_boundary_interface.jl
  src/ImmersedBoundaries/immersed_boundary_nodes.jl
  src/ImmersedBoundaries/immersed_grid_metrics.jl
  src/ImmersedBoundaries/partial_cell_bottom.jl
  src/MultiRegion/multi_region_grid.jl
  src/Oceananigans.jl
  src/Operators/Operators.jl
  src/Operators/derivative_operators.jl
  src/Operators/interpolation_utils.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  test/test_grids.jl
  test/utils_for_runtests.jl
Labels: grids 🗺️, immersed boundaries ⛰️

#3924 Reduce parameter space for velocity tendency kernels
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/NonhydrostaticModels/compute_nonhydrostatic_tendencies.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl
  src/Models/ShallowWaterModels/compute_shallow_water_tendencies.jl
  src/Models/ShallowWaterModels/solution_and_tracer_tendencies.jl
Labels: GPU 👾

#3930 RK3 for the HydrostaticFreeSurfaceModel version 2
  docs/oceananigans.bib
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/SplitExplicitFreeSurfaces.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/compute_slow_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/initialize_split_explicit_substepping.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/split_explicit_timesteppers.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/step_split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_field_tuples.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_rk3_step.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/quasi_adams_bashforth_2.jl
  src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl
  test/test_hydrostatic_free_surface_immersed_boundaries_implicit_solve.jl
  test/test_implicit_free_surface_solver.jl
  test/test_split_explicit_vertical_integrals.jl
Labels: numerics 🧮
