Repository CliMA/Oceananigans.jl, pull requests merged in 2024-03, with the labels that each got.

#3493 Remove misleading comment
  src/Fields/field.jl
  test/test_distributed_hydrostatic_model.jl
Labels: cleanup 🧹

#3495 Use Julia v1.10.2 for CI
  .buildkite/pipeline.yml
  Dockerfile
  Manifest.toml
  docs/Manifest.toml
Labels: testing 🧪

#3132 Add internal tide example in Docs
  docs/make.jl
  examples/internal_tide.jl
Labels: documentation 📜

#3504 Show method for `HydrostaticFreeSurfaceModel` summarizes advection schemes
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl
Labels: user interface/experience 💻

#3487 (0.90.11) Tests for a distributed Immersed boundary grid + fix some `on_architecture` bugs
  Project.toml
  src/Fields/field.jl
  test/dependencies_for_runtests.jl
  test/test_distributed_hydrostatic_model.jl
Labels: testing 🧪

#3505 Enhance immersed boundary grid docs
  src/ImmersedBoundaries/grid_fitted_bottom.jl
  src/ImmersedBoundaries/grid_fitted_boundary.jl
  src/ImmersedBoundaries/immersed_boundary_condition.jl
Labels: documentation 📜, immersed boundaries ⛰️

#3512 File splitting in `NetCDFOutputWriter` when `max_filesize` is exceeded
  src/OutputWriters/netcdf_output_writer.jl
  test/test_netcdf_output_writer.jl
Labels: output 💾

#3503 Revisit `SplitExplicitFreeSurface` user-interface and Docs + use `SplitExplicitFreeSurface` as the default when appropriate
  examples/internal_tide.jl
  src/Grids/rectilinear_grid.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_vertically_integrated_variables.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_w_from_continuity.jl
  src/Models/HydrostaticFreeSurfaceModels/distributed_split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/fft_based_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_field_tuples.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/matrix_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/Models/HydrostaticFreeSurfaceModels/show_hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/split_explicit_free_surface_kernels.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/Models/Models.jl
  src/MultiRegion/multi_region_grid.jl
  src/MultiRegion/multi_region_split_explicit_free_surface.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  src/Solvers/fft_based_poisson_solver.jl
  test/test_distributed_hydrostatic_model.jl
  test/test_hydrostatic_regression.jl
  test/test_immersed_advection.jl
  test/test_implicit_free_surface_solver.jl
  test/test_split_explicit_free_surface_solver.jl
  test/test_split_explicit_vertical_integrals.jl
  validation/distributed_simulations/distributed_geostrophic_adjustment.jl
  validation/distributed_simulations/distributed_hydrostatic_turbulence.jl
  validation/field_time_series_boundary_conditions/seasonal_baroclinic_channel.jl
  validation/implicit_free_surface/geostrophic_adjustment_test.jl
Labels: documentation 📜, models 🧫, user interface/experience 💻

#3511 Allow testing of just a single file
  docs/src/contributing.md
  test/dependencies_for_runtests.jl
  test/runtests.jl
Labels: testing 🧪, documentation 📜

#3498 Add support for `AbstractArray` `Forcing`
  src/Forcings/forcing.jl
  src/Forcings/model_forcing.jl
  test/test_forcings.jl
Labels: user interface/experience 💻

#3517 Add Chen et al. 2024
  docs/src/index.md
Labels: documentation 📜

#3515 Generalize file splitting for output writers
  benchmark/benchmark_multi_GPU.jl
  docs/src/model_setup/output_writers.md
  src/Oceananigans.jl
  src/OutputWriters/OutputWriters.jl
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/OutputWriters/output_writer_utils.jl
  src/OutputWriters/windowed_time_average.jl
  test/test_jld2_output_writer.jl
  test/test_netcdf_output_writer.jl
  validation/barotropic_gyre/barotropic_gyre.jl
  validation/solid_body_rotation/solid_body_rotation.jl
  validation/solid_body_rotation/solid_body_tracer_advection.jl
Labels: feature 🌟, output 💾

#3094 PCG uses provided `grid`'s halo size instead of hardcoding `halo = (3, 3, 1)`
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
Labels: good first issue 🐤, cleanup 🧹

#3521 Don't ship docs with Manifest
  .buildkite/pipeline.yml
  .gitignore
  Manifest.toml
  Project.toml
  docs/Manifest.toml
  docs/Project.toml
  docs/make.jl
  docs/oceananigans.bib
  docs/src/contributing.md
  docs/src/model_setup/tracers.md
  src/AbstractOperations/conditional_operations.jl
Labels: documentation 📜, package 📦

#3499 Allow interpolation on `Distributed` architectures
  src/Fields/interpolate.jl
Labels: distributed 🕸️

#3496 Default partition in `Distributed`
  src/AbstractOperations/conditional_operations.jl
  src/DistributedComputations/distributed_architectures.jl
  src/DistributedComputations/distributed_on_architecture.jl
  src/DistributedComputations/partition_assemble.jl
  src/ImmersedBoundaries/grid_fitted_bottom.jl
  src/ImmersedBoundaries/mask_immersed_field.jl
  src/ImmersedBoundaries/partial_cell_bottom.jl
  src/TurbulenceClosures/implicit_explicit_time_discretization.jl
  src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/ri_based_vertical_diffusivity.jl
Labels: distributed 🕸️

#3523 Tests for splitting output files using `TimeInterval`
  src/OutputWriters/output_writer_utils.jl
  test/test_jld2_output_writer.jl
  test/test_netcdf_output_writer.jl
Labels: testing 🧪, output 💾
