Repository CliMA/Oceananigans.jl, pull requests merged in 2024-06, with the labels that each got.

#3610 Update deps
  Manifest.toml
Labels: package 📦

#3585 (0.91.1) CATKE numerics: discretely correct shear production, split-explicit TKE substepping
  Project.toml
  src/Grids/Grids.jl
  src/ImmersedBoundaries/active_cells_map.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_boundary_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/HydrostaticFreeSurfaceModels/store_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/Models/interleave_communication_and_computation.jl
  src/Oceananigans.jl
  src/OutputReaders/set_field_time_series.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/quasi_adams_bashforth_2.jl
  src/TimeSteppers/store_tendencies.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/mixing_length.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/time_step_turbulent_kinetic_energy.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/turbulent_kinetic_energy_equation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/ri_based_vertical_diffusivity.jl
  src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl
  test/test_turbulence_closures.jl
  validation/vertical_mixing_closures/column_windy_convection.jl
  validation/vertical_mixing_closures/compare_catke_results.jl
Labels: numerics 🧮

#3579 Speedup constructing a `ConformalCubedSphereGrid` on GPU
  src/Grids/latitude_longitude_grid.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/MultiRegion/MultiRegion.jl
  src/MultiRegion/cubed_sphere_grid.jl
Labels: GPU 👾, cubed sphere 🧊🌎

#3617 Compute third stage time-step for RK3 in a way that reduces the accumulation of error
  src/TimeSteppers/runge_kutta_3.jl
Labels: numerics 🧮

#3619 `Adapt`ing all fields of the `OrthogonalSphericalShellGrid`
  src/Grids/orthogonal_spherical_shell_grid.jl
Labels: GPU 👾, grids 🗺️

#3605 TKEDissipationVerticalDiffusivity (aka k-epsilon) turbulence closure (take 2)
  src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
  src/Models/HydrostaticFreeSurfaceModels/slice_ensemble_model_mode.jl
  src/Models/HydrostaticFreeSurfaceModels/store_hydrostatic_free_surface_tendencies.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/TKEBasedVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_equation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_mixing_length.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/time_step_catke_equation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/tke_dissipation_equations.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/tke_dissipation_stability_functions.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/tke_dissipation_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/tke_top_boundary_condition.jl
  src/TurbulenceClosures/turbulence_closure_implementations/ri_based_vertical_diffusivity.jl
  test/test_time_stepping.jl
  validation/vertical_mixing_closures/column_windy_convection.jl
  validation/vertical_mixing_closures/compare_catke_k_epsilon.jl
  validation/vertical_mixing_closures/k_epsilon_boundary_layer.jl
  validation/vertical_mixing_closures/look_at_stability_functions.jl
Labels: turbulence closures 🎐, parameterizations

#3633 (0.91.3) Bump
  Project.toml
Labels: package 📦

#3629 `fill_halo_regions!` for velocities in implicit free surface correctly
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
Labels: bug 🐞

#3556 Remove performance-/precompilation-time harmful `@eval`
  src/AbstractOperations/grid_metrics.jl
  src/Advection/reconstruction_coefficients.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/nodes_and_spacings.jl
  src/MultiRegion/cubed_sphere_grid.jl
  src/MultiRegion/multi_region_models.jl
  src/Operators/interpolation_utils.jl
  src/TimeSteppers/TimeSteppers.jl
Labels: performance 🏍️

#3641 Update list of papers using Oceananigans
  docs/src/index.md
Labels: documentation 📜

#3624 Make `Base.axes(f::Field)` type-inferable for windowed fields
  src/Fields/field.jl
Labels: performance 🏍️

#3636 Remove vestigial code
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/CATKEVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/CATKEVerticalDiffusivities/turbulent_kinetic_energy_equation.jl
Labels: cleanup 🧹
