Repository CliMA/Oceananigans.jl, pull requests merged in 2024-12, with the labels that each got.

#3955 Refactor of spacings and correction of spacings-connected bugs
  src/AbstractOperations/binary_operations.jl
  src/AbstractOperations/grid_metrics.jl
  src/BoundaryConditions/flat_extrapolation_open_boundary_matching_scheme.jl
  src/Grids/Grids.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/nodes_and_spacings.jl
  src/ImmersedBoundaries/immersed_boundary_nodes.jl
  src/ImmersedBoundaries/immersed_grid_metrics.jl
  src/ImmersedBoundaries/partial_cell_bottom.jl
  src/MultiRegion/multi_region_grid.jl
  src/Oceananigans.jl
  src/Operators/Operators.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  test/test_grids.jl
Labels: cleanup 🧹

#3965 Polar boundary conditions
  src/BoundaryConditions/BoundaryConditions.jl
  src/BoundaryConditions/field_boundary_conditions.jl
  src/BoundaryConditions/polar_boundary_condition.jl
  test/test_boundary_conditions.jl
Labels: boundary conditions 🏓

#3971 advective form of the GM skew diffusivity
  src/Biogeochemistry.jl
  src/Forcings/advective_forcing.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/Models/LagrangianParticleTracking/LagrangianParticleTracking.jl
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_tendency_kernel_functions.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
  src/TurbulenceClosures/turbulence_closure_implementations/advective_skew_diffusion.jl
  src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
  src/Utils/sum_of_arrays.jl
  test/test_time_stepping.jl
  validation/mesoscale_turbulence/immersed_corse_baroclinic_adjustment.jl
Labels: numerics 🧮, turbulence closures 🎐

#3974 (0.95.0) Refactor grids to allow generalized vertical coordinate
  Project.toml
  examples/langmuir_turbulence.jl
  src/AbstractOperations/grid_metrics.jl
  src/Advection/Advection.jl
  src/Advection/reconstruction_coefficients.jl
  src/DistributedComputations/distributed_grids.jl
  src/DistributedComputations/distributed_on_architecture.jl
  src/DistributedComputations/transposable_field.jl
  src/Fields/abstract_field.jl
  src/Forcings/forcing.jl
  src/Grids/Grids.jl
  src/Grids/abstract_grid.jl
  src/Grids/grid_generation.jl
  src/Grids/grid_utils.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/nodes_and_spacings.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Grids/rectilinear_grid.jl
  src/Grids/vertical_coordinate.jl
  src/ImmersedBoundaries/grid_fitted_bottom.jl
  src/ImmersedBoundaries/immersed_boundary_nodes.jl
  src/ImmersedBoundaries/immersed_grid_metrics.jl
  src/ImmersedBoundaries/partial_cell_bottom.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/MultiRegion/MultiRegion.jl
  src/MultiRegion/cubed_sphere_grid.jl
  src/MultiRegion/multi_region_grid.jl
  src/MultiRegion/unified_implicit_free_surface_solver.jl
  src/Oceananigans.jl
  src/Operators/Operators.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl
  test/test_diagnostics.jl
  test/test_distributed_models.jl
  test/test_distributed_poisson_solvers.jl
  test/test_dynamics.jl
  test/test_ensemble_hydrostatic_free_surface_models.jl
  test/test_grids.jl
  test/test_hydrostatic_regression.jl
  test/test_jld2_output_writer.jl
  test/test_lagrangian_particle_tracking.jl
  test/test_netcdf_output_writer.jl
  test/test_split_explicit_vertical_integrals.jl
  validation/stratified_couette_flow/stratified_couette_flow.jl
Labels: grids 🗺️

#3969 Some corrections in the timestepper constructors
  src/Fields/Fields.jl
  src/Fields/field_tuples.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_field_tuples.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/Models/HydrostaticFreeSurfaceModels/single_column_model_mode.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Models/ShallowWaterModels/shallow_water_model.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/quasi_adams_bashforth_2.jl
  src/TimeSteppers/runge_kutta_3.jl
  src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl
Labels: cleanup 🧹

#3991 Update the docstring for `HydrostaticFreeSurfaceModel`
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
Labels: documentation 📜

#3937 (0.95.3) Restores open boundary condition functionality
  Project.toml
  src/BoundaryConditions/fill_halo_regions.jl
  src/BoundaryConditions/fill_halo_regions_open.jl
  src/BoundaryConditions/flat_extrapolation_open_boundary_matching_scheme.jl
  test/test_boundary_conditions_integration.jl
Labels: bug 🐞, testing 🧪, boundary conditions 🏓

#4023 Minor enhancement in OceananigansMakieExt
  ext/OceananigansMakieExt.jl
Labels: extensions 🧬

#4022 Add info for Julia version used for testing
  docs/src/index.md
Labels: documentation 📜

#4026 Enzyme: mark prettytime as non-differentiable
  ext/OceananigansEnzymeExt.jl
Labels: extensions 🧬

#4025 Makie extension: tweaks the xticks for domains that wraps around the globe
  ext/OceananigansMakieExt.jl
Labels: extensions 🧬
