Repository CliMA/Oceananigans.jl, pull requests merged in 2024-09, with the labels that each got.

#3767 (0.91.13) Use SeawaterPolynomials 0.3.5
  Manifest.toml
  Project.toml
  src/Models/seawater_density.jl
Labels: package 📦

#3766 Fix FieldTimeSeries interpolation for single column grids with x, y locations
  src/Fields/interpolate.jl
  src/Grids/grid_generation.jl
  src/Grids/grid_utils.jl
  src/Grids/rectilinear_grid.jl
  src/OutputReaders/field_time_series_indexing.jl
  src/Utils/schedules.jl
  test/test_output_readers.jl
Labels: bug 🐞

#3754 Supporting indexing a `FieldDataset` with a `Symbol`
  src/OutputReaders/field_dataset.jl
  test/test_output_readers.jl
Labels: user interface/experience 💻

#3188 Add `ImmersedPressureSolver` with `FFTBasedPoissonSolver` as preconditioner for complex domains
  src/Grids/Grids.jl
  src/Grids/abstract_grid.jl
  src/Grids/grid_utils.jl
  src/Models/NonhydrostaticModels/NonhydrostaticModels.jl
  src/Models/NonhydrostaticModels/conjugate_gradient_poisson_solver.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Solvers/fft_based_poisson_solver.jl
  src/Solvers/preconditioned_conjugate_gradient_solver.jl
  validation/biogeochemistry/simple_plankton_continuous_form_biogeochemistry.jl
  validation/immersed_boundaries/2D_rough_rayleighbenard.jl
  validation/immersed_boundaries/nonlinear_topography.jl
Labels: numerics 🧮, immersed boundaries ⛰️

#3682 Fix a bug in the adapt of `PartialCellBottom`
  examples/internal_tide.jl
  src/ImmersedBoundaries/abstract_grid_fitted_boundary.jl
  src/ImmersedBoundaries/grid_fitted_bottom.jl
  src/ImmersedBoundaries/partial_cell_bottom.jl
  test/test_immersed_boundary_grid.jl
Labels: bug 🐞, GPU 👾

#3797 Remove vestigial `immersed_boundary` from `NonhydrostaticModel`
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
Labels: cleanup 🧹

#3796 Change default `hydrostatic_pressure_anomaly` to `CenterField(grid)` in `NonhydrostaticModel`
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
Labels: bug 🐞, numerics 🧮

#3580 (0.92.0) Make RungeKutta3 the default time-stepper for NonhydrostaticModel
  .buildkite/pipeline.yml
  Project.toml
  docs/src/model_setup/boundary_conditions.md
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  docs/src/model_setup/lagrangian_particles.md
  docs/src/model_setup/tracers.md
  docs/src/simulation_tips.md
  src/BuoyancyModels/buoyancy.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/Models/seawater_density.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/test_boundary_conditions_integration.jl
  test/test_forcings.jl
  test/test_netcdf_output_writer.jl
  test/test_simulations.jl
  test/test_time_stepping.jl
  test/test_turbulence_closures.jl
Labels: user interface/experience 💻

#3799 Enzyme (performance) mark some functions as non-differentiable
  ext/OceananigansEnzymeExt.jl
Labels: extensions 🧬
