Repository CliMA/Oceananigans.jl, pull requests merged in 2024-08, with the labels that each got.

#3416 Fix index calculation for Lagrangian particles in periodic directions
  src/Models/LagrangianParticleTracking/lagrangian_particle_advection.jl
Labels: bug 🐞

#3674 Update `time_step!` docstring for AB2
  docs/src/model_setup/output_writers.md
  src/TimeSteppers/quasi_adams_bashforth_2.jl
Labels: documentation 📜

#3652 Add Downloads badges on README.md
  README.md
Labels: documentation 📜, package 📦

#3671 Update number_type.md
  docs/src/model_setup/number_type.md
Labels: documentation 📜

#3678 Eliminate extra docstrings for FunctionField
  src/Fields/function_field.jl
Labels: documentation 📜

#3279 (0.91.6) Distributed FFTs using Oceananigans' inhouse DiscreteTransforms
  .buildkite/distributed/pipeline.yml
  .buildkite/pipeline.yml
  Dockerfile
  Manifest.toml
  Project.toml
  src/AbstractOperations/conditional_operations.jl
  src/Advection/vector_invariant_advection.jl
  src/DistributedComputations/DistributedComputations.jl
  src/DistributedComputations/distributed_architectures.jl
  src/DistributedComputations/distributed_fft_based_poisson_solver.jl
  src/DistributedComputations/distributed_fields.jl
  src/DistributedComputations/distributed_grids.jl
  src/DistributedComputations/distributed_transpose.jl
  src/DistributedComputations/halo_communication_bcs.jl
  src/DistributedComputations/partition_assemble.jl
  src/DistributedComputations/plan_distributed_transforms.jl
  src/DistributedComputations/transposable_field.jl
  src/Models/NonhydrostaticModels/solve_for_pressure.jl
  src/MultiRegion/multi_region_abstract_operations.jl
  src/MultiRegion/multi_region_field.jl
  src/MultiRegion/multi_region_grid.jl
  src/OutputReaders/set_field_time_series.jl
  src/Solvers/discrete_transforms.jl
  src/Solvers/fourier_tridiagonal_poisson_solver.jl
  src/Solvers/plan_transforms.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/runtests.jl
  test/test_distributed_models.jl
  test/test_distributed_poisson_solvers.jl
  test/test_distributed_transpose.jl
  test/test_nonhydrostatic_regression.jl
  test/utils_for_runtests.jl
  validation/distributed_simulations/distributed_geostrophic_adjustment.jl
  validation/distributed_simulations/distributed_nonhydrostatic_turbulence.jl
  validation/distributed_simulations/distributed_scaling/distributed_hydrostatic_simulation.jl
  validation/distributed_simulations/distributed_scaling/distributed_nonhydrostatic_simulation.jl
  validation/distributed_simulations/distributed_scaling/job_script.sh
  validation/distributed_simulations/distributed_scaling/run_tests.sh
Labels: distributed 🕸️

#3686 Implement Makie extension
  Project.toml
  docs/make.jl
  examples/baroclinic_adjustment.jl
  examples/convecting_plankton.jl
  examples/horizontal_convection.jl
  examples/internal_wave.jl
  examples/one_dimensional_diffusion.jl
  examples/two_dimensional_turbulence.jl
  ext/OceananigansMakieExt.jl
Labels: extensions 🧬

#3482 (0.91.7) Open boundary conditions for `NonhydrostaticModel`
  Project.toml
  docs/src/model_setup/boundary_conditions.md
  docs/src/numerical_implementation/boundary_conditions.md
  docs/src/numerical_implementation/finite_volume.md
  src/BoundaryConditions/BoundaryConditions.jl
  src/BoundaryConditions/boundary_condition.jl
  src/BoundaryConditions/boundary_condition_classifications.jl
  src/BoundaryConditions/continuous_boundary_function.jl
  src/BoundaryConditions/field_boundary_conditions.jl
  src/BoundaryConditions/fill_halo_regions.jl
  src/BoundaryConditions/fill_halo_regions_open.jl
  src/BoundaryConditions/flat_extrapolation_open_boundary_matching_scheme.jl
  src/BoundaryConditions/show_boundary_conditions.jl
  src/BoundaryConditions/update_boundary_conditions.jl
  src/DistributedComputations/halo_communication.jl
  src/Fields/field.jl
  src/ImmersedBoundaries/immersed_boundary_condition.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/Models/NonhydrostaticModels/set_nonhydrostatic_model.jl
  src/Models/NonhydrostaticModels/update_nonhydrostatic_model_state.jl
  src/MultiRegion/multi_region_boundary_conditions.jl
  src/Oceananigans.jl
  src/TimeSteppers/quasi_adams_bashforth_2.jl
  src/TimeSteppers/runge_kutta_3.jl
  test/dependencies_for_poisson_solvers.jl
  test/regression_tests/ocean_large_eddy_simulation_regression_test.jl
  test/regression_tests/rayleigh_benard_regression_test.jl
  test/test_boundary_conditions.jl
  test/test_boundary_conditions_integration.jl
  test/test_time_stepping.jl
  test/utils_for_runtests.jl
  validation/open_boundaries/cylinder.jl
  validation/open_boundaries/oscillating_flow.jl
Labels: boundary conditions 🏓

#3688 Add constructor for windowing `nothing` boundary conditions
  docs/make.jl
  src/BoundaryConditions/field_boundary_conditions.jl
  src/Fields/field.jl
  src/Grids/grid_utils.jl
  src/Grids/input_validation.jl
  src/Grids/new_data.jl
Labels: bug 🐞

#3673 The start of documentation 2.0
  .buildkite/pipeline.yml
  CONTRIBUTING.md
  docs/Project.toml
  docs/make.jl
  docs/src/contributing.md
  docs/src/field_time_series.md
  docs/src/fields.md
  docs/src/grids.md
  docs/src/model_setup/forcing_functions.md
  docs/src/model_setup/legacy_grids.md
  docs/src/model_setup/output_writers.md
  docs/src/model_setup/turbulent_diffusivity_closures_and_les_models.md
  docs/src/operations.md
  docs/src/physics/hydrostatic_free_surface_model.md
  docs/src/physics/nonhydrostatic_model.md
  docs/src/physics/turbulence_closures.md
  docs/src/quick_start.md
  docs/src/simulation_tips.md
  docs/src/simulations.md
  examples/horizontal_convection.jl
  examples/internal_wave.jl
  src/AbstractOperations/conditional_operations.jl
  src/DistributedComputations/distributed_architectures.jl
  src/Grids/rectilinear_grid.jl
  src/ImmersedBoundaries/grid_fitted_boundary.jl
  src/Oceananigans.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/Simulations/simulation.jl
Labels: documentation 📜

#3697 Make shading better in baroclinic_adjustment.jl
  Manifest.toml
  examples/baroclinic_adjustment.jl
Labels: documentation 📜

#3700 Leverage Makie extension in quick start
  docs/src/quick_start.md
  src/AbstractOperations/conditional_operations.jl
Labels: documentation 📜

#3706 Add Chor & Wenegrat (2024) in papers using package list
  docs/src/index.md
Labels: documentation 📜

#3685 Fixs fallback for `AbstractContinuousFormBiogeochemistry`
  src/Biogeochemistry.jl
Labels: bug 🐞

#3713 Use the word "grid" in the grid tutorial
  docs/src/grids.md
Labels: documentation 📜

#3715 Add extension feature for plotting fields when nodes are provided
  ext/OceananigansMakieExt.jl
Labels: extensions 🧬

#3620 Make it easier to build simple HydrostaticFreeSurfaceModels
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  src/BuoyancyModels/buoyancy.jl
  src/Fields/Fields.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/Models/HydrostaticFreeSurfaceModels/set_hydrostatic_free_surface_model.jl
  test/test_hydrostatic_free_surface_models.jl
Labels: user interface/experience 💻

#3724 Make the quickstart a bit more fun
  docs/make.jl
  docs/src/quick_start.md
Labels: documentation 📜

#3730 Nullify preferred axis for field arg
  Manifest.toml
  Project.toml
  ext/OceananigansMakieExt.jl
Labels: extensions 🧬

#3733 Bugfix for #3731
  Project.toml
  docs/src/model_setup/output_writers.md
  src/OutputReaders/field_time_series_indexing.jl
  src/OutputWriters/windowed_time_average.jl
  test/test_output_readers.jl
Labels: bug 🐞
