Repository CliMA/Oceananigans.jl, pull requests merged in 2025-03, with the labels that each got.

#4150 New reactant feature: sharding + avoid direct usage of `RArray`
  Project.toml
  ext/OceananigansReactantExt/Architectures.jl
  src/Architectures.jl
  test/test_reactant.jl
Labels: extensions 🧬

#4153 Update spatial_operators.md
  docs/src/numerical_implementation/spatial_operators.md
Labels: documentation 📜

#4140 Clean up immersed boundary interface
  ext/OceananigansReactantExt/Grids.jl
  src/DistributedComputations/distributed_immersed_boundaries.jl
  src/ImmersedBoundaries/active_cells_map.jl
  src/ImmersedBoundaries/grid_fitted_bottom.jl
  src/ImmersedBoundaries/grid_fitted_boundary.jl
  src/ImmersedBoundaries/immersed_boundary_grid.jl
  src/ImmersedBoundaries/partial_cell_bottom.jl
  test/test_active_cells_map.jl
  test/test_distributed_hydrostatic_model.jl
Labels: cleanup 🧹

#4185 Add non-trivial default boundary conditions for `FieldTimeSeries`
  src/OutputReaders/field_time_series.jl
  test/test_output_readers.jl
Labels: output 💾

#3913 Tripolar grid in Oceananigans (only serial)
  .buildkite/pipeline.yml
  docs/src/appendix/library.md
  docs/src/grids.md
  src/BoundaryConditions/BoundaryConditions.jl
  src/BoundaryConditions/apply_flux_bcs.jl
  src/BoundaryConditions/boundary_condition.jl
  src/BoundaryConditions/boundary_condition_classifications.jl
  src/BoundaryConditions/fill_halo_regions_zipper.jl
  src/BoundaryConditions/show_boundary_conditions.jl
  src/Fields/field.jl
  src/Oceananigans.jl
  src/OrthogonalSphericalShellGrids/OrthogonalSphericalShellGrids.jl
  src/OrthogonalSphericalShellGrids/generate_tripolar_coordinates.jl
  src/OrthogonalSphericalShellGrids/tripolar_field_extensions.jl
  src/OrthogonalSphericalShellGrids/tripolar_grid.jl
  test/runtests.jl
  test/test_tripolar_grid.jl
Labels: grids 🗺️

#4139 Tests on tartarus
  .buildkite/pipeline.yml
  Project.toml
  test/test_computed_field.jl
Labels: testing 🧪

#4222 Use correct eltype on abstractarray override
  ext/OceananigansReactantExt/OceananigansReactantExt.jl
Labels: extensions 🧬

#4046 (0.96.0) Improve the `NetCDFOutputWriter` experience
  Project.toml
  docs/src/model_setup/lagrangian_particles.md
  docs/src/model_setup/output_writers.md
  examples/shallow_water_Bickley_jet.jl
  examples/tilted_bottom_boundary_layer.jl
  src/Grids/grid_utils.jl
  src/OutputWriters/fetch_output.jl
  src/OutputWriters/netcdf_output_writer.jl
  src/OutputWriters/output_construction.jl
  test/test_lagrangian_particle_tracking.jl
  test/test_netcdf_output_writer.jl
Labels: output 💾

#4240 Add Johnston et al. 2025
  docs/src/index.md
Labels: documentation 📜

#4235 Add section in the docs for reduced operations
  docs/src/operations.md
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/split_explicit_timesteppers.jl
Labels: documentation 📜

#4242 Reactant: add make_tracer for grid
  ext/OceananigansReactantExt/OceananigansReactantExt.jl
  src/Grids/inactive_node.jl
  src/Grids/vertical_discretization.jl
  src/ImmersedBoundaries/grid_fitted_bottom.jl
  src/ImmersedBoundaries/immersed_boundary_interface.jl
  src/ImmersedBoundaries/immersed_reductions.jl
  src/Operators/spacings_and_areas_and_volumes.jl
Labels: grids 🗺️, extensions 🧬

#4272 Sharding for LatitudeLongitudeGrid and extend Distributed methods for `Distributed{<:ReactantState}`
  .github/workflows/ci.yml
  .gitignore
  Project.toml
  ext/OceananigansReactantExt/Architectures.jl
  ext/OceananigansReactantExt/Fields.jl
  ext/OceananigansReactantExt/Grids.jl
  ext/OceananigansReactantExt/Grids/Grids.jl
  ext/OceananigansReactantExt/Grids/serial_grids.jl
  ext/OceananigansReactantExt/Grids/sharded_grids.jl
  ext/OceananigansReactantExt/OceananigansReactantExt.jl
  ext/OceananigansReactantExt/ShardedGrids.jl
  src/DistributedComputations/distributed_architectures.jl
  src/DistributedComputations/distributed_fields.jl
  src/DistributedComputations/distributed_immersed_boundaries.jl
  src/DistributedComputations/partition_assemble.jl
  test/dependencies_for_runtests.jl
  test/distributed_tests_utils.jl
  test/regression_tests/thermal_bubble_regression_test.jl
  test/runtests.jl
  test/test_distributed_models.jl
  test/test_mpi_tripolar.jl
  test/test_reactant_distributed_tripolar.jl
  test/test_sharded_lat_lon.jl
  test/test_sharded_tripolar.jl
Labels: extensions 🧬

#4266 Add validation for `condition` kwarg in `ConditionalOperation`
  src/AbstractOperations/conditional_operations.jl
Labels: user interface/experience 💻

#4280 Export spacings operators near where they are defined
  src/Operators/Operators.jl
  src/Operators/derivative_operators.jl
  src/Operators/spacings_and_areas_and_volumes.jl
Labels: feature 🌟, user interface/experience 💻

#4281 Reinstate sharding tests
  .github/workflows/ci.yml
  Project.toml
  test/dependencies_for_runtests.jl
  test/test_distributed_latitude_longitude.jl
  test/test_init.jl
  test/test_sharded_tripolar.jl
Labels: testing 🧪, extensions 🧬

#4297 Replaces greek capital N with latin N in variable names...
  src/Grids/orthogonal_spherical_shell_grid.jl
Labels: grids 🗺️

#4315 Fix broken doctests
  docs/Project.toml
  docs/src/model_setup/buoyancy_and_equation_of_state.md
  src/BuoyancyFormulations/seawater_buoyancy.jl
  src/Models/seawater_density.jl
Labels: testing 🧪, documentation 📜
