Repository CliMA/Oceananigans.jl, pull requests merged in 2025-06, with the labels that each got.

#4531 Call `compute!` in constructor for `ComputedField`
  docs/oceananigans.bib
  docs/src/operations.md
  docs/src/quick_start.md
  examples/horizontal_convection.jl
  examples/shallow_water_Bickley_jet.jl
  src/AbstractOperations/computed_field.jl
  src/Fields/scans.jl
  src/Models/seawater_density.jl
  src/OutputWriters/output_construction.jl
  test/test_field_scans.jl
Labels: user interface/experience 💻

#4571 Export SplitRungeKutta3TimeStepper a few docstring fixes (typos and rendering)
  src/Grids/grid_utils.jl
  src/Simulations/callback.jl
  src/Simulations/simulation.jl
  src/TimeSteppers/TimeSteppers.jl
  src/TimeSteppers/clock.jl
  src/TimeSteppers/quasi_adams_bashforth_2.jl
  src/TimeSteppers/runge_kutta_3.jl
  src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
  src/Utils/kernel_launching.jl
Labels: documentation 📜

#4569 Use Makie extension in Kelvin-Helmholtz example
  examples/kelvin_helmholtz_instability.jl
  src/Models/VarianceDissipationComputations/VarianceDissipationComputations.jl
Labels: documentation 📜

#4554 fix mean pressure in FFT preconditioner for `ConjugateGradientPoissonSolver` for immersed boundaries
  src/Solvers/conjugate_gradient_poisson_solver.jl
  src/Solvers/conjugate_gradient_solver.jl
  test/dependencies_for_poisson_solvers.jl
  test/runtests.jl
  test/test_poisson_solvers_immersed_boundaries.jl
  validation/immersed_boundaries/vortex_sheet.jl
Labels: numerics 🧮

#4090 Fix GPU indexing flat fields
  docs/src/fields.md
  src/Fields/abstract_field.jl
  test/test_field.jl
Labels: GPU 👾

#4617 Replaces duplicate `κᶜᶜᶜ` with `κᶠᶠᶠ`
  src/TurbulenceClosures/abstract_scalar_diffusivity_closure.jl
Labels: turbulence closures 🎐
