Repository CliMA/Oceananigans.jl, pull requests merged in 2025-01, with the labels that each got.

#4037 (0.95.6) Pin GPUArrays version + fix GPU testing pipeline
  .buildkite/pipeline.yml
  Project.toml
Labels: GPU 👾, testing 🧪, package 📦

#4045 Add compat entries for Makie 0.22 and MakieCore 0.9
  Project.toml
Labels: extensions 🧬

#3956 (0.95.7) Yet another ZStar implementation
  .buildkite/pipeline.yml
  Project.toml
  src/Advection/Advection.jl
  src/Advection/vector_invariant_advection.jl
  src/Advection/vector_invariant_cross_upwinding.jl
  src/Advection/vector_invariant_self_upwinding.jl
  src/Grids/Grids.jl
  src/Grids/grid_generation.jl
  src/Grids/grid_utils.jl
  src/Grids/vertical_coordinates.jl
  src/Grids/vertical_discretization.jl
  src/ImmersedBoundaries/ImmersedBoundaries.jl
  src/ImmersedBoundaries/immersed_grid_metrics.jl
  src/ImmersedBoundaries/mutable_immersed_grid.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/SplitExplicitFreeSurfaces.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/barotropic_split_explicit_corrector.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/initialize_split_explicit_substepping.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/split_explicit_timesteppers.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/step_split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_w_from_continuity.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_ab2_step.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_tendency_kernel_functions.jl
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/Models/HydrostaticFreeSurfaceModels/update_hydrostatic_free_surface_model_state.jl
  src/Models/HydrostaticFreeSurfaceModels/z_star_vertical_spacing.jl
  src/Models/Models.jl
  src/Operators/Operators.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  src/Operators/time_variable_grid_operators.jl
  src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl
  test/runtests.jl
  test/test_active_cells_map.jl
  test/test_split_explicit_vertical_integrals.jl
  test/test_zstar_coordinate.jl
  validation/z_star_coordinate/lock_release.jl
Labels: feature 🌟

#4058 Bugfix for advection on distributed topologies
  src/Advection/topologically_conditional_interpolation.jl
  src/DistributedComputations/distributed_immersed_boundaries.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_buffers.jl
  src/Models/NonhydrostaticModels/update_nonhydrostatic_model_state.jl
  test/test_distributed_hydrostatic_model.jl
  test/utils_for_runtests.jl
Labels: bug 🐞, distributed 🕸️
