Repository CliMA/Oceananigans.jl, pull requests merged in 2025-02, with the labels that each got.

#4079 Fix Prandtl definition
  examples/horizontal_convection.jl
Labels: documentation 📜

#2320 `Field` Stokes shear and tendency with `UniformStokesDrift`
  src/StokesDrifts.jl
  test/test_stokes_drift.jl
  test/test_time_stepping.jl
Labels: feature 🌟

#4072 Change default output type to Float32
  src/OutputWriters/jld2_output_writer.jl
  src/OutputWriters/netcdf_output_writer.jl
  test/test_jld2_output_writer.jl
  test/test_netcdf_output_writer.jl
Labels: output 💾

#4075 Improves `DynamicCoefficient` docstring with discussion about `schedule`
  src/TurbulenceClosures/turbulence_closure_implementations/Smagorinskys/dynamic_coefficient.jl
Labels: documentation 📜

#4081 Bump the compat on GPUArrays to 11.2.2
  Project.toml
Labels: GPU 👾, package 📦

#4073 Implement a default float type
  Project.toml
  src/Advection/Advection.jl
  src/Advection/centered_reconstruction.jl
  src/Advection/upwind_biased_reconstruction.jl
  src/Advection/vector_invariant_advection.jl
  src/Advection/weno_interpolants.jl
  src/Advection/weno_reconstruction.jl
  src/BuoyancyFormulations/BuoyancyFormulations.jl
  src/BuoyancyFormulations/linear_equation_of_state.jl
  src/BuoyancyFormulations/seawater_buoyancy.jl
  src/Coriolis/Coriolis.jl
  src/Coriolis/beta_plane.jl
  src/Coriolis/constant_cartesian_coriolis.jl
  src/Coriolis/f_plane.jl
  src/Coriolis/hydrostatic_spherical_coriolis.jl
  src/Coriolis/non_traditional_beta_plane.jl
  src/DistributedComputations/DistributedComputations.jl
  src/DistributedComputations/distributed_grids.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/orthogonal_spherical_shell_grid.jl
  src/Grids/rectilinear_grid.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/split_explicit_free_surface.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
  src/MultiRegion/cubed_sphere_grid.jl
  src/Oceananigans.jl
  src/Simulations/Simulations.jl
  src/Simulations/time_step_wizard.jl
  src/TurbulenceClosures/turbulence_closure_implementations/Smagorinskys/Smagorinskys.jl
  src/TurbulenceClosures/turbulence_closure_implementations/Smagorinskys/dynamic_coefficient.jl
  src/TurbulenceClosures/turbulence_closure_implementations/Smagorinskys/lilly_coefficient.jl
  src/TurbulenceClosures/turbulence_closure_implementations/Smagorinskys/smagorinsky.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/TKEBasedVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/tke_dissipation_stability_functions.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/tke_dissipation_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/anisotropic_minimum_dissipation.jl
  src/TurbulenceClosures/turbulence_closure_implementations/convective_adjustment_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/leith_enstrophy_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/ri_based_vertical_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_biharmonic_diffusivity.jl
  src/TurbulenceClosures/turbulence_closure_implementations/scalar_diffusivity.jl
  test/test_coriolis.jl
  test/test_grids.jl
  validation/float_precision_tests/hydrostatic_two_dimensional_turbulence.jl
  validation/float_precision_tests/two_dimensional_turbulence.jl
Labels: user interface/experience 💻

#4082 Add a few more Reactant unit tests + test Reactant extension via github actions
  .github/workflows/ci.yml
  Project.toml
  ext/OceananigansReactantExt/OceananigansReactantExt.jl
  src/Fields/field.jl
  test/runtests.jl
  test/test_reactant.jl
Labels: testing 🧪, extensions 🧬

#4092 Add Fan et al. (2024) and Bhadouriya et al. (2025) in papers list + brings back Download badges
  README.md
  docs/src/index.md
Labels: documentation 📜

#4093 Make the `OceananigansReactantExt` depend explicitly on KA
  .buildkite/distributed/pipeline.yml
  Project.toml
Labels: extensions 🧬

#4109 Add warning for Julia version >= v1.11
  src/Oceananigans.jl
Labels: package 📦

#4125 More README info about citing and model development papers
  README.md
  docs/src/index.md
Labels: documentation 📜, package 📦

#3977 Adds a pertubation advection open boundary matching scheme
  src/BoundaryConditions/BoundaryConditions.jl
  src/BoundaryConditions/perturbation_advection_open_boundary_matching_scheme.jl
  src/Models/Models.jl
  src/Models/boundary_mean.jl
  test/test_boundary_conditions_integration.jl
  validation/open_boundaries/cylinder.jl
Labels: feature 🌟, science 🌊, numerics 🧮
