Repository CliMA/Oceananigans.jl, pull requests merged in 2025-10, with the labels that each got.

#4790 Add a new tutorial for Models
  docs/Project.toml
  docs/make.jl
  docs/src/grids.md
  docs/src/model_setup/architecture.md
  docs/src/model_setup/clock.md
  docs/src/model_setup/diagnostics.md
  docs/src/model_setup/forcing_functions.md
  docs/src/model_setup/legacy_grids.md
  docs/src/model_setup/number_type.md
  docs/src/model_setup/overview.md
  docs/src/model_setup/setting_initial_conditions.md
  docs/src/model_setup/tracers.md
  docs/src/model_setup/turbulent_diffusivity_closures_and_les_models.md
  docs/src/quick_start.md
  docs/src/simulation_tips.md
Labels: documentation 📜

#4831 Support time stepping with DateTime clock
  src/OutputReaders/field_time_series.jl
  src/OutputReaders/field_time_series_indexing.jl
  src/OutputWriters/jld2_writer.jl
  src/Simulations/simulation.jl
  src/TimeSteppers/clock.jl
  src/Utils/Utils.jl
  src/Utils/schedules.jl
  src/Utils/times_and_datetimes.jl
  test/runtests.jl
  test/test_datetime_clock.jl
  validation/dateclocks/datetime_clock_timestepping.jl
Labels: feature 🌟

#4824 (0.100.1) Set CUDA.jl compatibility to v5.9+
  Project.toml
  docs/Project.toml
Labels: GPU 👾
