Repository CliMA/Oceananigans.jl, pull requests merged in 2025-08, with the labels that each got.

#4704 Regularize field boundary conditions with a location rather than a name
  src/BoundaryConditions/field_boundary_conditions.jl
Labels: cleanup 🧹

#4709 Informative error when using LagrangianParticles on Distributed archs
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/NonhydrostaticModels/nonhydrostatic_model.jl
Labels: distributed 🕸️, user interface/experience 💻

#4710 Correct the implicit Split-RK3 diffusion implementation
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_rk3_step.jl
  src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl
  test/test_dynamics.jl
Labels: numerics 🧮

#4660 Add grid reconstruction utilities to reconstruct Grids from NetCDF outputs
  ext/OceananigansNCDatasetsExt.jl
  src/Grids/latitude_longitude_grid.jl
  src/Grids/rectilinear_grid.jl
  src/ImmersedBoundaries/grid_fitted_bottom.jl
  src/ImmersedBoundaries/grid_fitted_boundary.jl
  src/ImmersedBoundaries/partial_cell_bottom.jl
  src/OutputWriters/netcdf_writer.jl
  test/runtests.jl
  test/test_grid_reconstruction.jl
Labels: output 💾, user interface/experience 💻
