Repository CliMA/Oceananigans.jl, pull requests merged in 2025-09, with the labels that each got.

#4687 (0.98.0) Modify interface for `OpenBoundaryCondition`s with `schemes` and use Tuples in `boundary_mass_fluxes`
  Project.toml
  src/BoundaryConditions/BoundaryConditions.jl
  src/BoundaryConditions/boundary_condition.jl
  src/BoundaryConditions/boundary_condition_classifications.jl
  src/BoundaryConditions/flat_extrapolation_open_boundary_matching_scheme.jl
  src/BoundaryConditions/perturbation_advection.jl
  src/Models/NonhydrostaticModels/boundary_mass_fluxes.jl
  src/MultiRegion/cubed_sphere_grid.jl
  src/Oceananigans.jl
  test/test_boundary_conditions_integration.jl
  test/test_conjugate_gradient_poisson_solver.jl
  validation/open_boundaries/2d_flow_over_bathymetry.jl
  validation/open_boundaries/cylinder.jl
  validation/open_boundaries/oscillating_flow.jl
Labels: boundary conditions 🏓

#4737 A new formulation for the split RK3 timestepper
  docs/oceananigans.bib
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/compute_slow_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/initialize_split_explicit_substepping.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/step_split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_field_tuples.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_rk3_step.jl
  src/Models/HydrostaticFreeSurfaceModels/implicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/z_star_vertical_spacing.jl
  src/Models/VarianceDissipationComputations/VarianceDissipationComputations.jl
  src/Models/VarianceDissipationComputations/advective_dissipation.jl
  src/Models/VarianceDissipationComputations/diffusive_dissipation.jl
  src/Models/VarianceDissipationComputations/update_fluxes.jl
  src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/time_step_catke_equation.jl
  test/test_split_explicit_vertical_integrals.jl
  validation/advection/one_dimensional_advection.jl
  validation/implicit_dissipation/variance_dissipation.jl
  validation/implicit_free_surface/geostrophic_adjustment_test.jl
  validation/z_star_coordinate/lock_release.jl
Labels: numerics 🧮

#4746 Add a docstring for RotatedLatitudeLongitudeGrid
  src/OrthogonalSphericalShellGrids/rotated_latitude_longitude_grid.jl
Labels: documentation 📜, grids 🗺️

#4727 Indexing for a `CallableCoordinate`
  docs/oceananigans.bib
  src/Grids/coordinate_utils.jl
  src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl
  test/test_grids.jl
Labels: grids 🗺️, user interface/experience 💻

#4755 Move Buildkite CI to Nautilus
  .buildkite/pipeline.yml
  src/Models/boundary_mean.jl
  test/test_boundary_conditions_integration.jl
  test/test_lagrangian_particle_tracking.jl
  test/test_multi_region_cubed_sphere.jl
Labels: testing 🧪

#4766 Once again, fix warning message formatting in SplitRungeKutta3TimeStepper
  src/TimeSteppers/split_hydrostatic_runge_kutta_3.jl
Labels: user interface/experience 💻

#4765 Do not specify `JULIA_NUM_THREADS` or `JULIA_NUM_PRECOMPILE_TASKS` for Buildkite CI
  .buildkite/pipeline.yml
Labels: testing 🧪

#4769 Enforce (temporarily) CUDA.jl < v5.8.3 for Buildkite CI docs
  docs/Project.toml
Labels: testing 🧪

#4787 Remove misleading benchmark scripts
  benchmark/benchmark_multi_GPU.jl
Labels: cleanup 🧹

#4802 Clarify few things in tripolar grid docstring
  docs/oceananigans.bib
  src/OrthogonalSphericalShellGrids/generate_tripolar_coordinates.jl
  src/OrthogonalSphericalShellGrids/tripolar_grid.jl
Labels: documentation 📜, grids 🗺️

#4563 Symmetrizing Laplacian in order to use conjugate gradient in nonuniform grids
  src/Models/NonhydrostaticModels/solve_for_pressure.jl
  src/Solvers/conjugate_gradient_poisson_solver.jl
  src/Solvers/fourier_tridiagonal_poisson_solver.jl
  validation/immersed_boundaries/staircase_convection.jl
  validation/immersed_boundaries/vortex_sheet.jl
Labels: numerics 🧮, immersed boundaries ⛰️

#4819 Further enhancements of the XESMF extension
  .buildkite/pipeline.yml
  .github/workflows/ci.yml
  ext/OceananigansXESMFExt.jl
  test/runtests.jl
  test/test_xesmf.jl
Labels: extensions 🧬
