Repository CliMA/Oceananigans.jl, pull requests merged in 2025-04, with the labels that each got.

#3794 Massive clean up for conditional operations
  src/AbstractOperations/conditional_operations.jl
  src/AbstractOperations/derivatives.jl
  src/AbstractOperations/metric_field_reductions.jl
  src/Fields/abstract_field.jl
  src/Fields/field.jl
  src/ImmersedBoundaries/immersed_boundary_condition.jl
  src/ImmersedBoundaries/immersed_reductions.jl
  src/OutputReaders/field_time_series_reductions.jl
  test/dependencies_for_runtests.jl
  test/test_conditional_reductions.jl
  test/test_field.jl
  test/test_output_readers.jl
Labels: performance 🏍️, cleanup 🧹

#4350 Use polar criteria to build PolarBoundaryCondition
  src/BoundaryConditions/field_boundary_conditions.jl
  src/BoundaryConditions/polar_boundary_condition.jl
  test/test_boundary_conditions.jl
Labels: grids 🗺️

#4342 Zstar test that actually test conservation
  test/test_zstar_coordinate.jl
Labels: grids 🗺️

#4353 Add validation for `condition` kwarg in `ConditionalOperation` for immersed boundary grids
  src/AbstractOperations/conditional_operations.jl
  src/ImmersedBoundaries/immersed_reductions.jl
  test/test_field_scans.jl
Labels: immersed boundaries ⛰️

#4370 Require `interval::Int` in IterationInterval?
  src/Utils/schedules.jl
Labels: user interface/experience 💻

#4360 Test zstar on a tripolar grid
  test/test_zstar_coordinate.jl
Labels: testing 🧪, grids 🗺️

#4392 Change isopycnal_skew_symmetric_diffusivity.jl to use DiffusiveFormulation
  src/TurbulenceClosures/turbulence_closure_implementations/isopycnal_skew_symmetric_diffusivity.jl
Labels: turbulence closures 🎐

#4271 Implement an interface for writing output with Simulation
  ext/OceananigansNCDatasetsExt.jl
  src/OutputWriters/checkpointer.jl
  src/OutputWriters/jld2_writer.jl
  src/Simulations/run.jl
  src/Simulations/simulation.jl
Labels: output 💾, simulation 🎮

#4418 Add link to docstring of ConditionalOperations in the docs for various reductions
  src/AbstractOperations/metric_field_reductions.jl
Labels: documentation 📜

#4426 Add CATKE and GPU dycore paper references
  README.md
  docs/oceananigans.bib
  docs/src/index.md
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_vertical_diffusivity.jl
Labels: documentation 📜

#4375 Add a performance benchmark pipeline
  .buildkite/pipeline-benchmarks.yml
  test/benchmark_tests.jl
Labels: performance 🏍️, testing 🧪, benchmark performance

#4442 Improve benchmarks yml
  .buildkite/pipeline-benchmarks.yml
  test/benchmark_tests.jl
Labels: benchmark performance

#4440 Compute the difference between the latest main and the PR
  .buildkite/pipeline-benchmarks.yml
  .buildkite/pipeline.yml
Labels: benchmark performance

#4427 Update CATKE docstring
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/TKEBasedVerticalDiffusivities.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/catke_vertical_diffusivity.jl
Labels: documentation 📜, turbulence closures 🎐

#4444 Add Souza et al. 2025 + reorder refs chronologically
  docs/src/index.md
Labels: documentation 📜

#4407 Fused multiply add (fma) in stencil operations
  Project.toml
  src/Advection/Advection.jl
  src/Advection/centered_reconstruction.jl
  src/Advection/upwind_biased_reconstruction.jl
  src/Advection/weno_interpolants.jl
Labels: benchmark performance

#4432 Add newton_div utility for fast (but approximate) mixed-precision computation of divisions
  src/Advection/weno_interpolants.jl
  src/Advection/weno_reconstruction.jl
  src/Utils/Utils.jl
  src/Utils/newton_div.jl
Labels: performance 🏍️, numerics 🧮, benchmark performance

#4431 Add operators functions for reciprocals of metrics
  src/Advection/cell_advection_timescale.jl
  src/Advection/momentum_advection_operators.jl
  src/Advection/tracer_advection_operators.jl
  src/Advection/vector_invariant_advection.jl
  src/Advection/vector_invariant_self_upwinding.jl
  src/Coriolis/hydrostatic_spherical_coriolis.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/step_split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_w_from_continuity.jl
  src/Models/HydrostaticFreeSurfaceModels/matrix_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/pcg_implicit_free_surface_solver.jl
  src/Models/HydrostaticFreeSurfaceModels/z_star_vertical_spacing.jl
  src/Models/ShallowWaterModels/shallow_water_diffusion_operators.jl
  src/Operators/Operators.jl
  src/Operators/derivative_operators.jl
  src/Operators/divergence_operators.jl
  src/Operators/laplacian_operators.jl
  src/Operators/reciprocal_metric_operators.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  src/Operators/topology_aware_operators.jl
  src/Operators/vorticity_operators.jl
  src/Solvers/conjugate_gradient_poisson_solver.jl
  src/TurbulenceClosures/abstract_scalar_biharmonic_diffusivity_closure.jl
  src/TurbulenceClosures/closure_kernel_operators.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/TKEBasedVerticalDiffusivities.jl
  test/test_operators.jl
Labels: performance 🏍️, numerics 🧮, benchmark performance

#4447 Use vertical spacing reciprocal in implicit solver
  src/Operators/reciprocal_metric_operators.jl
  src/Operators/spacings_and_areas_and_volumes.jl
  src/TurbulenceClosures/vertically_implicit_diffusion_solver.jl
Labels: benchmark performance

#4441 (0.96.22) Make NetCDFWriter work with GPU grids with stretched dimensions
  Project.toml
  ext/OceananigansNCDatasetsExt.jl
  test/test_netcdf_writer.jl
Labels: output 💾

#3698 Add Distributed grids section in Grids tutorial
  docs/Project.toml
  docs/make.jl
  docs/src/grids.md
Labels: documentation 📜, distributed 🕸️

#4449 Export CATKE and k-ε
  docs/src/appendix/library.md
  src/Oceananigans.jl
  src/TurbulenceClosures/TurbulenceClosures.jl
  src/TurbulenceClosures/turbulence_closure_implementations/TKEBasedVerticalDiffusivities/TKEBasedVerticalDiffusivities.jl
Labels: turbulence closures 🎐, user interface/experience 💻

#3920 support for active_cells_map in kernels
  ext/OceananigansAMDGPUExt.jl
  ext/OceananigansMetalExt.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/barotropic_split_explicit_corrector.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/compute_slow_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/cache_hydrostatic_free_surface_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/compute_hydrostatic_free_surface_tendencies.jl
  src/Models/NonhydrostaticModels/compute_nonhydrostatic_tendencies.jl
  src/Utils/kernel_launching.jl
Labels: cleanup 🧹, 🚨 DO NOT MERGE 🚨, benchmark performance

#4368 Remove assumption about X/YFaceField on TripolarGrid by generalizing `default_auxiliary_boundary_condition`
  src/BoundaryConditions/field_boundary_conditions.jl
  src/BoundaryConditions/fill_halo_regions_zipper.jl
  src/BoundaryConditions/show_boundary_conditions.jl
  src/Fields/field.jl
  src/Models/HydrostaticFreeSurfaceModels/HydrostaticFreeSurfaceModels.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/split_explicit_free_surface.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_field_tuples.jl
  src/Models/HydrostaticFreeSurfaceModels/hydrostatic_free_surface_model.jl
  src/Models/HydrostaticFreeSurfaceModels/prescribed_hydrostatic_velocity_fields.jl
  src/MultiRegion/multi_region_field.jl
  src/MultiRegion/multi_region_split_explicit_free_surface.jl
  src/OrthogonalSphericalShellGrids/OrthogonalSphericalShellGrids.jl
  src/OrthogonalSphericalShellGrids/distributed_tripolar_grid.jl
  src/OrthogonalSphericalShellGrids/tripolar_field_extensions.jl
  test/test_tripolar_grid.jl
Labels: grids 🗺️

#4456 Bugfix in RK3 previous fields
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/compute_slow_tendencies.jl
  src/Models/HydrostaticFreeSurfaceModels/SplitExplicitFreeSurfaces/split_explicit_free_surface.jl
Labels: bug 🐞
